#!/usr/bin/env python3
"""SIMULATION ONLY.  Emit rtl/gen/wintb_top.sv around the GENERATED system bus AND memory bus of
PynqZ2RocketBigLittlePextTacitMicRgbBwWinConfig (MEMORY_BANDWIDTH.md section 9).

What is real: SystemBus.sv (the sbus crossbar, BwWindow's four 128-bit lanes and their core-clock
TLBuffers and TLAsyncCrossingSources, BwProbe, the DMA aperture's shrinker/map/filters and its
crossing source) and MemoryBus.sv (every crossing sink, the lanes' TLWidthWidget16 and buffers, the
6x5 mbus crossbar, patch 0061's buffers, the four TLToAXI4 / AXI4IdIndexer / AXI4UserYanker chains),
wired to each other through their async ports exactly as ChipTop wires them.
What is not: the AXI4 memory behind each channel (csrc/main.cpp), the harts (a C++ TileLink master
drives tile 0's master port), the L2 (its crossing into the memory bus is held idle), and the pbus
(MMIO is driven straight into the register nodes' TL-UL ports).  TWO CLOCKS: the system bus on
FCLK0, the memory bus on FCLK1, each at its own period (csrc/main.cpp)."""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
CFG = 'PynqZ2RocketBigLittlePextTacitMicRgbBwWinConfig'

def ports(sv, mod):
    txt = open(sv).read()
    m = re.search(r'^module %s\((.*?)^\);' % re.escape(mod), txt, re.S | re.M)
    out = []
    for line in m.group(1).split('\n'):
        line = line.split('//')[0]
        mm = re.match(r'\s*(input|output)\s*(\[[^\]]+\])?\s*(\w+)', line)
        if mm: out.append((mm.group(1), mm.group(2) or '', mm.group(3)))
    return out

def main():
    if len(sys.argv) > 1 and sys.argv[1] == '--config': print(CFG); return
    root = os.environ.get('WINTB_GENSRC_ROOT') or sys.exit('set WINTB_GENSRC_ROOT to <chipyard>/sims/verilator/generated-src')
    gen = os.path.join(root, 'chipyard.harness.TestHarness.' + CFG, 'gen-collateral')
    sb = ports(os.path.join(gen, 'SystemBus.sv'), 'SystemBus')
    mb = ports(os.path.join(gen, 'MemoryBus.sv'), 'MemoryBus')
    top, decl, csb, cmb = ['input clk0', 'input rst0', 'input clk1', 'input rst1'], [], [], []
    mbnames = {p: (d, w) for d, w, p in mb}
    paired = set()
    # async crossings: SystemBus auto_<X>_xsrc_out_<rest>  <->  MemoryBus auto_<X>_xsink_in_<rest>
    for d, w, p in sb:
        m = re.match(r'auto_(.+)_xsrc_out_(.+)$', p)
        if not m: continue
        peer = 'auto_%s_xsink_in_%s' % (m.group(1), m.group(2))
        assert peer in mbnames, peer
        net = 'x_%s_%s' % (m.group(1), m.group(2))
        decl.append('  wire %s %s;' % (w, net))
        csb.append('.%s(%s)' % (p, net)); cmb.append('.%s(%s)' % (peer, net)); paired.add(peer)
    def expose(prefix_map, d, w, p):
        for pre, short in prefix_map:
            if p.startswith(pre):
                n = short + p[len(pre):]
                top.append('%s %s %s' % (d, w, n)); return n
        return None
    SB_EXPOSE = [('auto_win_mmio_in_', 'win_'), ('auto_probe_mmio_in_', 'prb_'),
                 ('auto_coupler_from_rockettile_tl_master_clock_xing_in_0_', 't0_')]
    MB_EXPOSE = [('auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_%d_' % c, 'axi%d_' % c) for c in range(4)]
    def tie(d, w, p, conns, mod):
        if d == 'input':
            v = "1'b1" if p.endswith('_ready') else "'0"
            conns.append('.%s(%s)' % (p, v))
        else:
            decl.append('  wire %s nc_%s_%s;' % (w, mod, p)); conns.append('.%s(nc_%s_%s)' % (p, mod, p))
    for d, w, p in sb:
        if re.match(r'auto_(.+)_xsrc_out_', p): continue
        if p in ('auto_sbus_clock_groups_in_member_sbus_0_clock', 'auto_sbus_clock_groups_in_member_sbus_1_clock'):
            csb.append('.%s(clk0)' % p); continue
        if p in ('auto_sbus_clock_groups_in_member_sbus_0_reset', 'auto_sbus_clock_groups_in_member_sbus_1_reset'):
            csb.append('.%s(rst0)' % p); continue
        n = expose(SB_EXPOSE, d, w, p)
        if n: csb.append('.%s(%s)' % (p, n)); continue
        tie(d, w, p, csb, 'sb')
    for d, w, p in mb:
        if p in paired: continue
        if p == 'auto_mbus_clock_groups_in_member_mbus_0_clock': cmb.append('.%s(clk1)' % p); continue
        if p == 'auto_mbus_clock_groups_in_member_mbus_0_reset': cmb.append('.%s(rst1)' % p); continue
        n = expose(MB_EXPOSE, d, w, p)
        if n: cmb.append('.%s(%s)' % (p, n)); continue
        tie(d, w, p, cmb, 'mb')
    out = ['// GENERATED by gen_top.py for %s -- SIMULATION ONLY' % CFG,
           'module wintb_top (', ',\n'.join('  ' + x for x in top), ');'] + decl + [
           '  SystemBus sbus (', ',\n'.join('    ' + c for c in csb), '  );',
           '  MemoryBus mbus (', ',\n'.join('    ' + c for c in cmb), '  );', 'endmodule', '']
    os.makedirs(os.path.join(HERE, 'rtl', 'gen'), exist_ok=True)
    dst = os.path.join(HERE, 'rtl', 'gen', 'wintb_top.sv')
    open(dst, 'w').write('\n'.join(out))
    print(dst)

main()
