// SIMULATION ONLY.  The generated bypass memory bus (MemoryBus.sv of the bypass config) against a
// behavioural AXI4 memory on each channel.  MEMORY_BANDWIDTH.md section 8.
//
//   Vbyptb_top [--lat L] [--cap C] [--rows N] [--sets L0,L1,L01,SEQ] [--outs 1,2,4,8,12,16]
//
// The memory: AR accepted while fewer than C bursts are outstanding on that channel (the as-run AFI
// read issue cap is 8, bwlab/axiceil/asrun_ddrc_afi_*.json); the first beat of a burst is eligible L
// cycles after its AR handshake; bursts are returned one at a time, never interleaved (the port
// promises interleavedId = Some(0)), in the order they became eligible; one beat per cycle.  Data is
// a function of address, so every checksum is computed independently of the DUT.
#include "Vbyptb_top.h"
#include "verilated.h"
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <deque>
#include <string>
#include <vector>

static Vbyptb_top *top;
static uint64_t now = 0;

static uint64_t word_at(uint64_t addr) {
  uint64_t x = addr * 0x9E3779B97F4A7C15ULL;
  x ^= x >> 29; x *= 0xBF58476D1CE4E5B9ULL; x ^= x >> 32;
  return x;
}

struct Burst { uint8_t id; uint64_t addr; unsigned beats; uint64_t ready_at; };

struct Mem {
  int ch; unsigned lat; unsigned cap;
  std::deque<Burst> pending;      // accepted, in AR order
  bool active = false; Burst cur; unsigned beat = 0;
  uint64_t bursts = 0, beats = 0;
};

// ---- port access, one channel at a time ----------------------------------------------------
#ifndef NCH
#define NCH 2
#endif
#if NCH == 4
#define CHP(c, f) ((c) == 0 ? top->axi0_##f : (c) == 1 ? top->axi1_##f : (c) == 2 ? top->axi2_##f : top->axi3_##f)
#define CHSET(c, f, v) do { switch (c) { case 0: top->axi0_##f = (v); break; case 1: top->axi1_##f = (v); break; \
                                          case 2: top->axi2_##f = (v); break; default: top->axi3_##f = (v); } } while (0)
#else
#define CHP(c, f) ((c) == 0 ? top->axi0_##f : top->axi1_##f)
#define CHSET(c, f, v) do { if ((c) == 0) top->axi0_##f = (v); else top->axi1_##f = (v); } while (0)
#endif

static void mem_drive(Mem &m) {
  int c = m.ch;
  CHSET(c, ar_ready, m.pending.size() + (m.active ? 1 : 0) < m.cap);
  CHSET(c, aw_ready, 0); CHSET(c, w_ready, 0); CHSET(c, b_valid, 0);
  if (!m.active) {
    // the eligible burst that has waited longest
    for (size_t i = 0; i < m.pending.size(); i++) {
      if (m.pending[i].ready_at <= now) {
        m.cur = m.pending[i]; m.pending.erase(m.pending.begin() + i);
        m.active = true; m.beat = 0; break;
      }
    }
  }
  if (m.active) {
    CHSET(c, r_valid, 1);
    CHSET(c, r_bits_id, m.cur.id);
    CHSET(c, r_bits_data, word_at(m.cur.addr + 8ULL * m.beat));
    CHSET(c, r_bits_resp, 0);
    CHSET(c, r_bits_last, m.beat + 1 == m.cur.beats);
  } else {
    CHSET(c, r_valid, 0); CHSET(c, r_bits_last, 0);
  }
}

struct Hs { bool ar; uint8_t id; uint64_t addr; unsigned len; unsigned size; unsigned burst; bool r; };

static Hs mem_sample(Mem &m) {
  int c = m.ch; Hs h{};
  h.ar = CHP(c, ar_valid) && CHP(c, ar_ready);
  h.id = CHP(c, ar_bits_id); h.addr = CHP(c, ar_bits_addr); h.len = CHP(c, ar_bits_len);
  h.size = CHP(c, ar_bits_size); h.burst = CHP(c, ar_bits_burst);
  h.r = CHP(c, r_valid) && CHP(c, r_ready);
  if (CHP(c, aw_valid) || CHP(c, w_valid)) { fprintf(stderr, "unexpected write on channel %d\n", c); exit(3); }
  return h;
}

static void mem_update(Mem &m, const Hs &h) {
  if (h.ar) {
    if (h.size != 3 || h.burst != 1 || h.len != 7) {
      fprintf(stderr, "channel %d: AR size %u burst %u len %u\n", m.ch, h.size, h.burst, h.len); exit(3);
    }
    m.pending.push_back(Burst{h.id, h.addr, h.len + 1, now + m.lat});
    m.bursts++;
  }
  if (h.r) {
    m.beats++;
    if (++m.beat == m.cur.beats) m.active = false;
  }
}

static Mem mems[NCH];

// ---- one cycle -------------------------------------------------------------------------------
static void cycle() {
  for (auto &m : mems) mem_drive(m);
  top->clock = 0; top->eval();
  Hs h[NCH]; for (int c = 0; c < NCH; c++) h[c] = mem_sample(mems[c]);
  top->clock = 1; top->eval();
  for (int c = 0; c < NCH; c++) mem_update(mems[c], h[c]);
  now++;
}

// ---- TL-UL register access through the generated TLAsyncCrossingSource ------------------------
static const uint64_t BASE = 0x100b0000ULL;

static uint64_t tl(bool put, uint64_t off, uint64_t data) {
  top->mmio_a_valid = 1;
  top->mmio_a_bits_opcode = put ? 0 : 4;      // PutFullData / Get
  top->mmio_a_bits_param = 0; top->mmio_a_bits_size = 3; top->mmio_a_bits_source = 0;
  top->mmio_a_bits_address = BASE + off; top->mmio_a_bits_mask = 0xff;
  top->mmio_a_bits_data = put ? data : 0; top->mmio_a_bits_corrupt = 0;
  top->mmio_d_ready = 1;
  // hold A until accepted
  for (int i = 0; ; i++) {
    for (auto &m : mems) mem_drive(m);
    top->clock = 0; top->eval();
    bool acc = top->mmio_a_ready;
    Hs h[NCH]; for (int c = 0; c < NCH; c++) h[c] = mem_sample(mems[c]);
    top->clock = 1; top->eval();
    for (int c = 0; c < NCH; c++) mem_update(mems[c], h[c]); now++;
    if (acc) break;
    if (i > 100000) { fprintf(stderr, "mmio A never accepted\n"); exit(4); }
  }
  top->mmio_a_valid = 0;
  for (int i = 0; ; i++) {
    for (auto &m : mems) mem_drive(m);
    top->clock = 0; top->eval();
    bool got = top->mmio_d_valid; uint64_t d = top->mmio_d_bits_data; bool den = top->mmio_d_bits_denied;
    Hs h[NCH]; for (int c = 0; c < NCH; c++) h[c] = mem_sample(mems[c]);
    top->clock = 1; top->eval();
    for (int c = 0; c < NCH; c++) mem_update(mems[c], h[c]); now++;
    if (got) { if (den) { fprintf(stderr, "mmio denied at +0x%llx\n", (unsigned long long)off); exit(4); } return d; }
    if (i > 100000) { fprintf(stderr, "mmio D never came\n"); exit(4); }
  }
}
static void wr(uint64_t off, uint64_t v) { tl(true, off, v); }
static uint64_t rd(uint64_t off) { return tl(false, off, 0); }

// ---- a point -----------------------------------------------------------------------------------
static const uint64_t BUF = 0x82000000ULL;

struct Set { const char *name; unsigned mask; bool seq; };

static void point(const Set &s, int out, unsigned rows) {
  const unsigned lanes = NCH; const uint64_t stride = 64 * lanes;
  uint64_t sw = 0;
  for (unsigned l = 0; l < lanes; l++) {
    uint64_t lb = 0x100 + l * 0x40;
    if (s.seq && l == 0) {
      wr(lb + 0x00, BUF); wr(lb + 0x08, rows); wr(lb + 0x10, 1); wr(lb + 0x18, 0);
    } else {
      wr(lb + 0x00, BUF + l * 64); wr(lb + 0x08, 1); wr(lb + 0x10, rows); wr(lb + 0x18, stride);
    }
    if (s.mask & (1u << l)) {
      if (s.seq && l == 0) {
        for (uint64_t b = 0; b < rows; b++) for (int w = 0; w < 8; w++) sw ^= word_at(BUF + 64 * b + 8 * w);
      } else {
        for (uint64_t r = 0; r < rows; r++) for (int w = 0; w < 8; w++) sw ^= word_at(BUF + l * 64 + stride * r + 8 * w);
      }
    }
  }
  wr(0x010, out); wr(0x008, s.mask);
  uint64_t b0[NCH]; for (int c = 0; c < NCH; c++) b0[c] = mems[c].beats;
  wr(0x000, 1);
  while (rd(0x018) & 1) {}
  uint64_t cyc = rd(0x020), beats = rd(0x028), reqs = rd(0x030), ck = rd(0x038), den = rd(0x040), peak = rd(0x048);
  printf("BYPTB nch=%d lat=%u cap=%u set=%s out=%d cycles=%llu beats=%llu reqs=%llu bpc=%.4f cyc_per_get=%.3f peak=%llu denied=%llu",
         NCH, mems[0].lat, mems[0].cap, s.name, out, (unsigned long long)cyc, (unsigned long long)beats, (unsigned long long)reqs,
         8.0 * beats / cyc, (double)cyc / reqs, (unsigned long long)peak, (unsigned long long)den);
  for (unsigned l = 0; l < lanes; l++) {
    uint64_t lb = 0x100 + l * 0x40;
    printf(" lane%u(c=%llu b=%llu r=%llu p=%llu)", l, (unsigned long long)rd(lb + 0x20), (unsigned long long)rd(lb + 0x28),
           (unsigned long long)rd(lb + 0x30), (unsigned long long)(rd(lb + 0x38) & 0xff));
  }
  printf(" ch_beats=");
  for (int c = 0; c < NCH; c++) printf("%s%llu", c ? "/" : "", (unsigned long long)(mems[c].beats - b0[c]));
  printf(" cksum=%s\n", ck == sw ? "ok" : "MISMATCH");
  fflush(stdout);
}

int main(int argc, char **argv) {
  Verilated::commandArgs(argc, argv);
  unsigned lat = 16, cap = 8, rows = 2048;
  std::string sets = "L0,L1,L01,SEQ", outs = "1,2,4,8,12,16";
  for (int i = 1; i < argc; i++) {
    if (!strcmp(argv[i], "--lat") && i + 1 < argc) lat = atoi(argv[++i]);
    else if (!strcmp(argv[i], "--cap") && i + 1 < argc) cap = atoi(argv[++i]);
    else if (!strcmp(argv[i], "--rows") && i + 1 < argc) rows = atoi(argv[++i]);
    else if (!strcmp(argv[i], "--sets") && i + 1 < argc) sets = argv[++i];
    else if (!strcmp(argv[i], "--outs") && i + 1 < argc) outs = argv[++i];
  }
  top = new Vbyptb_top;
  for (int c = 0; c < NCH; c++) { mems[c].ch = c; mems[c].lat = lat; mems[c].cap = cap; }
  top->buf_a_ready = 1; top->buf_d_valid = 0;
  top->mmio_a_valid = 0; top->mmio_d_ready = 1;
  top->reset = 1;
  for (int i = 0; i < 50; i++) cycle();
  top->reset = 0;
  for (int i = 0; i < 50; i++) cycle();
  uint64_t geo = rd(0x050);
  printf("BYPTB geometry=0x%llx depth=%llu lanes=%llu get=%llu\n", (unsigned long long)geo,
         (unsigned long long)(geo & 0xff), (unsigned long long)((geo >> 8) & 0xff), (unsigned long long)((geo >> 16) & 0xffff));
  static const Set all[] = {{"L0", 1, false}, {"L1", 2, false}, {"L01", 3, false}, {"SEQ", 1, true},
                            {"L2", 4, false}, {"L02", 5, false}, {"L012", 7, false}, {"L013", 11, false},
                            {"L23", 12, false}, {"L0123", 15, false}};
  std::vector<int> ov;
  for (char *t = strtok(&outs[0], ","); t; t = strtok(nullptr, ",")) ov.push_back(atoi(t));
  std::vector<std::string> sv;
  { std::string s2 = sets; for (char *t = strtok(&s2[0], ","); t; t = strtok(nullptr, ",")) sv.push_back(t); }
  for (auto &sn : sv)
    for (auto &a : all)
      if (sn == a.name)
        for (int o : ov) point(a, o, rows);
  delete top;
  return 0;
}
