"""B147: the quantisation cost ON NEGATIVES, and where the bench's false STOPs come from.

B144 measured the int8 lowering against float on a held-out split that is mostly positives
(argmax agreement 0.9996, max |dP| 0.228) and reported a procedural-indoor false alarm of
0.022.  B146's live demo fires STOP on an empty ceiling about half the time.  This computes
the 2x2 that separates the two candidate causes:

                         procedural indoor_neg      the real bench frames
    float torch                 (a)                        (c)
    int8 generated C            (b)                        (d)

(a) reproduces B144's number, (b)-(a) is the quantisation cost on ITS OWN negatives, (c)-(a)
is the distribution gap, and (d) is what the board does.  Same metric throughout: per-FRAME
peak objectness = max over cells of max(P_stop, P_yield), fired = peak > thr -- eval_heldout.py's
metric, not a per-cell one.
"""
from __future__ import annotations
import argparse, json, os, sys
import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(os.path.dirname(HERE), "moonshine"))
import _paths                                # noqa: E402
import make_data as md                      # noqa: E402
from model import SignDetLite, GRID         # noqa: E402
import hostrun                              # noqa: E402


def peak_obj(P):
    """(N,3,8,8) -> (N,) per-frame peak objectness, eval_heldout.py's definition."""
    return P[:, 1:].max(axis=1).reshape(len(P), -1).max(1)


def float_probs(m, X):
    out = []
    with torch.no_grad():
        for i in range(0, len(X), 512):
            xb = torch.from_numpy(X[i:i + 512].astype(np.float32) / 255.0).permute(0, 3, 1, 2)
            out.append(torch.softmax(m.features(xb), dim=1).numpy())
    return np.concatenate(out)


def int8_probs(exe, X, workdir, oscale, ozp):
    """host_gate.py's held-out path: the front end's own 1/127 quantisation, then the C."""
    q = np.clip((2 * 127 * X.astype(np.uint32) + 255) // 510, 0, 127)
    q = q.astype(np.int8).transpose(0, 3, 1, 2).reshape(len(X), -1)
    o = hostrun.batch(exe, q, GRID * GRID * 3, workdir)
    return ((o.astype(np.float32) - ozp) * oscale).reshape(len(X), GRID, GRID, 3).transpose(0, 3, 1, 2)


def thr_for_rate(scores, rate):
    """Smallest threshold whose fired-rate is <= rate."""
    s = np.sort(scores)[::-1]
    k = int(np.floor(rate * len(s)))
    return 0.0 if k >= len(s) else float(s[k])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen", default=_paths.out("signdet/gen"))
    ap.add_argument("--ir", default=_paths.out("signdet/ir"))
    ap.add_argument("--ckpt", default=_paths.work("b144/run/signdet_b144.pt"))
    ap.add_argument("--gtsdb", default=_paths.work("b144/data/FullIJCNN2013"))
    ap.add_argument("--probs", default=_paths.work("b147/run/probs.npz"))
    ap.add_argument("--labels", default=_paths.work("b147/labels.json"))
    ap.add_argument("--workdir", default=_paths.work("b147/hostc"))
    ap.add_argument("--out", default=_paths.work("b147/run"))
    ap.add_argument("--n", type=int, default=900)
    ap.add_argument("--thr", type=float, default=0.5)
    a = ap.parse_args()

    g = json.load(open(os.path.join(a.ir, "graph.json")))
    oq = g["tensors"][g["output"]["tensor"]]["quant"]
    oscale, ozp = float(oq["scale"]), int(oq["zero_point"])
    exe = hostrun.build(a.gen, a.workdir)
    m = SignDetLite(); m.load_state_dict(torch.load(a.ckpt, map_location="cpu")); m.eval()

    # ---- the real bench frames, already run by host_gate_unlabelled.py
    z = np.load(a.probs)
    names = [str(x)[:-4] for x in z["files"]]
    lab = json.load(open(a.labels))["frames"]
    Pf, Pc = z["P_f"], z["P_c"]
    y = np.array([lab[n][0] for n in names])
    conf = np.array([lab[n][1] for n in names])
    neg = y == "none"
    bf, bc = peak_obj(Pf), peak_obj(Pc)

    # ---- the procedural indoor negatives B144 scored 0.022 on, regenerated by its own code
    rng = np.random.default_rng(1234)
    Xi = np.stack([md.camera_sim(md.indoor_bg(rng), rng) for _ in range(a.n)])
    Pif, Pic = float_probs(m, Xi), int8_probs(exe, Xi, a.workdir, oscale, ozp)
    inf, inc = peak_obj(Pif), peak_obj(Pic)

    # ---- and the GTSDB road negatives, as a second reference point
    gt = md.load_gtsdb(a.gtsdb)
    pool = [n for n in sorted(os.listdir(a.gtsdb)) if n.endswith(".ppm") and int(n[:5]) >= 600]
    from PIL import Image
    Xr, cache, tries = [], {}, 0
    while len(Xr) < a.n and tries < a.n * 200:
        tries += 1
        nm = pool[rng.integers(len(pool))]
        if nm not in cache:
            if len(cache) > 200:
                cache.pop(next(iter(cache)))
            cache[nm] = np.asarray(Image.open(os.path.join(a.gtsdb, nm)).convert("RGB"))
        r = md.gtsdb_crop(cache[nm], gt.get(nm, []), rng, "neg")
        if r is None:
            continue
        Xr.append(md.camera_sim(r[0], rng))
    Xr = np.stack(Xr)
    rnf, rnc = peak_obj(float_probs(m, Xr)), peak_obj(int8_probs(exe, Xr, a.workdir, oscale, ozp))

    L = []
    def p(s=""):
        print(s); L.append(s)

    p("B147  the quantisation cost ON NEGATIVES")
    p("metric: per-FRAME peak objectness = max_cells max(P_stop,P_yield); fired = peak > %.2f" % a.thr)
    p("        (this is eval_heldout.py's own metric, so B144's 0.022 is directly comparable)")
    p()
    p("%-34s %5s %14s %14s %12s" % ("negative set", "n", "float FA", "int8 FA", "int8-float"))
    for nm, sf, sc in (("procedural indoor_neg (B144's)", inf, inc),
                       ("GTSDB road, no target (B144's)", rnf, rnc),
                       ("REAL bench frames, no sign", bf[neg], bc[neg]),
                       ("  of those, conf=high only", bf[neg & (conf == "high")],
                        bc[neg & (conf == "high")])):
        p("%-34s %5d %13.3f %14.3f %12s" % (nm, len(sf), (sf > a.thr).mean(), (sc > a.thr).mean(),
                                            "%+.3f" % ((sc > a.thr).mean() - (sf > a.thr).mean())))
    p()
    p("mean peak objectness   procedural %.3f -> %.3f | road %.3f -> %.3f | bench-neg %.3f -> %.3f"
      % (inf.mean(), inc.mean(), rnf.mean(), rnc.mean(), bf[neg].mean(), bc[neg].mean()))
    p("p99  peak objectness   procedural %.3f -> %.3f | road %.3f -> %.3f | bench-neg %.3f -> %.3f"
      % (np.percentile(inf, 99), np.percentile(inc, 99), np.percentile(rnf, 99),
         np.percentile(rnc, 99), np.percentile(bf[neg], 99), np.percentile(bc[neg], 99)))
    p()
    d = bc[neg] - bf[neg]
    p("int8 - float on the %d no-sign bench frames:" % neg.sum())
    p("  mean %+.4f  median %+.4f  sd %.4f  min %+.4f  max %+.4f  |  >0 on %d/%d"
      % (d.mean(), np.median(d), d.std(ddof=1), d.min(), d.max(), (d > 0).sum(), len(d)))
    for lo, hi in ((-1, -0.05), (-0.05, 0.0), (0.0, 0.05), (0.05, 0.10), (0.10, 0.15),
                   (0.15, 0.20), (0.20, 1.0)):
        p("  %+.2f .. %+.2f : %2d" % (lo, hi, int(((d > lo) & (d <= hi)).sum())))
    flip = neg & (bf <= a.thr) & (bc > a.thr)
    unflip = neg & (bf > a.thr) & (bc <= a.thr)
    p("  crossed 0.50 upward because of int8: %d frames %s" % (flip.sum(), [names[i] for i in np.where(flip)[0]]))
    p("  crossed 0.50 downward:               %d frames %s" % (unflip.sum(), [names[i] for i in np.where(unflip)[0]]))
    p()
    di = inc - inf
    p("int8 - float on the %d procedural indoor negatives: mean %+.4f median %+.4f max %+.4f"
      % (len(di), di.mean(), np.median(di), di.max()))
    p()
    p("THRESHOLDS that equalise the false-alarm rate on the real no-sign bench frames")
    for tgt in (0.022, 0.05, 0.10, 0.20, bf[neg].mean() * 0 + (bf[neg] > a.thr).mean()):
        p("  FA %.3f needs  float thr %.3f   int8 thr %.3f"
          % (tgt, thr_for_rate(bf[neg], tgt), thr_for_rate(bc[neg], tgt)))
    p("  int8 thr that matches FLOAT's FA at 0.50 (%.3f): %.3f"
      % ((bf[neg] > a.thr).mean(), thr_for_rate(bc[neg], (bf[neg] > a.thr).mean())))
    p()
    pos = ~neg
    p("what that threshold costs on the %d sign-present bench frames (recall, ANY class):" % pos.sum())
    for t in (0.50, 0.60, 0.70, 0.80, 0.90, 0.95):
        p("  thr %.2f : float %d/%d  int8 %d/%d   (no-sign FA float %.3f int8 %.3f)"
          % (t, (bf[pos] > t).sum(), pos.sum(), (bc[pos] > t).sum(), pos.sum(),
             (bf[neg] > t).mean(), (bc[neg] > t).mean()))

    open(os.path.join(a.out, "negatives.txt"), "w").write("\n".join(L) + "\n")
    np.savez_compressed(os.path.join(a.out, "negscores.npz"),
                        indoor_f=inf, indoor_c=inc, road_f=rnf, road_c=rnc,
                        bench_f=bf, bench_c=bc, y=y, conf=conf, names=np.array(names))
    print("\nwrote %s/{negatives.txt,negscores.npz}" % a.out)


if __name__ == "__main__":
    main()
