/* @generated by fpga/pynq-z2/modelblaster/signdet/bake_live_frames.py -- do not edit. */
/*
 * Lab B146's replay gate.  Each entry is one REAL HM01B0 capture -- 324 lines of a 326-byte
 * stride, exactly what the DMA delivers -- together with the answer the HOST-C build of this
 * same generated model gave for it, decoded at the threshold named below.
 *
 * `host_out` is the host's WHOLE 192-byte output tensor, so a board that agrees on the class
 * but not on the tensor is still caught.  `truth` is B144's hand label; the FILENAME is not a
 * label -- it records the old GTSRB classifier's wrong guess.
 */
#ifndef SIGNDET_FRAMES_H
#define SIGNDET_FRAMES_H
#include <stdint.h>
#define SDF_N           8
#define SDF_FRAME_BYTES 105624
#define SDF_OUT_LEN     192
#define SDF_GRID        8
#define SDF_THR_PCT     50
#define SDF_IR_MD5      "5e3ac0705fe5ef1beb7a35afc2b15138"

struct signdet_frame {
	const uint8_t *bytes;      /* SDF_FRAME_BYTES of raw Bayer, as the DMA delivers it */
	const int8_t  *host_out;   /* SDF_OUT_LEN of the host-C model's output */
	const char    *name;       /* the capture's file stem */
	const char    *truth;      /* B144's hand label: background / stop / yield */
	int8_t         host_cls;   /* 0 background, 1 stop, 2 yield -- at SDF_THR_PCT */
	int8_t         host_gx, host_gy;
	int8_t         host_q;     /* the peak cell's quantised objectness */
	uint8_t        host_pct;
	const char    *note;
};
extern const struct signdet_frame signdet_frames[SDF_N];
#endif /* SIGNDET_FRAMES_H */
