/* SPDX-License-Identifier: Apache-2.0
 *
 * Host generator for main.c's second dispatch: a multi-tile linear (M2 x K2 -> N2) whose golden
 * is computed here, so the SoC simulation spends no hart-0 cycles on the reference.  Writes
 * golden2.h: the input, weights, bias, requantisation and expected output, with the same xorshift
 * and the same reference arithmetic as main.c's ref_linear.
 *
 *   cc -O2 -o gen_golden2 gen_golden2.c && ./gen_golden2 > golden2.h
 */
#include <stdint.h>
#include <stdio.h>

#define M2 40
#define K2 288
#define N2 288
static const int32_t MULT2 = 1518500250, SHIFT2 = 12, AMIN2 = -128, AMAX2 = 127;

static int8_t w[N2 * K2], in[M2 * K2], out[M2 * N2];
static int32_t b[N2];

static void emit8(const char *name, const int8_t *v, int n)
{
	printf("static const int8_t %s[%d] = {", name, n);
	for (int i = 0; i < n; i++) printf("%s%d", i == 0 ? "\n" : ((i % 24) ? "," : ",\n"), v[i]);
	printf("\n};\n");
}

int main(void)
{
	uint64_t x = 0xD1B54A32D192ED03ULL;
	for (int i = 0; i < N2 * K2; i++) { x ^= x << 13; x ^= x >> 7; x ^= x << 17; w[i] = (int8_t)x; }
	for (int i = 0; i < M2 * K2; i++) { x ^= x << 13; x ^= x >> 7; x ^= x << 17; in[i] = (int8_t)x; }
	for (int i = 0; i < N2; i++) { x ^= x << 13; x ^= x >> 7; x ^= x << 17; b[i] = (int32_t)(x % 200001) - 100000; }
	for (int m = 0; m < M2; m++)
		for (int n = 0; n < N2; n++) {
			int32_t acc = b[n];
			for (int k = 0; k < K2; k++) acc += (int32_t)in[m * K2 + k] * (int32_t)w[n * K2 + k];
			int64_t prod = ((int64_t)acc * MULT2 + (1LL << 30)) >> 31;
			int32_t s = (int32_t)prod;
			if (SHIFT2 > 0) s = (int32_t)(((int64_t)s + ((int64_t)1 << (SHIFT2 - 1))) >> SHIFT2);
			if (s < AMIN2) s = AMIN2;
			if (s > AMAX2) s = AMAX2;
			out[m * N2 + n] = (int8_t)s;
		}
	printf("/* generated by gen_golden2.c -- do not edit */\n");
	printf("#define M2 %d\n#define K2 %d\n#define N2 %d\n", M2, K2, N2);
	printf("#define MULT2 %d\n#define SHIFT2 %d\n#define AMIN2 %d\n#define AMAX2 %d\n", MULT2, SHIFT2, AMIN2, AMAX2);
	emit8("in2", in, M2 * K2);
	emit8("w2", w, N2 * K2);
	emit8("gold2", out, M2 * N2);
	printf("static const int32_t b2[%d] = {", N2);
	for (int i = 0; i < N2; i++) printf("%s%d", i == 0 ? "\n" : ((i % 12) ? "," : ",\n"), b[i]);
	printf("\n};\n");
	return 0;
}
