# SPDX-License-Identifier: Apache-2.0
#
# The WEIGHT LANE's clock and crossings, for every variant with has_wlane (`roccmoon2b`).
# MEMORY_BANDWIDTH.md sections 9.9 (the design) and 9.11 (what the first build of it found).
#
# A SEPARATE FILE from pynqz2_memclk.xdc, and not that file with a second group: the waivers there
# name the memory domain's structures (memrst_sync, the mbus reset catcher), which this build does
# not have.  What the two files share is the problem -- FCLK0 and FCLK1 both come from the 1000 MHz
# IO PLL, 1000/29 and 1000/10, with a common period of 2.9 us, so the default setup requirement
# between them is a fraction of a nanosecond that no path can meet.
#
# NO create_clock HERE: FCLK0 and FCLK1 are generated by the PS7 IP, which constrains them itself.
#
# ---- WHY THERE IS NO set_clock_groups IN THIS FILE, AND THAT IS THE POINT --------------------
#
# The first build of 0x5A5A0013 shipped this file with `set_clock_groups -asynchronous` AND two
# `set_max_delay -datapath_only` lines that were meant to bound the descriptor crossing.  Both
# failed silently, in two different ways, and report_cdc is what surfaced it (MEMORY_BANDWIDTH.md
# 9.11):
#
#   1. The max-delay lines named cells -- *u_core/d_base_reg*, *u_whalf/* -- that do not exist in
#      this netlist.  Queried on the routed design, all three filters matched ZERO cells.  `-quiet`
#      swallowed the empty-object warning, so the build said nothing.  A constraint that names
#      nothing looks exactly like a constraint that works.
#   2. Even with the right names they would have been IGNORED: a clock-group false path outranks
#      set_max_delay (UG903), so the group would have won.  Every report_cdc row in that build
#      shows it -- the Exception column reads "Asynch Clock Groups", never a max delay.
#
# So the asynchronous relationship is declared HERE by the bound itself, in both directions.  A
# max delay of one lane period (10 ns) replaces the impossible default requirement, `-datapath_only`
# ignores clock skew and removes the hold check, and unlike a false path it is a CONSTRAINT: if
# placement ever stretches a crossing past a lane cycle, the build says so instead of shrugging.
# tcl/build_rocket.tcl checks after synthesis that every object query in this file matched something
# and that both crossings really are bounded (WLANE_XDC_QUERY, WLANE_CDC_BOUND), and after routing
# that report_cdc has no unsafe or unknown endpoint left (WLANE_CDC).
set fclk0 [get_clocks -include_generated_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ *PS7_i/FCLKCLK[0]}]]
set fclk1 [get_clocks -include_generated_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ *PS7_i/FCLKCLK[1]}]]
set_max_delay -datapath_only -from $fclk0 -to $fclk1 10.000
set_max_delay -datapath_only -from $fclk1 -to $fclk0 10.000

# ---- The lane's crossings, all of them, and the waiver each one needs -------------------------
#
# Between the engine (FCLK0) and the weight half (FCLK1) there is exactly one interface, mbxr_wx:
#   * a request toggle and a completion toggle, each sampled by two ASYNC_REG flops in the
#     receiving domain (mbxr_wx_core.a / mbxr_wx_half.a) -- report_cdc calls these CDC-3, safe;
#   * an error toggle and the "W lane ready" bit (fence bit 41), the same structure;
#   * the fill count, Gray-coded, crossed by the same kind of pair;
#   * the QUASI-STATIC load descriptor (base, row_blocks, nrows, stride, fbuf, lgpw, cap), which is
#     NOT synchronised by design: the core writes it before the request toggles and does not touch
#     it again until the fill has cleared, so the lane samples it at least two lane cycles later.
#
# The last two are structures Vivado cannot recognise, because what makes them safe is a protocol
# it cannot see.  They are waived below BY ID AND BY EXACT PIN PATTERN -- never blanket -- so the
# gate keeps catching everything else, in particular any new data path that crosses without either
# a synchroniser or the handshake.  Measured on the first build's routed design: the worst
# descriptor path is 6.165 ns and the worst status path back 2.493 ns, both now bounded at 10 ns.
#
# CDC-1 / CDC-15: the quasi-static descriptor into the weight half's datapath registers (their D,
# CE and R pins) and into the lane TLBuffer's A-queue pointers.  Safe because the seven source
# registers are written before the request toggle and held until the fill reports done: the lane
# cannot act on them until `req` has crossed two ASYNC_REG flops, which is at least two lane cycles
# after the last change.  THE CONTRACT THIS RESTS ON: software changes the outstanding-Get cap
# (l_cap) only between loads, never during one.
create_waiver -type CDC -id {CDC-1} -user iiswc-wlane \
  -from [get_pins -hier -filter {NAME =~ *eng/e/d_base_reg*/C || NAME =~ *eng/e/d_rblk_reg*/C || NAME =~ *eng/e/d_rows_reg*/C || NAME =~ *eng/e/d_stride_reg*/C || NAME =~ *eng/e/lw_fbuf_reg*/C || NAME =~ *eng/e/lw_lgpw_reg*/C || NAME =~ *eng/e/l_cap_reg*/C}] \
  -to   [get_pins -hier -filter {NAME =~ *domain/wh/e/*/D || NAME =~ *domain/wh/e/*/CE || NAME =~ *domain/wh/e/*/R || NAME =~ *domain/buffer/*/D || NAME =~ *domain/buffer/*/CE}] \
  -description {mbxr_wx quasi-static descriptor: written before the request toggle, held until done, sampled >= 2 lane cycles later; bounded at 10 ns by the max delay above}
create_waiver -type CDC -id {CDC-15} -user iiswc-wlane \
  -from [get_pins -hier -filter {NAME =~ *eng/e/d_base_reg*/C || NAME =~ *eng/e/d_rblk_reg*/C || NAME =~ *eng/e/d_rows_reg*/C || NAME =~ *eng/e/d_stride_reg*/C || NAME =~ *eng/e/lw_fbuf_reg*/C || NAME =~ *eng/e/lw_lgpw_reg*/C || NAME =~ *eng/e/l_cap_reg*/C}] \
  -to   [get_pins -hier -filter {NAME =~ *domain/wh/e/*/D || NAME =~ *domain/wh/e/*/CE || NAME =~ *domain/wh/e/*/R || NAME =~ *domain/buffer/*/D || NAME =~ *domain/buffer/*/CE}] \
  -description {the same descriptor, reported again as a clock-enable controlled structure; same handshake, same bound}
# CDC-13: the same quasi-static fields into non-flop primitives -- the weight banks' write address
# and write enable (the banks are written on FCLK1 and read on FCLK0, which is P2's assumption) and
# the lane A-queue's distributed RAM write enable.  Same handshake, same reasoning.
create_waiver -type CDC -id {CDC-13} -user iiswc-wlane \
  -from [get_pins -hier -filter {NAME =~ *eng/e/lw_fbuf_reg*/C || NAME =~ *eng/e/lw_lgpw_reg*/C || NAME =~ *eng/e/l_cap_reg*/C}] \
  -to   [get_pins -hier -filter {NAME =~ *eng/e/u_sp/port*bank*ww.mem_reg/ADDRBWRADDR* || NAME =~ *eng/e/u_sp/port*bank*ww.mem_reg/WEBWE* || NAME =~ *domain/buffer/*/ram_ext/*/WE}] \
  -description {quasi-static page geometry into the weight banks' write port and the lane queue RAM; stable across the whole fill}
# CDC-10: the lane's registered status crossing into two-flop ASYNC_REG pairs with logic in front of
# the first flop.  The logic is the Gray encode itself -- mbxr_wx.v:183 computes
# `x_beats_gray = cnt ^ (cnt >> 1)` combinationally at the source -- and the three inflight bits are
# decoded from the DMA's busy state the same way.  Both are STATISTICS, not control: the engine's
# accumulator telescopes (`total += bin - last`), so a sampled transient cancels on the next sample,
# and every control signal in this interface is a single-bit toggle (CDC-3 above).
create_waiver -type CDC -id {CDC-10} -user iiswc-wlane \
  -from [get_pins -hier -filter {NAME =~ *domain/wh/e/u_wx/cnt_reg*/C || NAME =~ *domain/wh/e/u_dma/s_busy_reg*/C}] \
  -to   [get_pins -hier -filter {NAME =~ *eng/e/u_wx/a.g_s1_reg*/D || NAME =~ *eng/e/u_wx/a.inf_s1_reg*/D}] \
  -description {Gray encode and inflight decode in front of an ASYNC_REG pair; both are statistics and the engine's accumulator telescopes, control is toggles only}
# CDC-8: Chipyard's own reset catcher for the lane clock group -- the third flop of
# ResetCatchAndSync's chain carries no ASYNC_REG property in the generated Verilog.  This is
# generated code, so it is RECORDED here rather than patched in the generator: the chain is three
# flops deep on the lane clock, asserted asynchronously and released synchronously, and the lane's
# own reset hold (WLaneResetHold, MEMORY_BANDWIDTH.md 9.9) extends that release until the AXI pins
# are quiet, so a one-cycle difference in the release is harmless by construction.
create_waiver -type CDC -id {CDC-8} -user iiswc-wlane \
  -from [get_pins -hier -filter {NAME =~ u_ctrl/soc_resetn_reg/C}] \
  -to   [get_pins -hier -filter {NAME =~ *wlane_reset_catcher/io_sync_reset_chain/output_chain/sync_*_reg/CLR}] \
  -description {Chipyard ResetCatchAndSync for the lane clock group: third flop without ASYNC_REG in generated code; release is further gated by WLaneResetHold}

# ---- What must NOT be constrained away --------------------------------------------------------
#
# roccmoon_wquiet (the AR/RLAST balance counter at the lane's AXI4 pins) and resetHold/hold (the
# flop that keeps the lane in reset until that counter says quiet) are RESET-FREE BY DESIGN: they
# must survive a SoC reset with bursts outstanding.  Their clock is FCLK1 and their fanin is FCLK1,
# so they need no constraint here; what they must not get is a reset.  tcl/build_rocket.tcl checks
# that in the synthesised netlist (WLANE_RESET_FREE): FDRE or FDSE, no asynchronous set or reset,
# nothing driving an FDRE's R or an FDSE's S except on the hold flop itself, and INIT equal to the
# value the RTL declares -- 1'b1 for mbxr_wquiet's `quiet` (mbxr_wx.v:214), 1'b0 for its counters
# and for the hold.
#
# ---- What report_cdc must say -----------------------------------------------------------------
#
# ZERO unsafe and ZERO unknown endpoints, with the waived ones listed by ID in the waiver table:
# every crossing is either a two-flop ASYNC_REG pair or one of the four structures waived above.
# tcl/build_rocket.tcl fails the build on anything else (WLANE_CDC) -- a new unsafe row means a new
# crossing appeared, and it is a failure, not a waiver.
