# SPDX-License-Identifier: Apache-2.0
#
# The memory domain's clock, for every variant with has_memclk (`bwfast`, `bwbypass`).
#
# A SEPARATE FILE, not a guarded block inside pynqz2_rocket.xdc, for the same reason
# pynqz2_mic.xdc and pynqz2_rgb.xdc are separate: Vivado parses everything in constrs_1
# as XDC, which has no `if`, and answers one with a CRITICAL WARNING and then runs
# neither branch.
#
# NO create_clock HERE.  FCLK0 and FCLK1 are generated by the PS7 IP, which constrains
# them itself; adding our own would double-constrain them.  What the tool cannot know is
# the RELATIONSHIP between them.
#
# WHY -asynchronous AND NOT -logically_exclusive.  Both clocks come from the same 1000 MHz
# IO PLL, so they are not strictly asynchronous in the physical sense -- they are
# 1000/29 and 1000/10, which have a common period of 2.9 us.  Vivado would happily try to
# meet setup across that, and the resulting requirement is a fraction of a nanosecond that
# no path can meet.  The design does not need it met: every crossing between the two
# domains is a TileLink AsynchronousCrossing (PynqZ2Configs.scala's
# WithSbusToMbusCrossingType), which is a Gray-coded AsyncQueue with three-deep
# synchronisers on each side, and the one hand-written crossing -- soc_resetn into
# mem_resetn in pynqz2_rocket_top.v -- is a two-flop synchroniser marked ASYNC_REG.
#
# So: declare them unrelated, and let the CDC structures do their job.  `report_cdc` is
# the thing to read after a build; an unsynchronised crossing shows up there as a CDC-1
# critical warning rather than as a timing failure, which is exactly the hazard this
# constraint creates and the reason to look.
set_clock_groups -asynchronous \
  -group [get_clocks -include_generated_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ *PS7_i/FCLKCLK[0]}]] \
  -group [get_clocks -include_generated_clocks -of_objects [get_pins -hierarchical -filter {NAME =~ *PS7_i/FCLKCLK[1]}]]

# ---- report_cdc waivers: rocket-chip's reset structures across FCLK0/FCLK1, reviewed ----
#
# The build gates on report_cdc (build_*_z1.sh [3/3]).  Tested against the routed bwbypass
# checkpoint c0bf3870: 5 unsafe endpoints -> 1, the one left being saw_mem's OR, which is
# fixed in RTL rather than waived.  Two patterns in Chipyard's generated
# reset logic are reported Critical on every memory-clock build and are correct by design.
# They are waived HERE, by ID and by exact pin pattern, so the gate keeps catching everything
# else -- in particular any DATA path that crosses without a synchroniser.
#
# CDC-10 on an AsyncQueue valid synchroniser's clear.  rocket-chip's AsyncValidSync clears
# its sink_valid/source_valid chain from the local reset OR the other side's synchronised
# reset (AsyncQueue.scala), so there is logic in front of the clear.  Assertion is
# asynchronous by intent; deassertion is re-synchronised by the chain itself.
create_waiver -type CDC -id {CDC-10} -user iiswc-bwlab \
  -from [get_pins -quiet -hier -filter {NAME =~ *reset_catcher/io_sync_reset_chain/output_chain/sync_*_reg/C}] \
  -to   [get_pins -quiet -hier -filter {NAME =~ */io_out_*_valid_*/output_chain/sync_*_reg/CLR}] \
  -description {rocket-chip AsyncValidSync: clear = local reset OR the other domain's synchronised reset; by design}
# The same endpoints also report CDC-11 (the reset catcher's output flop fans out to both
# valid synchronisers of a queue in the other domain).  Same structure, same reasoning.
create_waiver -type CDC -id {CDC-11} -user iiswc-bwlab \
  -from [get_pins -quiet -hier -filter {NAME =~ *reset_catcher/io_sync_reset_chain/output_chain/sync_*_reg/C}] \
  -to   [get_pins -quiet -hier -filter {NAME =~ */io_out_*_valid_*/output_chain/sync_*_reg/CLR}] \
  -description {rocket-chip AsyncValidSync: one synchronised reset into both valid synchronisers of a queue; by design}
# CDC-11: one reset flop (soc_ctrl_regs' soc_resetn) fans out to two synchronisers in the
# memory domain -- the top level's memrst_sync (the AXI shims) and Chipyard's mem reset
# catcher (the mbus).  Their releases can differ by a cycle; neither side issues AXI traffic
# for many cycles after reset, so the skew is harmless.
create_waiver -type CDC -id {CDC-11} -user iiswc-bwlab \
  -from [get_pins -quiet -hier -filter {NAME =~ u_ctrl/soc_resetn_reg/C}] \
  -to   [get_pins -quiet -hier -filter {NAME =~ memrst_sync_reg*/CLR || NAME =~ *mem_reset_catcher/io_sync_reset_chain/output_chain/sync_*_reg/CLR}] \
  -description {one reset flop into two memory-domain reset synchronisers; one-cycle release skew is harmless}
