#!/usr/bin/env python3
"""Generate `notebooks/iiswc_tutorial.ipynb` from the published attendee page.

The page -- `/scratch/dima/iiswc-site/src/data/instructions.ts` -- is the source of
truth for what the units are, what they run, and what the screen should say. This
script is the transcription of it, so a page change is a data edit here and not a
hand-edit of notebook JSON. **Edit this file, re-run it, commit both.**

    python3 notebooks/tools/build_notebook.py

Fidelity rules kept here on purpose:
  * every command, every expected-output block and every fix is the page's text;
  * nothing is invented where the page says a unit has no attendee sequence;
  * a step's `where` decides which helper runs it -- `lab.sh` on the instance,
    `lab.board` on the card, and nothing at all where the page says the step
    happens at the glass or on a laptop.

Where this is not a transcription
---------------------------------
The page describes the flow in which the attendee joins `iiswc-robotics-tutorial`, holds
a shared SSH key and reaches AWS through their card. The interface moved
(TUTORIAL_INTERFACE_NOTES.md 4e, TUTORIAL_AUTH_TLS.md): the attendee opens JupyterLab on
their own instance and the board connects to that instance. Steps 0.2 and 1.3 are
therefore written for the flow that exists rather than transcribed from the page, and the
page's own "find your instance" step has no counterpart here at all.

The notebook does not narrate that difference: an attendee needs the flow in front of
them, not its history. The page is a separate repository and is edited separately.

Prose style, and the reason this file is the place to fix prose: ordinary sentences, the
command, and what the screen should say. Explain the technical content -- the two harts
and their extensions, what the trace encoder records, what the solver optimises -- and
not how the tutorial's own plumbing is arranged.
"""
import json
from pathlib import Path

NB = Path(__file__).resolve().parents[1] / "iiswc_tutorial.ipynb"

cells: list[dict] = []


def _lines(text: str) -> list[str]:
    """nbformat wants every line but the last to KEEP its newline.

    Splitting on "\\n" and dropping it collapses the whole cell onto one line, which
    looks right in the JSON and is a SyntaxError in the kernel. Caught by executing the
    notebook; it is not visible by reading it.
    """
    parts = text.rstrip("\n").split("\n")
    return [p + "\n" for p in parts[:-1]] + parts[-1:]


def _cell_id() -> str:
    return f"c{len(cells):03d}"


def md(text: str) -> None:
    cells.append({"cell_type": "markdown", "id": _cell_id(), "metadata": {},
                  "source": _lines(text)})


def code(text: str) -> None:
    cells.append({"cell_type": "code", "id": _cell_id(), "execution_count": None,
                  "metadata": {}, "outputs": [], "source": _lines(text)})


def fence(text: str, lang: str = "") -> str:
    return f"```{lang}\n{text}\n```"


def fixes_table(fixes) -> str:
    rows = "\n".join(f"| {s} | {a} |" for s, a in fixes)
    return "**If instead you see**\n\n| | do |\n|---|---|\n" + rows


# ======================================================================================
# Front matter -- instructions.ts `instructions`
# ======================================================================================
md("""# IISWC 2026 · Robotics stack tutorial

Your PYNQ board implements a RISC-V system-on-chip (SoC) in its FPGA. The SoC has two
cores with different instruction extensions. In this tutorial, you will build
applications for it and examine their performance.

This notebook runs on your AWS instance. The instance builds the applications, and
the board runs them. Some exercises use recorded measurements supplied with the notebook.

### Tutorial overview

Complete Unit 0 to check your setup, then work through these five units with your
instructor.

| Unit | What you will do |
|---|---|
| 1. Zephyr and Chipyard | Build a Zephyr application, run it on the board, and capture a camera frame. |
| 2. ModelBlaster | Compile a model, inspect its kernels, and compare scalar and accelerated execution. |
| 3. TACIT | Capture execution on both cores and inspect a recorded timeline. |
| 4. Kernel optimization | Check the correctness and speed of a kernel generated by a language model. |
| 5. XPU-RT | Compare schedules for two models that share the board's cores and memory. |

### Running the exercises

| Helper | Runs on |
|---|---|
| `lab.sh("...")` | this instance |
| `lab.board("verb")` | your board |

`lab.board()` accepts a fixed set of operations. Run `lab.board("help")` to list them.

<details>
<summary>Where the example outputs came from</summary>

The original page records command output from `pynq-2` on 2026-09-23. This notebook
includes board output from a rerun on `pynq-13` on 2026-09-24.

</details>""")

md("""### Find your seat

Read the IP address on your board's OLED display. If it shows `10.42.0.13`, your seat
number is 13. The table below uses `N` for your seat number.

| Device | Address or name |
|---|---|
| Your board | `10.42.0.{N}` |
| Its hostname | `pynq-{N}` |
| Your instance | `aws-{N}.iiswc` |

Enter your seat number in `SEAT` below, then run the two cells. The first identifies
your AWS instance. The second checks whether your board is connected.""")

code('''import sys, pathlib
sys.path.insert(0, str(pathlib.Path.cwd()))
import iiswc_lab as lab

SEAT = "N"          # <-- put your seat number here, from the OLED

lab.where_am_i()''')

code("lab.board_status()")

# ======================================================================================
# Unit 0
# ======================================================================================
md("""---

## Unit 0 · Check your board and its connection

Use the board's display to check that the SoC is running. Then check whether the board
is connected to your AWS instance.""")

md("""### 0.1 Check the board's display

The OLED should show the board's IP address, network name, and uptime:

""" + fence("10.42.0.{N}\niiswc-robotics-tutorial\nup 4:17") + """

Watch the `up M:SS` line for a few seconds. It counts minutes and seconds since the
SoC's last boot and should keep advancing.

""" + fixes_table([
    ("`up M:SS` stops advancing", "Turn the board off and on again. The counter should restart at `up 0:00`."),
    ("The display shows `NO ADDRESS` or `wlan0 DOWN`.", "Turn the board off and on again, then wait for an IP address to appear."),
    ("The display is blank and the board started less than two minutes ago.", "Wait for the display to update. Network startup takes about 37 seconds."),
]))

md("""### 0.2 Check the board's connection

Your board connects to your AWS instance automatically. Run the next cell to check
the connection. You can repeat this check if the board stops responding.""")
code("lab.board_status()")
md("""The check takes about three seconds. Look for `board connected` in the result. The
examples below show a successful connection and two offline states:

""" + fence(
    "board connected -- pynq-13, 10.42.0.13, PL operating, MAGIC -\n"
    "board offline (nothing is listening) -- ConnectionRefusedError ...\n"
    "board offline (tunnel is stale) -- the port is bound but nothing answered within 3s") + """

""" + fixes_table([
    ("`board offline (nothing is listening)`", "The board has not connected yet. Check the OLED as described in 0.1. If the uptime counter has stopped, turn the board off and on again."),
    ("`board offline (tunnel is stale)`", "The board retries the connection automatically. Wait, then run the cell again."),
    ("The board stays offline after a restart.", "Ask an instructor for help. You can continue with exercises that run entirely on the instance."),
]))

# Unit 1
# ======================================================================================
md("""---

## Unit 1 · Zephyr and Chipyard: build and run an application

You will build a Zephyr application for the Rocket SoC, run it on your board, and
capture a camera frame. You will also inspect how Zephyr describes the hardware and
selects drivers.

Your AWS instance provides the build tools. Keep the board connected to the instance
while you upload and run the applications.""")

md("""### 1.1 Run build commands from the notebook

The cells below use `lab.sh` to run shell commands on your AWS instance. If your browser
disconnects, reopen the notebook to continue. The commands run on the instance and can
continue while the browser is disconnected.""")

md("""### 1.2 Build a Zephyr image for the Rocket SoC

Build `samples/boot_info`, the application currently running on your board. It reports
the board's status and network connection. The recorded build took about thirteen
seconds.""")
code('''lab.sh("""cd /home/ubuntu/tut && source /home/ubuntu/tut/env.sh && \\
west build -p always -b chipyard_pynqz1_all_f40 \\
    -d ~/out/boot_info samples/boot_info \\
    -- -DBOARD_ROOT=/home/ubuntu/tut""", timeout=900)''')
md("The build ends with a summary of memory use:\n\n" + fence(
    "-- west build: building application\n...\n"
    "Memory region         Used Size  Region Size  %age Used\n"
    "             RAM:       69720 B       256 MB      0.03%"))
code('lab.sh("ls -l ~/out/boot_info/zephyr/zephyr.bin")')
md("Check that the file listing includes `zephyr.bin`. This build produced a 56,888-byte image:\n\n" + fence("-rw-rw-r-- 1 ubuntu ubuntu 56888 ... zephyr.bin"))

md("""### 1.3 Upload the image to the PYNQ board and run it

Upload the image you just built. You will then load the SoC's FPGA configuration,
start the application, and read its console output.""")
code('lab.board_put("/home/ubuntu/out/boot_info/zephyr/zephyr.bin")')
md("""Check that the response reports `ok: true` and that `bytes` matches the file size
from 1.2. The board computes the `md5` checksum of the uploaded image:

""" + fence("""{
  "ok": true,
  "stored": "zephyr.bin",
  "bytes": 56888,
  "md5": "c830b4b6a0d1e4f7c2b9358e6a1d70cf"
}""", "json") + """

Run the next cell to load the FPGA configuration and start the application. This takes
about 40 seconds.""")
code('lab.board("run", "zephyr", timeout=300)')
md("""The board reports the application it ran and the number of console bytes it saved:

""" + fence("""{
  "ok": true,
  "ran": "zephyr",
  "console_bytes": 373,
  "results": ["console.out", "run.log"]
}""", "json") + """

The board saves the console output in `console.out`. Fetch it with the next cell.""")
code('''c = lab.board("get", "console.out", binary=True, verbose=False)
print(c.stdout.decode("utf-8", "replace") if c.ok else c)''')
md("""Card 13 produced this 373-byte console output on 2026-09-24:

""" + fence(
    "*** Booting Zephyr OS build 4329bf61c4fe ***\n"
    "BI_BOOT addr=0x8f000000\n"
    "BI_RAW magic=0x42533031\n"
    "BI_OLED probe addr=0x3c addr_ack_rc=0 nop_rc=0 init_rc=0 setup_rc=0\n"
    "BI_OLED state=READY addr=0x3c\n"
    "BI_STATUS state=PRESENT nonce=0xa1873611 soc_magic=0x5A5A0038\n"
    "BI_NET host=pynq-13 iface=wlan0 ipv4=10.42.0.13 ssid=iiswc-robotics-tutorial "
    "link_up=1 signal_dbm=-31\n"
    "BI_DONE") + """

Check for `soc_magic=0x5A5A0038` and `BI_DONE`. The magic value identifies the FPGA
configuration used in this unit. Your `nonce` will differ, and the OLED's uptime
counter should restart at `up 0:00`.

""" + fixes_table([
    ("`console_bytes: 0`", "Stop and tell an instructor. Do not retry and do not reboot."),
    ("`another console reader is already on /dev/ttyPS1`", "Stop the process with the exact PID shown in the message."),
    ("The output contains the boot banner but no `BI_` lines.", "The reader started late. Read the full text in `console.out` on the board."),
]) + """

This sequence has been tested twice on a bench board. Boards prepared through the
imaging flow still need verification, so an empty console may reflect a board setup
issue.""")

md("""### 1.4 Take a picture with the board's camera

The board's shield carries an image sensor. The application starts a hardware capture
unit, which writes a frame into the board's DRAM. When the capture finishes, the
application reports the frame's address and size.

Build the camera application with the next cell. Allow about twenty seconds.""")
code('''lab.sh("""cd /home/ubuntu/tut && source /home/ubuntu/tut/env.sh && \\
west build -p always -b chipyard_pynqz1_all_f40 \\
    -d ~/out/cam_capture samples/cam_capture \\
    -- -DBOARD_ROOT=/home/ubuntu/tut -DCAM_MCLKDIV=2""", timeout=900)''')
md("The camera build reports its memory use:\n\n" + fence(
    "Memory region         Used Size  Region Size  %age Used\n"
    "             RAM:      594216 B       256 MB      0.22%\n"
    "        IDT_LIST:           0 B         4 KB      0.00%") + """

Upload the image and run it. The application measures the sensor's pixel clock for a
second, captures a frame, and reports the result.""")
code('''lab.board_put("/home/ubuntu/out/cam_capture/zephyr/zephyr.bin")
lab.board("run", "zephyr", timeout=300)''')
md("""The recorded run uploaded 52,720 bytes and returned about 7,700 console bytes after
roughly forty seconds. The next cell extracts the lines that describe the capture.""")
code('''c = lab.board("get", "console.out", binary=True, verbose=False)
console = c.stdout.decode("utf-8", "replace")
for line in console.splitlines():
    if line.startswith(("CAM_SHIELD", "CAM_SENSOR", "CAM_STREAM", "CAM_GEOM",
                        "CAM_FRAME ", "CAM_RESULT")):
        print(line)''')
md("""Card 3 reported the following capture. Your pixel values and frame sum will depend
on what the camera sees.

""" + fence(
    "CAM_SHIELD present=1\n"
    "CAM_SENSOR rc=0 model_id=0x01b0 ok=1\n"
    "CAM_STREAM mode_rc=0 mode_select=1 readback_rc=0 ms=1001 pclk=3336669 fvld=17 "
    "lvld=5197 pclk_hz=3333335 fps_x1000=16983 lines_per_frame=305 ...\n"
    "CAM_GEOM src=lastheight width=326 height=324 bytes=105624 lines_per_frame=305 ...\n"
    "CAM_FRAME ok=1 rc=0 addr=0x8000ce80 phys=0x1000ce80 width=326 height=324 "
    "bytes=105624 ... min=0 max=255 mean_x100=8696 sum=9185093 saweof=1\n"
    "CAM_RESULT shield=1 ok=1") + """

Check three fields in your output:

- `model_id=0x01b0` confirms that the sensor answered on the control bus.
- `saweof=1` confirms that the capture unit saw the sensor mark the end of the frame.
- `bytes=105624` gives the stored frame size: 324 rows of 326 bytes.

The application adds all the frame bytes and reports the total as `sum`. You will
compare it with the sum of the downloaded bytes in 1.5.

<details>
<summary>How to interpret the capture checks</summary>

The sensor uses separate connections for control and pixel data. It can answer a
control request while sending no pixels, so the model ID alone cannot confirm a capture.

The end-of-frame marker tells the capture unit when the sensor has finished the frame.
A capture that stops at a byte limit can have the same size while containing an
incomplete frame.

Each row contains 324 sensor pixels and two padding bytes. The stored frame therefore
occupies 326 x 324 = 105,624 bytes. The next section removes the padding before
displaying the image.

</details>""")

md("""### 1.5 Download and display the frame

The frame is stored in the board's DRAM. The `camera` operation reads it from the
address reported by the application, and `get` transfers the bytes to your instance.
The next cell saves them as `frame.raw` and compares their sum with the application's
reported sum.""")
code('''lab.board("camera")
f = lab.board("get", "frame.raw", binary=True, verbose=False)
raw = f.stdout
open("frame.raw", "wb").write(raw)

said = int([l for l in console.splitlines() if l.startswith("CAM_FRAME ")][0]
           .split("sum=")[1].split()[0])
print(f"{len(raw):,} bytes here, guest said sum={said:,}, these bytes sum to {sum(raw):,}")''')
md("""Check that the two sums agree. This recorded frame produced:

""" + fence("105,624 bytes here, guest said sum=9,185,093, these bytes sum to 9,185,093") + """

The next cell converts the raw frame into a colour image. It removes the two padding
bytes at the start of each row, combines each 2x2 pixel group, and rotates the image
180 degrees to account for the sensor's mounting. It then adjusts the colour balance
by scaling each channel.

<details>
<summary>How the sensor values become RGB pixels</summary>

Each sensor pixel contributes one byte through a colour filter. Blue samples occupy
even rows and even columns, red samples occupy odd rows and odd columns, and green
samples occupy the other two positions in each 2x2 group.

The code takes the red and blue samples and averages the two green samples to make
one RGB pixel. This produces a 162 x 162 image from the 324 x 324 sensor area. It then
scales each colour channel toward a mean of 110 and clips values at 255.

</details>""")
code('''import numpy as np, matplotlib.pyplot as plt

STRIDE, W, H = 326, 324, 324
m = np.frombuffer(raw, np.uint8).reshape(H, STRIDE)[:, 2:2 + W]   # drop the two pad bytes
B = m[0::2, 0::2].astype(np.uint16)
G = (m[0::2, 1::2].astype(np.uint16) + m[1::2, 0::2]) // 2
R = m[1::2, 1::2].astype(np.uint16)
rgb = np.rot90(np.dstack([R, G, B]).astype(np.uint8), 2)          # sensor mounted inverted

for ch in range(3):                                               # each channel to one mean
    v = rgb[:, :, ch].astype(np.uint32)
    mean = max(int(v.mean()), 1)
    rgb[:, :, ch] = np.minimum((v * 110 + mean // 2) // mean, 255)

plt.figure(figsize=(4, 4))
plt.imshow(rgb)
plt.axis("off")
plt.title(f"{rgb.shape[1]}x{rgb.shape[0]} from your card", fontsize=9)
plt.show()''')
md("""You should see a 162 x 162 colour image of the scene in front of the camera. Isolated
bright or coloured pixels may be the sensor's hot pixels.

The detector in Unit 2 uses the same colour-filter pattern, rotation, and channel
scaling to prepare 64 x 64 inputs. The deployment tools check that host and board
preprocessing produce identical bytes. The detector needs consistent preprocessing
during training and deployment.""")

md("""### 1.6 Inspect the hardware description and enabled drivers

Zephyr uses devicetree to describe the hardware and Kconfig to choose which software
components to include. Inspect both for the camera image you just built.

The board files in `boards/chipyard/pynqz1_all_f40` describe the I2C controller at
`0x1004_0000`, the capture unit at `0x1008_0000`, GPIO, six LEDs, and four buttons.
The generated `zephyr.dts` contains the hardware description used by this build.

Run the next cell to find the camera and button nodes in that file.""")
code('''lab.sh("""grep -A7 'ospi@10080000' ~/out/cam_capture/zephyr/zephyr.dts \\
  | sed 's,[[:space:]]*/[*].*[*]/,,' | grep -v '^$' && echo --- && \\
grep -A6 'buttons: buttons' ~/out/cam_capture/zephyr/zephyr.dts \\
  | sed 's,[[:space:]]*/[*].*[*]/,,' | grep -v '^$'""")''')
md("The command prints the camera node followed by the start of the button definitions:\n\n" + fence(
    "ospi0: ospi@10080000 {\n"
    '        compatible = "ucbbar,ospi-hm01b0";\n'
    "        reg = < 0x10080000 0x1000 >;\n"
    "        interrupt-parent = < &plic >;\n"
    "        interrupts = < 0xd 0x1 >;\n"
    "        frame-buffer-depth = < 0x200 >;\n"
    "        sensor-i2c = < &i2c0 >;\n"
    '        status = "okay";\n'
    "---\n"
    "buttons: buttons {\n"
    '        compatible = "gpio-keys";\n'
    "        debounce-interval-ms = < 0x1e >;\n"
    "        btn0: btn0 {\n"
    "                gpios = < &gpio0 0x6 0x0 >;") + """

The camera sample reads and polls the capture registers directly. This checkout has
no Zephyr driver for `compatible = "ucbbar,ospi-hm01b0"`. The node records the register
address in `reg`, the interrupt in `interrupts`, and the sensor's control bus in
`sensor-i2c`.

<details>
<summary>How the sensor and buttons use the hardware description</summary>

The sensor uses I2C address `0x24` on the controller it shares with the OLED at `0x3c`.
The sample accesses the sensor through that controller. The sensor's control port has
no separate node.

The board declares four buttons as `gpio-keys` with aliases `sw0` to `sw3`. An
application can use `GPIO_DT_SPEC_GET(DT_ALIAS(sw0), gpios)` to obtain BTN0's pin and
polarity from the devicetree. BTN0 uses pin 6. Kconfig controls whether the build
includes the `gpio-keys` input driver.

</details>

The next cell reads the generated `.config` file to show which I2C, GPIO, display,
and input options the camera image enabled.""")
code('''lab.sh("grep -E '^CONFIG_(I2C|I2C_SIFIVE|GPIO|GPIO_SIFIVE|DISPLAY|INPUT|SSD1306)=' "
       "~/out/cam_capture/zephyr/.config | sort")''')
md("The camera image enables these four options:\n\n" + fence(
    "CONFIG_GPIO_SIFIVE=y\nCONFIG_GPIO=y\nCONFIG_I2C_SIFIVE=y\nCONFIG_I2C=y") + """

Compare these options with the hardware nodes above. The camera image enables I2C
and GPIO support. It leaves `CONFIG_DISPLAY` and `CONFIG_INPUT` disabled.

Why can the board describe an OLED while this image omits its driver?

<details>
<summary>How the board and application select drivers</summary>

The board's `_defconfig` enables shared components such as `CONFIG_I2C`, `CONFIG_GPIO`,
and the console. The SiFive drivers default to enabled when the devicetree contains
matching enabled nodes, which selects `CONFIG_I2C_SIFIVE` and `CONFIG_GPIO_SIFIVE`.

An application enables additional components in its `prj.conf`. The display sample
enables `CONFIG_DISPLAY` there. The camera sample leaves display and input support
disabled, so its image omits those drivers even though the board describes the devices.

</details>""")

md("""### 1.7 Configure an application for a different target

An application can use a devicetree overlay to add or change hardware nodes for its
build. The display sample's `oled.overlay` enables the I2C controller and adds a
display at `0x3d`. The board also declares a display at `0x3c`, since the panel is
sold at either address.

The example command builds the display application with that overlay:

""" + fence(
    "west build -b chipyard_pynqz1_all_f40 samples/oled_status \\\n"
    "    -- -DBOARD_ROOT=$IISWC_ROOT \\\n"
    "       -DEXTRA_DTC_OVERLAY_FILE=$IISWC_ROOT/samples/oled_status/oled.overlay") + """

The build merges the overlay with the board definition. `EXTRA_DTC_OVERLAY_FILE` adds
to the automatically discovered overlays. `DTC_OVERLAY_FILE` overrides the automatic
overlay selection.

Zephyr also finds application overlays at `<app>/boards/<board>.overlay` and Kconfig
fragments at `<app>/boards/<board>.conf`.

#### Select a trace sink for Spike

The tracing sample's `boards/spike_riscv64.conf` configures the application for the
Spike simulator. This setting disables the trace sink that writes to DRAM:

""" + fence(
    "# Target 0, not 1: spike's sink is the file writer that emits tacit.out / tacit.log /\n"
    "# tacit.debug into the CWD. It needs no address, and there is no SiFive InclusiveCache\n"
    "# control node at 0x2010000 in the simulator -- the L2 flush the FPGA needs would take\n"
    "# a store access fault here.\n"
    "CONFIG_TACIT_MB_SINK_DMA=n") + """

Zephyr picks up this fragment for the Spike target, so the application can use the
same source with a different trace sink.

<details>
<summary>Why the cache flush depends on the target</summary>

On the board, the trace encoder writes into DRAM. The application flushes the L2 cache
so the ARM processor can read the updated memory. The camera application uses the same
flush before reporting the frame's address.

Spike writes the trace to a file and has no cache controller at `0x2010000`. Accessing
that address in the simulator causes a store access fault. The configuration fragment
selects the appropriate sink for Spike.

</details>""")

# ======================================================================================
# Unit 2
# ======================================================================================
md("""---

## Unit 2 · ModelBlaster: compile a PyTorch model for the SoC

ModelBlaster compiles a PyTorch model into C for the SoC. It converts the network into
an intermediate representation (IR), quantizes weights and activations to int8, and
selects kernels for the target hardware.

You will compile SignDetLite, a small traffic-sign detector, and follow a convolution
from the model to the SoC's `MBP.DOT8` instruction. Later sections compare scalar and
accelerated execution using recorded board measurements. The compilation exercises
run on your AWS instance.

This checkout supplies deterministic random weights (`signdet/random_weights.py`,
NumPy PCG64, seed 144). They allow you to run the compilation and arithmetic checks.
The resulting model has not learned to recognize signs.""")

md("""### 2.1 Generate the model graph and C code

Run `scripts/84_signdet_lower.sh` to generate SignDetLite's IR and C code. The script
runs `extract_graph`, `generate_skeleton`, and `generate_kernels`, then writes the
results under `out/signdet/`. Allow about five seconds.""")
code('''import json
repo = lab.repo_root()
r = lab.sh(f"cd {repo} && ./scripts/84_signdet_lower.sh", timeout=900, head=0, tail=14)
signdet = lab.Lowering.from_run(r)''')
md("""The summary lists the selected kernels and an estimated inference time:

""" + fence(
    "==> op coverage\n"
    "    conv2d_s8_pc       curated[pext]        pext_patch_dot8_pc\n"
    "    permute4_s8        curated[pext_nl]     pext_block\n"
    "    softmax_s8         curated[pext_nl]     pext_int_memo2\n"
    "    MAC 7532544   est 9.61 M cycles   est 240.2 ms @ 40 MHz  (1.2755 cycles per MAC, measured)\n"
    "    all ops curated, no reference-C fallback") + """

The `extract_graph` stage writes `ir/graph.json`. This file records tensor shapes,
quantization scales, and the order in which operators run. Use the next cell to
inspect the graph.""")
code('''lab.show_graph(signdet)''')
md("""Follow the tensor names from input `x` to output `softmax`:

""" + fence(
    "signdet_b144  int8  9 operators, 8 of them dispatched to a kernel\n"
    "input  x        [1, 3, 64, 64]\n"
    "output softmax  [64, 3]\n"
    "\n"
    "  conv1     conv2d_s8_pc          x -> relu      N=1 IC=3 IH=64 IW=64 OC=16 OH=32 OW=32 ...\n"
    "  conv2     conv2d_s8_pc       relu -> relu_1    N=1 IC=16 IH=32 IW=32 OC=32 OH=16 OW=16 ...\n"
    "  conv3     conv2d_s8_pc     relu_1 -> relu_2    N=1 IC=32 IH=16 IW=16 OC=32 OH=16 OW=16 ...\n"
    "  conv4     conv2d_s8_pc     relu_2 -> relu_3    N=1 IC=32 IH=16 IW=16 OC=64 OH=8 OW=8 ...\n"
    "  conv5     conv2d_s8_pc     relu_3 -> relu_4    N=1 IC=64 IH=8 IW=8 OC=64 OH=8 OW=8 ...\n"
    "  head      conv2d_s8_pc     relu_4 -> head      N=1 IC=64 IH=8 IW=8 OC=3 OH=8 OW=8 ...\n"
    "  permute   permute4_s8        head -> permute   d0=1 d1=3 d2=8 d3=8 p0=0 p1=2 p2=3 p3=1\n"
    "  reshape   view            permute -> reshape   n=192\n"
    "  softmax   softmax_s8      reshape -> softmax   M=64 K=3\n"
    "\n"
    "graph.json md5 70a0ac6d37a0bf99a6733f40e5e64073") + """

The graph contains nine operators and makes eight kernel calls. Which operator does
not need a kernel?

<details>
<summary>Why there are eight kernel calls</summary>

The `reshape` operator is a `view`. It changes how the existing data is interpreted
without moving the bytes, so ModelBlaster does not generate a kernel for it.

ModelBlaster also folds the ReLU operations into the convolutions' activation clamps.
This explains why `conv1` produces a tensor named `relu` even though the graph has no
separate ReLU operator.

</details>

Six operators have type `conv2d_s8_pc`, an int8 convolution with per-channel
quantization. You will inspect their kernel in 2.2.""")

md("""### 2.2 Inspect the selected convolution kernel

A kernel implements an operator for the target hardware. The `generate_kernels`
stage matches IR operators with available kernels and records its choices in
`kernel_picks.json`. Run the next cell to see where each kernel comes from, which
algorithm it uses, and which C file will be compiled.""")
code('''lab.show_kernel_choices(signdet)''')
md("""Find `conv2d_s8_pc` and the kernel named `pext_patch_dot8_pc`:

""" + fence(
    "conv2d_s8_pc   curated[pext]      pext_patch_dot8_pc\n"
    "               serves 6 of the 9 operators\n"
    "               .../out/signdet/kernels_board/pext/pext_conv2d_s8_pc_pext_patch_dot8_pc.c\n"
    "permute4_s8    curated[pext_nl]   pext_block\n"
    "               serves 1 of the 9 operators\n"
    "               .../out/signdet/kernels_board/pext_nl/pext_nl_permute4_s8_pext_block.c\n"
    "softmax_s8     curated[pext_nl]   pext_int_memo2\n"
    "               serves 1 of the 9 operators\n"
    "               .../out/signdet/kernels_board/pext_nl/pext_nl_softmax_s8_pext_int_memo2.c\n"
    "\n"
    "conv2d_s8_pc carries 7,532,544 multiply-accumulates -- every one in the graph.") + """

ModelBlaster maps PyTorch's `torch.nn.Conv2d` to `conv2d_s8_pc` in the IR. The `_pc`
suffix indicates per-channel quantization. For this target, it selected
`pext_patch_dot8_pc` for all six convolutions.

The kernel gathers the input values needed for an output pixel into a contiguous
vector and arranges the weights to match. It uses `MBP.DOT8` to multiply and sum eight
pairs of int8 values at a time.

The next cell shows the loop that accumulates four output channels at once.""")
code('''lab.show_source(signdet.picks["conv2d_s8_pc"]["path"],
                around="for (b = 0; b < quads", lines=17)''')
md("""Follow `x` through the four calls to `mb_pext_dot8`:

""" + fence(
    "281      for (b = 0; b < quads; b++) {\n"
    "282          const int8_t *w = wp + (size_t)b * G * 32;\n"
    "283          const int8_t *pp = p;\n"
    "284          int64_t a0 = bias ? bias[i + 0] : 0;\n"
    "285          int64_t a1 = bias ? bias[i + 1] : 0;\n"
    "286          int64_t a2 = bias ? bias[i + 2] : 0;\n"
    "287          int64_t a3 = bias ? bias[i + 3] : 0;\n"
    "288  \n"
    "289          for (g = 0; g < G; g++) {\n"
    "290              const int64_t x = MB_PEXT_LD8(pp);\n"
    "291              a0 += mb_pext_dot8(x, MB_PEXT_LD8(w));\n"
    "292              a1 += mb_pext_dot8(x, MB_PEXT_LD8(w + 8));\n"
    "293              a2 += mb_pext_dot8(x, MB_PEXT_LD8(w + 16));\n"
    "294              a3 += mb_pext_dot8(x, MB_PEXT_LD8(w + 24));\n"
    "295              pp += 8;\n"
    "296              w += 32;\n"
    "297          }", "c") + """

`MB_PEXT_LD8(pp)` loads eight input bytes into `x`. Each call to `mb_pext_dot8`
combines those inputs with a different set of weights and adds the result to one of
the accumulators, `a0` through `a3`.

With `MB_PEXT_HW` enabled, `mb_pext_dot8` emits one `MBP.DOT8` instruction. The next
cell shows its definition in `pext.h`.""")
code('''lab.show_source(lab.repo_file("fpga/pynq-z2/sw/pext.h"),
                around="mb_pext_dot8(", before=2, lines=8)''')
md("""The helper uses the assembler's `.insn` directive to encode `MBP.DOT8`:

""" + fence(
    "173  #if MB_PEXT_HW\n"
    "174\n"
    "175  static inline int64_t mb_pext_dot8(int64_t a, int64_t b)\n"
    "176  {\n"
    "177  \tint64_t r;\n"
    "178  \n"
    '179  \t__asm__(".insn r 0x0b, 0, 0, %0, %1, %2" : "=r"(r) : "r"(a), "r"(b));\n'
    "180  \treturn r;", "c") + """

Opcode `0x0b` belongs to RISC-V's `custom-0` space. The instruction takes two 64-bit
registers, each containing eight int8 values. It multiplies corresponding pairs and
returns the sum of the eight products.

<details>
<summary>Where to read the full implementations</summary>

The convolution kernel is in
`fpga/pynq-z2/modelblaster/kernels/pext/pext_conv2d_s8_pc_pext_patch_dot8_pc.c`.
The instruction helper is in `fpga/pynq-z2/sw/pext.h`.

</details>""")

md("""### 2.3 Compare quantization with 64 and 256 calibration frames

The convolution kernel in 2.2 accumulates products before converting its results to
int8. ModelBlaster uses one scale per activation tensor and one per output channel
for the weights.

Each convolution uses a multiplier and a shift to convert its accumulators to the
output scale. Inspect these parameters in `weights.c`, then repeat calibration with
more frames to see whether they change.""")
code('''lab.show_requant_arrays(signdet)''')
md("""The output lists the array locations and prints the two arrays for `conv1`:

""" + fence(
    "weights.c is 4,477 lines. 52 of them are the requantise grid: 12 arrays, 422 int32 values.\n"
    "\n"
    "  line    10  signdet_b144_conv1_output_multiplier_per_oc_roccmoon [16]\n"
    "  line    14  signdet_b144_conv1_output_shift_per_oc_roccmoon      [16]\n"
    "  line    53  signdet_b144_conv2_output_multiplier_per_oc_roccmoon [32]\n"
    "  ...\n"
    "  line  4460  signdet_b144_head_output_shift_per_oc_roccmoon       [3]\n"
    "\n"
    "const int32_t signdet_b144_conv1_output_multiplier_per_oc_roccmoon[16] = {\n"
    "    1591242990, 1736033205, 1084498289, 1308506831, ...\n"
    "};\n"
    "\n"
    "const int32_t signdet_b144_conv1_output_shift_per_oc_roccmoon[16] = {\n"
    "    8, 9, 8, 8, 9, 9, 8, 9, 9, 9, 8, 9, 8, 9, 9, 9,\n"
    "};") + """

Each output channel has one entry in each array. Its multiplier and shift encode the
scale ratio *M* = input scale × weight scale ÷ output scale. The next cell uses these
values to recover the weight scale for each channel.

<details>
<summary>How the kernel applies the scale</summary>

The kernel computes `(acc * multiplier + 2^30) >> 31 >> shift` using integer arithmetic.
This approximates multiplying the accumulator by *M*.

</details>""")
code('''lab.show_requant_channels(signdet)''')
md("""Compare the first two channels in the `implied weight scale` column:

""" + fence(
    "conv1   input scale 0.007874015748 (= 1/127)   output scale 0.014415336406\n"
    "\n"
    "  oc   multiplier  shift          M   implied weight scale   max |W| that fits\n"
    "   0   1591242990      8   0.00289445         0.00529902   0.672975\n"
    "   1   1736033205      9   0.00157891         0.00289059   0.367105\n"
    "   2   1084498289      8   0.00197269         0.00361150   0.458660\n"
    "   3   1308506831      8   0.00238016         0.00435747   0.553399\n"
    "\n"
    "  ... and 12 more channels. Every channel saturates at 127, which is what per-channel\n"
    "  means: the multiplier absorbs the range, not the weights.") + """

Channel 0's scale covers weight magnitudes up to about 0.673, and channel 1's covers
up to about 0.367. The separate scales let both channels use the available int8 range.

#### Recalibrate with more frames

ModelBlaster runs calibration frames through the float model to estimate activation ranges.
The earlier build used 64 frames. Run the next cell to lower the same checkpoint with
256 frames and compare the generated arrays.

Predict which values will change when you use more calibration frames: the quantized
weights, the multipliers, or the shifts.""")
code('''r256 = lab.sh(f"cd {repo} && ./scripts/84_signdet_lower.sh --name signdet_cal256 --ncal 256",
              timeout=900, quiet=True)
lab.compare_calibration(signdet, lab.Lowering.from_run(r256))''')
md("""Read the `differ` column to see how many entries changed in each array:

""" + fence(
    "graph.json md5   64 frames 70a0ac6d37a0bf99a6733f40e5e64073\n"
    "                256 frames 5e3ac0705fe5ef1beb7a35afc2b15138\n"
    "\n"
    "array                               entries   differ\n"
    "conv1.output_multiplier_per_oc           16       16\n"
    "conv1.output_shift_per_oc                16        3\n"
    "conv2.output_multiplier_per_oc           32       32\n"
    "conv2.output_shift_per_oc                32        1\n"
    "conv3.output_multiplier_per_oc           32       32\n"
    "conv3.output_shift_per_oc                32        0\n"
    "conv4.output_multiplier_per_oc           64       64\n"
    "conv4.output_shift_per_oc                64       20\n"
    "conv5.output_multiplier_per_oc           64       64\n"
    "conv5.output_shift_per_oc                64        4\n"
    "head.output_multiplier_per_oc             3        3\n"
    "head.output_shift_per_oc                  3        1\n"
    "\n"
    "weight_q arrays identical: True") + """

The final line confirms that the weights are identical. Every multiplier changes, while
only some shifts change. Compare these results with your prediction.

<details>
<summary>Why the scaling parameters change</summary>

ModelBlaster derives weight scales from the checkpoint's weights, which stayed the
same in this comparison. It estimates activation scales from the calibration frames.
Changing those frames can change the output rescaling even when the weights stay
fixed.

Record the calibration count with the generated model. The two runs above have
different `graph.json` hashes.

</details>""")

md("""### 2.4 Compile the model with scalar kernels

Compile the same model again with `--scalar`. This option selects ModelBlaster's
reference C kernels for every dispatched operator. The next cell compares the result
with the accelerated build. Allow about five seconds.""")
code('''rs = lab.sh(f"cd {repo} && ./scripts/84_signdet_lower.sh --name signdet_scalar --scalar",
            timeout=900, head=0, tail=8)
scalar = lab.Lowering.from_run(rs)
lab.compare_backends(signdet, scalar)''')
md("""Compare the selected kernels and the hashes of the generated files:

""" + fence(
    "conv2d_s8_pc   pext    curated[pext]      pext_patch_dot8_pc\n"
    "               scalar  reference          None\n"
    "permute4_s8    pext    curated[pext_nl]   pext_block\n"
    "               scalar  reference          None\n"
    "softmax_s8     pext    curated[pext_nl]   pext_int_memo2\n"
    "               scalar  reference          None\n"
    "\n"
    "ir/graph.json    same   70a0ac6d37a0bf99a6733f40e5e64073  70a0ac6d37a0bf99a6733f40e5e64073\n"
    "gen/weights.c    same   e706082b34c472af1e9ad072eb5b88b4  e706082b34c472af1e9ad072eb5b88b4\n"
    "gen/kernels.c    differs   19d585027f49cc808b2b0339e2dfaf24  3c9bcaf92dec52668773cfaf41045209\n"
    "\n"
    "kernels.c    1382 lines on pext,  119 on scalar") + """

The graph, weights, and quantization parameters are identical in this comparison.
The kernel implementations change. The next cell shows the scalar convolution's
inner loops.""")
code('''lab.show_source(scalar.gen / "kernels.c", around="acc +=", before=11, lines=16)''')
md("""Find the line that multiplies an input value by a weight and adds it to `acc`:

""" + fence(
    " 25                  for (int ow = 0; ow < OW; ow++) {\n"
    " 26                      int32_t acc = bias ? bias[oc] : 0;\n"
    " 27                      for (int ic = 0; ic < IC; ic++) {\n"
    " 28                          for (int kh = 0; kh < KH; kh++) {\n"
    " 29                              int ih = oh * SH - PH + kh;\n"
    " 30                              if (ih < 0 || ih >= IH) continue;\n"
    " 31                              for (int kw = 0; kw < KW; kw++) {\n"
    " 32                                  int iw = ow * SW - PW + kw;\n"
    " 33                                  if (iw < 0 || iw >= IW) continue;\n"
    " 34                                  int32_t iv = "
    "(int32_t)input[((n*IC + ic)*IH + ih)*IW + iw] + input_offset;\n"
    " 35                                  int32_t wv = "
    "(int32_t)weight[((oc*IC + ic)*KH + kh)*KW + kw] + filter_offset;\n"
    " 36                                  acc += iv * wv;\n"
    " 37                              }\n"
    " 38                          }\n"
    " 39                      }\n"
    " 40                      int64_t prod = ((int64_t)acc * (int64_t)mult + (1LL << 30)) >> 31;",
    "c") + """

The scalar loop performs one multiply-accumulate with `acc += iv * wv`. The accelerated
kernel uses `mb_pext_dot8` to accumulate eight products per call. Both apply the same
output rescaling after accumulation.

<details>
<summary>Where to compare the source files</summary>

The generated scalar kernel is in `out/signdet_scalar/gen/kernels.c`.
The accelerated kernel is in
`fpga/pynq-z2/modelblaster/kernels/pext/pext_conv2d_s8_pc_pext_patch_dot8_pc.c`.

</details>""")

md("""### 2.5 Compare recorded board runs

The next cells read recorded results from `assets/signdet_board_cycles.json`. The
scalar and accelerated images used the same graph, trained checkpoint, and input
frame. The earlier compilation exercises use the random weights in the public checkout.

Both images were built with `scripts/86_signdet_board.sh` and run on a PYNQ-Z1 with
bitstream `0x5A5A0038` at 40 MHz. The test harness records a cycle count for each
operator dispatch and compares all 192 output bytes against a reference computed on
the host.

The harness also deliberately executes `MBP.DOT8` on hart 1, which does not support
the instruction. This test expects an illegal-instruction trap. Run the next cell
to inspect the accelerated run.""")
code('''board = json.load(open("assets/signdet_board_cycles.json"))
lab.show_board_provenance(board)''')
md("""Look for `max_abs_err=0` and the expected illegal-instruction trap in the console:

""" + fence(
    "MB_PEXT_BUILD model=signdet_b144 quant=int8 ops=8 iters=11 hw=1\n"
    "MB_PEXT_RUN cpu=0 mhartid=0 median=9508851 min=9504987 max=9514870 warm=9519734 "
    "mtime=9505 max_abs_err=0\n"
    "MB_PEXT_OP id=0 name=conv1 op=conv2d_s8_pc shape=N=1;IC=3;IH=64;... cycles=998077\n"
    "MB_PEXT_OP id=1 name=conv2 op=conv2d_s8_pc shape=N=1;IC=16;IH=32;... cycles=1197067\n"
    "...\n"
    "MB_PEXT_OP id=7 name=softmax op=softmax_s8 shape=M=64;K=3 cycles=51859\n"
    "   hart 0 (big): median 237.721 ms   max_abs_err=0\n"
    "MB_PEXT_NEG starting -- one MBP.DOT8 pinned to CPU 1; an illegal-instruction trap "
    "here is the PASS\n"
    "\n"
    " mcause: 2, Illegal instruction\n"
    "  mtval: d7070b\n"
    "...\n"
    "   hart 1 refused 0x00d7070b -- custom-0, funct3=0: MBP is on hart 0 only, as specified\n"
    "RESULT: PASS -- the MBP kernels ran bit-exact on hart 0 and the same instruction is "
    "illegal on hart 1") + """

`median` gives the cycle count for one inference, measured across eleven inferences
after a warm-up. The `MB_PEXT_OP` lines report operator cycle counts from the same run.
The next cell compares the two backends.""")
code('''lab.show_board_arms(board)''')
md("""Compare the `frame` totals, then check that both outputs match the reference:

""" + fence(
    "                           MBP kernels    reference C   factor\n"
    "conv1    conv2d_s8_pc          998,077     10,687,289   10.71x\n"
    "conv2    conv2d_s8_pc        1,197,067     26,614,336   22.23x\n"
    "conv3    conv2d_s8_pc        2,764,055     50,937,793   18.43x\n"
    "conv4    conv2d_s8_pc        1,322,570     25,645,999   19.39x\n"
    "conv5    conv2d_s8_pc        3,080,706     48,684,531   15.80x\n"
    "head     conv2d_s8_pc           86,788        454,883    5.24x\n"
    "permute  permute4_s8             2,117          9,697    4.58x\n"
    "softmax  softmax_s8             51,859        889,603   17.15x\n"
    "frame                        9,508,851    163,923,052   17.24x\n"
    "ms at 40 MHz                     237.72       4,098.08\n"
    "\n"
    "pext      custom-0 instructions in the image  49   output vs golden: 0 of 192 "
    "bytes differ, max |d| = 0\n"
    "scalar    custom-0 instructions in the image   1   output vs golden: 0 of 192 "
    "bytes differ, max |d| = 0") + """

The accelerated image completes inference 17.24 times faster in this measurement.
Both images match all 192 reference output bytes.

The scalar image contains one custom-0 instruction for the deliberate test on hart 1.
Its kernels use the reference C implementations.

The figure compares total inference time in the upper panel and each operator's share
of its backend's total in the lower panel.""")
code("lab.kernel_speedup_figure(board)")
md("""The five 3x3 convolutions account for 98.46% of the accelerated inference and 99.17%
of the scalar inference. They remain the largest part of runtime on both backends.

`conv1` accelerates by 10.71x, while `conv2` accelerates by 22.23x. As a result,
`conv1`'s share grows from 6.52% of the scalar inference to 10.50% of the accelerated
inference.

<details>
<summary>How layer shape affects the comparison</summary>

The first convolution has three input channels and a 3x3 filter, so each input patch
contains 27 values. The kernel pads the patch for `MBP.DOT8`, which processes eight
int8 values at a time. Later convolutions use 16, 32, or 64 input channels, which fit
into groups of eight. Padding and setup work can limit how much of the instruction's
throughput a kernel uses.

`head` and `permute` improve by 5.24x and 4.58x. Their accelerated cycle counts,
86,788 and 2,117, represent 0.91% and 0.02% of the total. For such small dispatches,
setup work can be a substantial share of execution.

</details>""")

md("""### 2.6 Compare detector and speech workloads

SignDetLite runs the same eight operator dispatches for each 64x64x3 image and
produces an 8x8x3 output grid. Its computation has a fixed shape.

Moonshine transcribes a four-second audio window in two stages. Its encoder produces
165 hidden states of 288 values each. Its decoder generates one token per step and
stops when it emits end-of-sequence. This build allows up to 24 steps.

In the matrix multiplications summarized below, the encoder processes 165 rows
together, and the decoder processes one row per token. This gives the encoder more
opportunities to reuse each weight load.

The next cell compares model sizes, operator counts, and the arithmetic performed
per byte of weight data using the supplied measurement record.""")
code('''lab.show_model_shapes()''')
md("Compare the dispatch counts and the decoder's arithmetic per byte of weight data:\n\n" + fence(
    "SignDetLite runs once per camera frame.\n"
    "  8 dispatches, 7,532,544 multiply-accumulates,\n"
    "  9,511,271 cycles = 238 ms at 40 MHz,\n"
    "  72,276 bytes of weights.\n"
    "\n"
    "Moonshine Tiny runs encoder once per four-second window, then the decoder once per "
    "output token.\n"
    "  encoder    117 dispatches, every matrix multiply 165 rows tall\n"
    "  prologue    12 dispatches, also 165 rows tall\n"
    "  decoder    176 dispatches per step, every matrix multiply 1 row tall\n"
    "            164 at the first step: there is no cache to append to yet\n"
    "\n"
    "  18,993,024 multiply-accumulates per token against 18,395,136 weight bytes\n"
    "  = 1.03 multiply-accumulates per byte of weight read.\n"
    "  The encoder does 165 rows of arithmetic on the same weights; the decoder does one.\n"
    "\n"
    "  Self-attention reads 1 key at the first step and 24 at the last.\n"
    "  The model stops when it emits end-of-sequence, on average after 11.25 of the 24 "
    "steps that are compiled in.\n"
    "\n"
    "  About 2,098 dispatches for one utterance, against 8 for one frame of the detector."))
md("""The decoder performs about 1.03 multiply-accumulates per byte of weight data read.
The encoder's larger matrices reuse weights across 165 rows. These shapes help explain
why memory traffic matters to the decoder's performance.

In Unit 5, you will schedule four SignDetLite inferences at one-second intervals
alongside a Moonshine job. The detector provides periodic work with a fixed graph.
The speech job's total work depends on the number of decoded tokens.

<details>
<summary>How later decoding steps add work</summary>

The decoder attends to the tokens it has already generated. The first step reads one
key, and the 24th reads 24. The lowering unrolls all 24 steps into code and extends
the key and value cache using concatenation. These operations add work to later steps.

The first step dispatches 164 operators. Later steps dispatch 176 because they also
append to the cache. In the recorded workload, the model stops after an average of
11.25 steps, for about 2,098 dispatches per utterance.

</details>

<details>
<summary>How a lookup table speeds up GELU</summary>

Moonshine's encoder evaluates the GELU activation 1,378,656 times per utterance. The
activation appears twice in the convolutional stem and once in each of the six
encoder layers.

With fixed per-tensor symmetric quantization scales, each possible input byte maps
to a fixed output byte. A 256-entry table can precompute this mapping from the
reference expression.

The recorded benchmarks report a 167.48x speedup over the float version for the GELU
pass in a transformer feed-forward block and a 153.09x speedup for a model dispatch.
The whole block improved by 4.72x. The table matched the reference output on every
checked row and uses ordinary instructions to look up each result.

</details>

<details>
<summary>How model weights affect image updates</summary>

The build carrying both models contains 1.0 MB of code and 62.8 MB of read-only data.
The image transferred to the board is 63.9 MB.

A recorded kernel update modified 15 KB of code and relocated 65.5 MB of weight
symbols without changing their contents. A binary delta that accounts for relocation
was 257 KB. The experiment reported 261 times less transferred data than resending
the full image.

</details>

<details>
<summary>Which weights the tutorial supplies</summary>

Moonshine uses a public checkpoint pinned to one revision. The download requires no
account or licence-acceptance step, and the tutorial checks each file against a
recorded SHA256 hash.

The trained SignDetLite checkpoint uses the German Traffic Sign Detection Benchmark.
The tutorial omits that checkpoint because its redistribution terms were unresolved
when the material was prepared. The public checkout uses the deterministic random
weights introduced at the start of this unit for the compilation exercises.

</details>""")

# ======================================================================================
# Unit 3
# ======================================================================================
md("""---

## Unit 3 · TACIT: trace execution on both cores

TACIT's hardware encoders record instruction execution in memory. A decoder converts
the trace into a timeline of function calls.

You will inspect a supplied trace, then capture execution on both cores of your board
and download the files. The tutorial identifies the SoC's two hardware threads as
hart 0 and hart 1.

The timeline exercises use captures decoded in advance. Decoding takes about eight
minutes and requires a decoder that is not installed on your instance.""")

md("""### 3.1 Open Perfetto

Open Perfetto on your laptop and wait for the page to finish loading:

<https://ui.perfetto.dev>

Look for **Open trace file** in the left sidebar. Keep the tab open so you can use it
if the internet connection drops. The first load requires internet access, and the
room has no offline copy of the viewer.

""" + fixes_table([
    ("Perfetto cannot load because the internet connection is down.", "Follow along with a neighbour who has the viewer open, or watch the instructor's demonstration."),
]))

md("""### 3.2 Inspect a supplied trace

Inspect a trace of a field-oriented control loop supplied with the notebook. The
next cell unpacks it into `rocket_tacit_trace.perfetto.json`.""")
code("t = lab.unpack_trace()")
md("""This trace was captured on a Rocket SoC on 2026-09-16. It contains 534,990 decoded
instructions, recorded at 2.021 bits per instruction. The unpacked timeline is about
1.99 MB.

The next cell ranks functions by their own trace ticks, excluding time spent in
functions they call.""")
code("lab.trace_summary(t)")
md("""Read the `self ticks` and `share` columns to identify the busiest functions:

""" + fence(
    "function                    self ticks   share    calls\n"
    "__muldf3                       210,583   31.3%    1,515\n"
    "__subdf3                        99,067   14.7%    1,146\n"
    "__mulsf3                        56,400    8.4%      600") + """

Six of the eight busiest functions are compiler routines for floating-point arithmetic:
`__muldf3`, `__subdf3`, `__mulsf3`, `__addsf3`, `__subsf3`, and `__adddf3`. The core has
no floating-point unit, so it implements the control loop's `float` and `double`
operations in software. These routines account for much of the recorded execution time.

In JupyterLab's file browser, right-click `rocket_tacit_trace.perfetto.json` and choose
**Download**. Drag the downloaded file into the Perfetto tab you opened in 3.1.""")

md("""### 3.3 Compare trace start points

The point where you enable tracing determines which part of execution you record.
The two recorded runs below perform the same application work. One starts tracing at
reset, and the other starts at `main()`. Compare their first events and the cycles
recorded before `main()`.

| Measurement | Trace starts at reset | Trace starts in `main()` |
|---|---|---|
| Work counted by the application | **24,093** | **24,093** |
| Cycles while the encoder was enabled | 1,636,333 | 679,794 |
| Cycles before `main()` | **958,012 (58.5 %)** | 0 |
| Trace bytes | 147,093 | 135,182 |
| Timeline events | 10,064 | 9,839 |
| Distinct function names | **93** | **42** |
| First event | **`z_prep_c`** | **`__floatsidf`** |

The reset capture includes 958,012 cycles before `main()`, or 58.5% of its recorded
window. Its first function, `z_prep_c`, clears the BSS during boot. The capture started
at `main()` begins in `__floatsidf`, the compiler's integer-to-double helper.

Why are the trace sizes so close when the recorded cycle counts differ so much?

<details>
<summary>How compression affects trace size</summary>

The two captures differ by 8.8% in bytes and 2.3% in timeline events. Their five
busiest functions appear in the same order. The encoder compresses control flow, so
long stretches of straight-line boot code can occupy relatively few trace bytes.

Check the first event to establish where a capture begins. In these runs, the number
of distinct function names also helps identify whether boot was included: 93 from
reset and 42 from `main()`.

</details>""")

md("""### 3.4 Capture both harts on your board

This application runs SignDetLite on hart 0 and a wake-word model on hart 1. It
enables both trace encoders from reset and stops them at a shared deadline about
13 seconds later.

Hart 0 supports the packed-SIMD instructions used by SignDetLite. Hart 1 runs scalar
code. The shared window lets you compare when each core performs model work.

Build the capture application with the next cell. It includes both models and takes
a few minutes to build.""")
code('''lab.sh("""cd /home/ubuntu/tut && source /home/ubuntu/tut/env.sh && \\
./scripts/90_b156_tacit_window.sh --name lab3 --build-only""", timeout=1800)''')
md("""Look for `lab3_duo: bin=1096544 B  window_ms=13000 frames=0 kws_s=60` at the end of
the build.

The next cell uploads the application, selects the `trace` bitstream, and starts the
capture. This configuration includes the trace encoders and omits the dispatch engine.
After downloading the capture, complete the restoration step below to reload the
`all` bitstream before using the board again.""")
code('''lab.board_put("/home/ubuntu/tut/out/lab3_duo/zephyr.bin", "tacit.bin")
lab.board("bitstream", "trace")
lab.board("run", "tacit", timeout=300)''')
md("""In the recorded run, the 1,096,544-byte upload took about eight seconds. Loading
the bitstream took fourteen seconds, and the run operation took seventy-five.
The next cell reads the console and prints the capture checks.""")
code('''c = lab.board("get", "console.out", binary=True, verbose=False)
for line in c.stdout.decode("utf-8", "replace").splitlines():
    if line.startswith(("DUO_TRACE_ARM", "DUO_TRACE_HART", "DUO_TRACE_GATE", "SD_REPLAY_END",
                        "DUO_DONE")):
        print(line)''')
md("""Card 3 reported the following capture. Compare `DUO_TRACE_GATE` and `DUO_DONE`
with your result:

""" + fence(
    "DUO_TRACE_ARM hart=0 from_reset=1 buf=0x81000000 addr_rb=0x81000000 span=67108864 "
    "count_at_main=170040 ok=1\n"
    "DUO_TRACE_ARM hart=1 from_reset=1 buf=0x85000000 addr_rb=0x85000000 span=150994944 "
    "count_at_main=93040 ok=1\n"
    "SD_REPLAY_END decisions_ok=1 tensors_ok=1 thr_match=1\n"
    "DUO_TRACE_HART hart=0 buf=0x81000000 bytes=23596344 span_cycles=534655340 "
    "bytes_per_s=1765349 buf_span=67108864 full_pct=35 armed=1 ...\n"
    "DUO_TRACE_HART hart=1 buf=0x85000000 bytes=15962636 span_cycles=534655340 "
    "bytes_per_s=1194237 buf_span=150994944 full_pct=10 armed=1 ...\n"
    "DUO_TRACE_GATE overrun=0 overlap=0 base0=0x81000000 end0=0x82680d38 base1=0x85000000 "
    "end1=0x85f3920c\n"
    "DUO_DONE want=2 got=2 sign=1 kws=1") + """

Check for `overrun=0 overlap=0` in `DUO_TRACE_GATE` before using the capture. These
fields report whether the trace data stayed within its allocated regions and whether
the two regions overlap. Ask an instructor if either value is nonzero.

The `DUO_DONE` line reports whether both harts finished. In this run,
`count_at_main=170040` shows that hart 0 had already written 170,040 trace bytes when
it entered `main()`.

Your byte counts may differ because the amount of work completed within the timed
window varies between runs.

<details>
<summary>Why the trace buffers need explicit checks</summary>

The trace sink writes sequentially from its base address. It has no limit register
and keeps writing when its allocated region fills. If one hart writes beyond its
region, it can overwrite the other hart's trace.

The application checks the written ranges against the allocated regions. An
overwritten trace may still decode, so the buffer checks are needed before interpreting
the result.

</details>

The next cell reads both traces from board memory. The `drain` operation uses the
addresses and lengths reported by the board and compresses the files before transfer.
The recorded capture compressed from about 39 MB to 3 MB.""")
code('''d = lab.board("drain", timeout=900, verbose=False)
import json
drain = json.loads(d.stdout)
print(f'{drain["lanes"]} lanes, {drain["bytes"]:,} bytes of trace, '
      f'{drain["gz_bytes"]:,} bytes compressed')
for lane in drain["drained"]:
    got = lab.board("get", lane["name"], binary=True, verbose=False).stdout
    open(lane["name"], "wb").write(got)
    print(f'  hart {lane["hart"]}: {lane["name"]}, {len(got):,} B '
          f'(the card declared {lane["gz_bytes"]:,})')''')
md("""Allow about a minute for the download. Check that each file's size matches the
size declared by the board:

""" + fence(
    "2 lanes, 39,558,980 bytes of trace, 3,148,637 bytes compressed\n"
    "  hart 0: tacit0.out.gz, 2,604,891 B (the card declared 2,604,891)\n"
    "  hart 1: tacit1.out.gz, 543,746 B (the card declared 543,746)") + """

The downloaded `tacit0.out.gz` and `tacit1.out.gz` contain your capture. The timeline
in 3.5 comes from a separate capture decoded in advance.

**Restore the board before continuing.** Run the next cell to reload the `all`
bitstream and restart `boot_info`.""")
code('''lab.board("bitstream", "all")
lab.board("run", "boot_info", timeout=300)''')
md("""Check that the responses include `\"loaded\": \"all\"` and `\"ran\": \"boot_info\"`.
The loader checks the FPGA configuration, and the run log should contain:

""" + fence("MAGIC = 0x5A5A0038 OK") + """

The OLED's uptime counter should restart at `up 0:00`.""")

md("""### 3.5 Compare both cores on a shared timeline

This section reads supplied lane statistics from `assets/lane_timeline.json`. Each
lane represents one core in a capture decoded before the session. The next cell
summarizes the work recorded on each lane.""")
code('''import json
lanes = json.load(open("assets/lane_timeline.json"))
for pid, lane in lanes["lanes"].items():
    print(f'pid {pid}  {lane["name"]}')
    print(f'    {lane["events"]:>7,} events, {lane["distinct"]} distinct frames')
    print(f'    in the model {lane["model_time_pct"]:5.1f}% of the window, '
          f'spin/console/idle {lane["idle_time_pct"]:5.1f}%')
print(f'\\nmodel work on the two lanes ends {lanes["ends_together_s"]:.2f} s apart '
      f'= {lanes["ends_together_pct"]:.1f}% of the window')
print("gates:", lanes["gates"])''')
md("""Compare how much of the capture window each hart spends in model functions:

""" + fence(
    "pid 0  hart 0 (BIG, MBP) signdet_live\n"
    "        258,393 events, 179 distinct frames\n"
    "        in the model  22.4% of the window, spin/console/idle  53.9%\n"
    "pid 1  hart 1 (LITTLE, scalar) kws_live\n"
    "        109,712 events, 103 distinct frames\n"
    "        in the model  75.8% of the window, spin/console/idle   6.1%\n\n"
    "model work on the two lanes ends 0.10 s apart = 0.7% of the window") + """

Both lanes share a 13.309-second window from reset, containing 368,105 events. The
trace records encoder stop times 94 and 248 cycles from the end of that window.
The next cell plots model activity over time.""")
code("lab.lane_timeline_figure(lanes)")
md("""Each point shows the fraction of a time bucket spent inside an `mb_pext_conv` call.
Both lanes contain model work in every bucket after startup. The dashed lines mark
the end of the last such call on each hart.

<details>
<summary>Estimate buffer requirements from an active capture</summary>

A busy hart 0 produced 0.0443 bytes per core cycle, or 1.77 MB/s. In a separate run
where it was idle for 80% of the window, its average rate was 0.0084 bytes per core
cycle, about five times lower.

A spin loop produces relatively little trace data, so idle periods lower the average
rate. Use a recording in which the core stays busy to estimate the buffer size for
your planned capture.

</details>""")

md("""### 3.6 Optional: view the supplied trace in the notebook

The next cell opens the supplied trace from 3.2 in an embedded Perfetto viewer. The
notebook transfers the trace from your instance to your browser automatically.""")
code('''lab.show_perfetto(t)''')
md("""The viewer reports its progress above the embedded timeline:

""" + fence(
    "fetch -> HTTP 200\n"
    "trace in the page: 1989396 bytes\n"
    "viewer loaded\n"
    "handed to the viewer -- answer Yes in the frame below") + """

When Perfetto asks whether this notebook may open the file, choose **Yes**.""")

# ======================================================================================
# Units 4 and 5
# ======================================================================================
md("""---

## Unit 4 · Optimize a kernel with a language model

Unit 2 used kernels written by hand. In this unit, you will use ModelBlaster to ask a
language model to rewrite `maxpool2d_s8`, then check its correctness and measure its
speed on your board.

The reference kernel compares signed 8-bit values one pair at a time. The board's
`MBP.MAX8` instruction compares eight pairs at once. The model's task is to arrange the
values in packed registers so the loop can use that instruction.""")

md("""### 4.1 Follow the optimization loop

ModelBlaster asks the model for candidate kernels and evaluates them in Spike, a
RISC-V simulator. It ranks the candidates by simulated cycle count. The supplied
Spike build supports the board's MBP instructions, including `MBP.MAX8`.

After the first round, the optimizer builds the best candidate for your FPGA and
measures it on the board. It adds those measurements to the model's prompt for the
second round.

Spike counts each instruction as one cycle and omits memory timing. The board
measurements give the model feedback about costs that Spike cannot represent,
including memory access delays.

<details>
<summary>How the run checks correctness</summary>

The run uses three checks:

- ModelBlaster verifies each candidate on the host using four shapes with random inputs.
- Spike runs the kernel on a test tensor and compares its output with the expected values.
- A negative control executes a `custom-0` instruction on hart 1, where MBP is unavailable.
  That instruction must trap, confirming that the core rejects it.

The run requires these checks to pass before accepting a result.

</details>""")

md("""### 4.2 Check the optimizer setup

The next cell checks for four required files: the model credentials, the development
environment settings, the Spike build with MBP support, and the optimizer script.""")
code('''ready = lab.mb_preflight()''')
md("""Check that all four lines say `yes`. If any says `NO`, the next cell skips the
optimization and looks for a saved run on your instance. Ask the instructor for help
with the missing setup.""")

md("""### 4.3 Run the search

The next cell requests two rounds of optimization for `maxpool2d_s8` and limits the
search to eight model calls with `--max-calls 8`. The search can stop early if a round
finds no improvement.""")
code('''if ready:
    r = lab.sh("cd ~/iiswc-tutorial && . ~/.config/iiswc/dev.env && . ./env.sh && "
               "./scripts/95_mb_kernel_llm.sh --op maxpool2d_s8 --where board --board-loop "
               "--beam 2 --expansions 2 --rounds 2 --max-calls 8",
               timeout=3600, head=0, tail=18)
run = lab.mb_latest_run()
print("reading", run)''')
md("""Allow several minutes for the script to complete its seven steps and print a verdict.
Building and simulating the candidates accounts for much of that time.

Check the path after `reading` to see which run the remaining cells will inspect. If
it prints `reading None`, ask the instructor for a saved run before continuing.""")

md("""### 4.4 Inspect the model calls

The `--beam`, `--expansions`, and `--rounds` settings control how many candidates the
search can explore. Read the call log below to see how many calls it actually made.
The table gives each call's round, phase, input and output token counts, and time in
seconds.""")
code('''lab.show_search_shape(run)''')
md("""The `phase` column distinguishes `synth` calls, which request an initial kernel,
from `optimize` calls, which request improvements.

Compare the `in` column between rounds. The prompt includes board measurements once
they are available, so later calls may use more input tokens.""")

md("""### 4.5 Read the board feedback

The optimizer writes the board measurements to a feedback file and adds them to the
next round's system prompt. Read the file below to see what information the model
receives.""")
code('''lab.show_board_feedback(run)''')
md("""Find the cycles per output for the reference kernel and the previous round's
candidate, measured on the FPGA at 40 MHz. The feedback also explains that Spike
omits memory timing.

<details>
<summary>Give the model more detailed feedback with TACIT</summary>

You could extend the search to include a TACIT trace from Unit 3. The model would
then see which functions ran and how execution moved through them, alongside the
board's cycle totals.

</details>""")

md("""### 4.6 Inspect the generated kernel

The next cell shows a loop from a kernel saved during the search.""")
code('''lab.show_llm_kernel(run, around="for (")''')
md("""The recorded kernel loads eight bytes at a time into a register and calls
`mb_pext_max8` to compare the packed values. Your generated kernel may differ.
Follow one loop iteration to see which input values it compares and which outputs
it writes.""")

md("""### 4.7 Compare the board results

The board runs three builds with the same input data:

| Row | Kernel |
|---|---|
| `before` | The reference kernel. |
| `after` | The generated kernel using MBP instructions. |
| `mbpoff` | The generated kernel built with `-DMB_PEXT_HW=0`. |""")
code('''lab.show_board_verdict(run)''')
md("""Check that all three rows report `bit-exact`, then compare their cycles per output.
Lower values mean the kernel finished faster.

With `-DMB_PEXT_HW=0`, the kernel keeps its packed eight-byte loads and executes a C
implementation of `mb_pext_max8`. Comparing `mbpoff` with `after` measures the benefit
of using the hardware instruction within that packed loop.

<details>
<summary>Interpret the speedup ratios</summary>

The recorded ratios were about 1.7× from `before` to `mbpoff`, 9.1× from `mbpoff` to
`after`, and 15.3× overall. The first comparison measures the combined effect of
packed loads and software SIMD emulation. It cannot isolate the loop rewrite's
contribution.

A separate bench experiment disabled the MBP path entirely. That version ran
**three percent slower than the reference**. For this kernel, the loop rewrite
makes `MBP.MAX8` usable, and the instruction provides most of the measured speedup.

</details>""")

md("""---

## Unit 5 · Schedule two models with XPU-RT

XPU-RT chooses where and when each operator runs. You will first solve a small
schedule on your instance, then compare saved schedules for two models sharing the
board's cores and memory. The instructors will demonstrate the robot, RiskyBird,
during the session.""")

md("""### 5.1 Solve a schedule for eight operators

Run the CP-SAT solver on a workload with eight dispatches. Each dispatch is one
operator invocation. The solver chooses a device and start time for each one while
respecting dependencies and device constraints.""")
code('''lab.sh("""source /etc/profile.d/xpurt.sh && cd $XPURT_ROOT && \\
XPURT_CPSAT_WORKERS=1 $XPURT_PYTHON scripts/run_xpurt_schedule.py \\
  --networks-json data/toplevel/networks_b154_gate.json \\
  --solver cpsat --profiled --cpsat-time-limit 60""", timeout=300)''')
md("Find the summary near the end of the output. The recorded run printed:\n\n" + fence(
    "makespan_us=237.87  op_deadline_miss=0 (dispatches, NOT instances)  cross_dev=0  solver_s=0.377")
   + """

The recorded solve reached an optimal schedule in 0.377 seconds. `makespan_us`
describes the schedule's duration using operator timings measured on the board.
`solver_s` measures the time your instance spent solving it.

For the same profiles and optimal solution, a faster host changes the solve time
while the schedule duration stays the same. Use the next cell to check the saved
`makespan_us` value against 237.87.""")
code("""import json, os
root = os.environ.get("XPURT_ROOT", "/opt/xpurt/XPU-RT")
m = json.load(open(os.path.join(
    root, "schedules/scheduled_networks_b154_gate_cpsat_profiled_metrics.json")))
lab.expect("makespan_us", round(m["makespan_us"], 2), 237.87)""")
md("""Open the schedule plot and follow the operators across the device lanes. Each
operator's position shows when it runs and which device executes it.""")
code("""from IPython.display import Image
Image(filename=os.path.join(root, "plots/networks_b154_gate_cpsat_profiled.png"))""")
md(fixes_table([
    ("The log stays quiet while the cell runs", "Python may buffer its output. Allow time for startup; the full command took about three seconds in the recorded run. Ask the instructor for help if it remains quiet for minutes."),
]))

md("""### 5.2 Compare schedules for two models

Now consider SignDetLite and Moonshine sharing two harts with different instruction
sets and a common memory system. SignDetLite runs four times at **1,000 ms intervals**.
Moonshine processes one speech job alongside those detector inferences.

A passing schedule must meet all four detector windows and finish Moonshine within
the **4,000 ms** reference time. You will compare scheduling methods and examine
compaction, a pass that moves dispatches into earlier free time slots while preserving
the schedule's constraints.

The next cells read saved results from `expected/xpurt_coloc2m_b157.json` and draw a
comparison. They do not run XPU-RT. If the file is missing from your checkout, follow
the printed example and discussion below.

<details>
<summary>How the experiment covers 44 configurations</summary>

Each configuration selects one option from each row:

| Setting | Options |
|---|---|
| Scheduling method | Nine heuristics and two CP-SAT paths. |
| Memory contention | `none` uses uncontended timings; `dram` includes measured DRAM contention. |
| Compaction | `plain` keeps the generated schedule; `compact` applies the compaction pass. |

These choices give 11 × 2 × 2 = 44 configurations, each with 2,285 dispatches.
Section 5.3 lets you rerun one of them.

</details>""")
code('''import json
golden_path = lab.repo_file("expected/xpurt_coloc2m_b157.json")
if golden_path is None:
    raise SystemExit("This checkout does not ship expected/xpurt_coloc2m_b157.json -- "
                     "that golden lives in the curated public tree.")
g = json.load(open(golden_path))
for name, cell in g["headline_cells"].items():
    if name.startswith("_"):
        continue
    print(f'{name:<32} {cell["moonshine_end_ms"]:>9,.2f} ms   '
          f'windows {cell["windows_landed"]:<6} '
          f'{"PASSES" if cell["real_time_ok"] else "FAILS"}')
print()
print("cells", g["totals"]["cells"], "| dispatches per schedule",
      f'{g["totals"]["dispatches_per_schedule"]:,}',
      "| machine overlaps", g["totals"]["machine_overlaps"])''')
md("""Read both Moonshine's completion time and the number of detector windows met:

""" + fence(
    "best_heuristic_makespan           4,251.12 ms   windows 1 of 4  FAILS\n"
    "only_heuristic_landing_all_four   6,076.00 ms   windows 4 of 4  FAILS\n"
    "cpsat_none_plain                  3,649.06 ms   windows 4 of 4  PASSES\n"
    "cpsat_none_compact                3,272.91 ms   windows 4 of 4  PASSES\n"
    "cpsat_dram_plain                  5,412.25 ms   windows 4 of 4  FAILS\n"
    "cpsat_dram_compact                3,992.30 ms   windows 4 of 4  PASSES\n\n"
    "cells 44 | dispatches per schedule 2,285 | machine overlaps 0"))
code("lab.schedule_comparison_figure(g)")
md("""Compare the CP-SAT schedules in the top panel. With measured DRAM contention,
compaction moves Moonshine's completion from 5,412.25 ms to **3,992.30 ms**, saving
1,419.95 ms and bringing it within the four-second target. Both schedules have
`op_deadline_miss_count` of 0, so all detector windows remain satisfied. Without
contention, compaction saves 376.15 ms.

The bottom panel shows the heuristic schedules. The fastest policies, `heft` and
`critical_path`, finish Moonshine at 4,251.12 ms and miss three of the four detector
windows. Only `edf` meets all four windows, but Moonshine finishes at 6,076.00 ms,
which exceeds the reference by 2,076 ms. All 36 heuristic configurations fail at least
one of the two requirements.

<details>
<summary>Why compaction helps these CP-SAT schedules</summary>

The heuristic results contain 18 pairs of plain and compact schedules. In every
pair, compaction moves 0 of 2,285 dispatches and saves 0.000 ms. The list schedulers
already place each dispatch at the earliest feasible time for their chosen order.
Their schedules leave no gaps that this pass can remove. The plot therefore shows
only the 18 plain configurations.

The CP-SAT schedules contain gaps that compaction can remove by starting dispatches
earlier while respecting their dependencies and resource constraints.

</details>

<details>
<summary>Read the detector frame rates</summary>

The fastest heuristic meets one of four detector windows, equivalent to 0.25 on-time
frames per second. A passing schedule meets all four, or 1.0 fps. The experiment also
reports a capacity estimate of 2.62 fps.

</details>""")
code('''for c in g["compaction"][:4]:
    print(f'{c["scheduler"]:<22} {c["contention"]:<5} '
          f'{c["recovered_ms"]:>10,.3f} ms  {c["dispatches_moved"]:>5,} moved  {c["result"]}')
print(f'\\n{len(g["refused"])} cells were REFUSED, not reported:')
for r in g["refused"]:
    print(f'  {r["scheduler"]} {r["contention"]}/{r["compaction"]}: '
          f'{r["exclusion_violations"]} exclusion violations, '
          f'withheld makespan {r["withheld_makespan_ms"]:,.2f} ms')''')
md("""The validation report rejects four configurations with forbidden device assignments
involving 74 dispatches. They place `linear_s8` on a core marked infeasible by the
dispatch graph and `permute4_s8` on the hart without the P-extension. Those kernels
would execute unsupported instructions on their assigned cores.

Check device validity before comparing completion times. The shortest Moonshine
completion time across all 44 configurations, 3,272.91 ms, belongs to a valid schedule.

<details>
<summary>Why the solver allowed forbidden assignments</summary>

One CP-SAT path omits `infeasible_combinations` when building its model. It therefore
treats forbidden placements as available options with ordinary durations. The
resulting completion times can look plausible even though the assignments are invalid.

The invalid `warmbest` result is faster in only one of the four paired comparisons.
Excluding those results leaves the best valid completion time unchanged.

</details>""")

md("""### 5.3 Optional: solve one configuration

Rerun the FIFO configuration with no memory contention and no compaction. Allow
about half a minute for this heuristic run. The full 44-configuration sweep takes
hours because it includes CP-SAT solves.

Set `XPURT_ROOT` to an XPU-RT checkout and `XPURT_PY` to a Python interpreter with
`ortools` before running these cells. Both are separate from the tutorial repository.
If they are unavailable, you can use the saved results in 5.2.

The first cell prepares the configuration's working directory. The supplied sweep
has a path problem and can exit successfully without producing a schedule. If it
prints `the sweep produced NO schedule`, continue with the second cell, which applies
the workaround. Check the schedule output to confirm that the solve succeeded.""")
code('''import os, glob
sweep = lab.repo_file("scripts/12_xpurt_coloc_sweep.sh")
root, py = os.environ.get("XPURT_ROOT"), os.environ.get("XPURT_PY")
cell_dir = None
if not sweep:
    print("STUB: no scripts/12_xpurt_coloc_sweep.sh in this checkout -- nothing was run.")
elif not (root and py and os.path.isdir(root) and os.access(py, os.X_OK)):
    print("Not run: set XPURT_ROOT to an XPU-RT checkout and XPURT_PY to an "
          "interpreter that has ortools. 5.2 above needs neither.")
else:
    repo = sweep.parent.parent
    lab.sh(f"cd {repo} && STAGE=heur POLICIES=fifo CONT_ARMS=none COMPACT_ARMS=plain "
           f"JOBS=1 {sweep}", timeout=900, quiet=True)
    got = glob.glob(f"{repo}/out/b157/schedules/none/plain/*_metrics.json")
    cell_dir = f"{repo}/out/b157/work/fifo_none_plain"
    print("the sweep produced a schedule" if got else
          "the sweep produced NO schedule -- the base-path trap above. "
          "The next cell runs the same solve the way that works.")''')
md("""Run the solver using the script inside `cell_dir`, where the previous cell prepared
the input data. The solver runs only if that directory exists.

<details>
<summary>Why the script path matters</summary>

The sweep creates a working directory containing links to XPU-RT and this tutorial's
input files. `run_xpurt_schedule.py` resolves data paths relative to its own location.
The original invocation points at the XPU-RT checkout, where the tutorial's data is
missing, and fails with `dispatch_deps_path not found at ''`.

Calling the script inside the configuration's working directory lets it find the
input files prepared there.

</details>""")
code('''if cell_dir and os.path.isdir(cell_dir):
    spec = lab.repo_file(
        "fpga/pynq-z2/xpurt/networks_pynqz1_coloc2m_sdp_b4_T1000.json")
    inject = lab.repo_file("scripts/lib/b157_inject")
    r = lab.sh(
        f"cd {cell_dir} && env -u XPURT_NO_COMPACT -u XPURT_COMPACT "
        f"PYTHONPATH={inject} XPURT_CPSAT_PYTHON={py} XPURT_CPSAT_WORKERS=1 "
        f"{py} {cell_dir}/scripts/run_xpurt_schedule.py "
        f"--networks-json {spec} --scheduler fifo --profiled",
        timeout=900, quiet=True)
    for line in r.stdout.splitlines():
        if "makespan_us" in line:
            print(line.strip())
    row = next(x for x in g["rows"] if x["policy"] == "fifo"
               and x["contention"] == "none" and x["compaction"] == "plain")
    print(f'golden says moonshine_end_ms={row["moonshine_end_ms"]}, '
          f'late_detector_dispatches={row["late_detector_dispatches"]}')
else:
    print("No cell farm to run in -- 5.2 carries the result without it.")''')
md("""The recorded FIFO run matched the saved completion time and late-dispatch count:

""" + fence("makespan_us=6339.28  op_deadline_miss=21 (dispatches, NOT instances)  "
            "cross_dev=1438  solver_s=0.484\n"
            "golden says moonshine_end_ms=6339.28, late_detector_dispatches=21") + """

Compare `op_deadline_miss` with `late_detector_dispatches`: both report 21. These
misses count individual operator dispatches; a single detector inference contains
several dispatches. Your `solver_s` value will vary with the machine running the solve.""")

# ======================================================================================
# The demos
# ======================================================================================
md("""---

## Watch the live demos

The instructors will demonstrate the speech and traffic-sign models from Units 2 and 5
using live microphone and camera input. Both run on the same SoC design used throughout
the tutorial. Watch the board's indicators and display as each model processes its input.""")

md("""### Transcribe speech on the board

The demo samples the room's background noise for two seconds. The instructor then
claps to start a four-second recording and speaks into the microphone. The lamp turns
green during recording and blue during transcription. The transcript appears on the
console and display.

The board takes about **4.7 seconds to transcribe the clip after recording finishes**.
It handles one clip at a time and pauses recording during transcription. The model
weights and audio stay on the SoC; the host supplies power and a console.

<details>
<summary>Compare the live and batched speech timings</summary>

Dividing the 4.7-second compute time by the four-second audio duration gives a
real-time factor of about 1.18. Transcription takes longer than the speech itself,
even before accounting for the separate recording phase.

A separate benchmark on the same model and board reported a real-time factor of 0.89
when it processed four recordings as a batch. The decoder's matrix multiplications
have four rows, one per utterance, so each weight load serves all four. The live demo
processes one recording at a time.

</details>

<details>
<summary>How audio preprocessing affects the accuracy comparison</summary>

The batched benchmark measured word error with a 1,000-tap equalizer running on the
ARM core. The live demo image omits this equalizer. Running the benchmark without it
produced a word error rate above 20%.

</details>""")

md("""### Detect traffic signs on the board

The instructor points the camera at a sign. The board runs the detector from Unit 2
and updates its display with **STOP**, **YIELD**, or **NO SIGN**.

Model inference takes **237 to 238 ms**. Capturing, processing, and displaying a whole
frame takes about **0.55 seconds**, giving roughly 1.8 frames per second.

<details>
<summary>Where the frame time goes</summary>

The inference timing was measured over 400 runs and agrees with Unit 2's prediction
and measurement on a saved frame. Inference accounts for less than half the total
frame time. The board also converts Bayer camera data into a 64x64x3 image, performs
L2 cache maintenance so the ARM core can read the frame, and updates the display.

</details>

<details>
<summary>How the demo checks its results</summary>

At startup, the board runs eight saved camera captures through the detector and
compares its answers with reference results computed on the host. It checks the
class, grid cell, confidence, and all 192 bytes of each output tensor.

The recorded run matched **all eight decisions and all eight tensors exactly**.
Both the host and the board rejected a detection in one capture because its confidence
was too low.

</details>

<details>
<summary>Why the demo uses a higher confidence threshold</summary>

The detector reported a sign on an empty bench about half the time at its default
confidence threshold. That measurement came from one test room. The demo uses a
higher threshold to reduce false detections.

</details>""")

md("""### Instructor note: speech demo readiness

The speech demo works on the bench board. Three limitations remain:

- The build for the attendee board's bitstream exists but has not been run on hardware.
- The variant that starts recording with a button press still needs to be built and run.
- The tools read the transcript from the guest console. On attendee boards, the tool
  account lacks permission to read that console device.""")

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
NB.write_text(json.dumps(nb, indent=1) + "\n")
print(f"wrote {NB}  ({len(cells)} cells)")
