#!/usr/bin/env python3
"""Generate fpga/pynq-z2/sw/audio_fe_tables.c -- the constant tables audio_fe.c reads.

Everything here is derived from four numbers (the sample rate, the FFT length, the frame
length and the mel band edges) and nothing here is tuned.  The file is regenerated rather
than edited; `--check` re-derives it and diffs, which is what the build gate uses.

The sample rate defaults to the rate the PYNQ-Z1's PDM decimator actually produces --
15993.859 Hz, not 16000 (fpga/pynq-z2/docs/MICROPHONE.md section 3.2).  It moves the mel
edges by 0.04 %, which is far below a bin, but using the real number costs nothing and
means the tables and the hardware agree about what "4 kHz" is.
"""
import argparse, math, sys, pathlib

SR_DEFAULT = 15993.859
NFFT = 512
FRAME = 400
HOP = 160
NMEL = 40
NDCT = 10
FMIN = 20.0
FMAX = 7600.0
DCT_ROW_SCALE = (0.25, 1.0)   # (c0, c1..c9) -- see build()


def _derive():
    global NCFFT, NBINS
    NCFFT = NFFT // 2
    NBINS = NFFT // 2 + 1


_derive()


def q31(x):
    v = int(round(x * (1 << 31)))
    return max(-(1 << 31), min((1 << 31) - 1, v))


def q15(x):
    v = int(round(x * (1 << 15)))
    return max(-(1 << 15), min((1 << 15) - 1, v))


def hz2mel(f):
    return 2595.0 * math.log10(1.0 + f / 700.0)


def mel2hz(m):
    return 700.0 * (10.0 ** (m / 2595.0) - 1.0)


def build(sr):
    tw = []
    for k in range(NCFFT):
        a = -2.0 * math.pi * k / NFFT
        tw += [q31(math.cos(a)), q31(math.sin(a))]

    # Periodic (not symmetric) Hann -- the STFT convention.
    win = [q15(0.5 - 0.5 * math.cos(2.0 * math.pi * n / FRAME)) for n in range(FRAME)]

    # Mel filterbank: NMEL triangles between NMEL+2 equally-mel-spaced edges.
    edges = [mel2hz(hz2mel(FMIN) + (hz2mel(FMAX) - hz2mel(FMIN)) * i / (NMEL + 1))
             for i in range(NMEL + 2)]
    bin_hz = sr / NFFT
    starts, lens, offs, weights = [], [], [], []
    for m in range(NMEL):
        lo, ctr, hi = edges[m], edges[m + 1], edges[m + 2]
        w = []
        first = None
        for b in range(NBINS):
            f = b * bin_hz
            if f <= lo or f >= hi:
                continue
            g = (f - lo) / (ctr - lo) if f <= ctr else (hi - f) / (hi - ctr)
            if g <= 0.0:
                continue
            if first is None:
                first = b
            w.append(q15(g))
        if first is None:          # a triangle narrower than one bin: snap to nearest
            first = max(0, min(NBINS - 1, int(round(ctr / bin_hz))))
            w = [1 << 15 >> 1]
        starts.append(first)
        lens.append(len(w))
        offs.append(len(weights))
        weights += w

    # Orthonormal DCT-II, NMEL -> NDCT.
    #
    # ROW 0 CARRIES AN EXTRA 1/4, AND IT IS NOT COSMETIC.  c0 is sum_n logmel[n]/sqrt(40)
    # -- forty same-sign terms -- so it is ~6x larger than any other coefficient and it
    # SATURATED the int16 output on 5.85 % of measured frames, silently, which is data
    # loss that looks like a perfectly ordinary feature.  c1..c9 are differences of
    # log-mels and stay an order of magnitude smaller, so shrinking them too would just
    # throw away resolution where it matters.  The row scale is part of the front-end
    # contract: the training set is built with this same table, and DCT_ROW_SCALE below
    # is recorded in the model's meta.json.
    dct = []
    for k in range(NDCT):
        s = math.sqrt(1.0 / NMEL) if k == 0 else math.sqrt(2.0 / NMEL)
        s *= DCT_ROW_SCALE[0] if k == 0 else DCT_ROW_SCALE[1]
        for n in range(NMEL):
            # the extra 1/2 keeps every entry inside Q0.31 whatever the row scale is;
            # the consumer shifts it back once at the end.
            dct.append(q31(s * math.cos(math.pi * (n + 0.5) * k / NMEL) * 0.5))
    return tw, win, starts, lens, offs, weights, dct, edges


def carr(name, vals, typ, perline):
    out = ["static const %s %s[] = {" % (typ, name)] if False else []
    out = ["const %s %s[] = {" % (typ, name)]
    for i in range(0, len(vals), perline):
        out.append("\t" + ", ".join(str(v) for v in vals[i:i + perline]) + ",")
    out.append("};")
    return "\n".join(out)


# The two framings the tutorial measures. See audio_fe.h.
GEOMETRIES = {
    #          nfft  frame  hop   what it is
    "asr":   (512,   400,  160),  # 25 ms window, 10 ms hop, 100 frames/s
    "kws":   (512,   480,  320),  # 30 ms window, 20 ms hop, 50 frames/s -- MLPerf Tiny
}


def emit(sr):
    tw, win, starts, lens, offs, weights, dct, edges = build(sr)
    L = []
    L.append("/* SPDX-License-Identifier: Apache-2.0")
    L.append(" *")
    L.append(" * GENERATED by fpga/pynq-z2/sw/tools/gen_fe_tables.py -- do not edit.")
    L.append(" *   sample rate %.3f Hz, NFFT %d, frame %d, hop %d, %d mel filters"
             % (sr, NFFT, FRAME, HOP, NMEL))
    L.append(" *   %.0f-%.0f Hz, %d DCT rows (c0 scaled by %g, c1.. by %g)."
             % (FMIN, FMAX, NDCT, DCT_ROW_SCALE[0], DCT_ROW_SCALE[1]))
    L.append(" *   %.2f frames per second of audio." % (sr / HOP))
    L.append(" *   Regenerate with --check to prove this file matches.")
    L.append(" */")
    L.append('#include "audio_fe.h"')
    L.append("")
    L.append("/* A table built for one geometry and a kernel compiled for another produces a")
    L.append(" * plausible-looking spectrum that is simply wrong, so the two are pinned together")
    L.append(" * at compile time rather than by convention. */")
    L.append("_Static_assert(FE_NFFT == %d && FE_FRAME_LEN == %d && FE_HOP_LEN == %d &&"
             % (NFFT, FRAME, HOP))
    L.append("\t\t   FE_NMEL == %d && FE_NDCT == %d," % (NMEL, NDCT))
    L.append('\t\t   "audio_fe_tables.c was generated for a different geometry -- '
             'rerun tools/gen_fe_tables.py");')
    L.append("")
    L.append("/* W_512^k = exp(-2*pi*i*k/512), interleaved re,im, Q0.31. */")
    L.append(carr("fe_twiddle_q31", tw, "int32_t", 8).replace(
        "fe_twiddle_q31[]", "fe_twiddle_q31[FE_NCFFT * 2]"))
    L.append("")
    L.append("/* Periodic Hann, Q0.15. */")
    L.append(carr("fe_window_q15", win, "int16_t", 12).replace(
        "fe_window_q15[]", "fe_window_q15[FE_FRAME_LEN]"))
    L.append("")
    L.append("/* Triangular mel weights, Q0.15, packed filter by filter. */")
    L.append(carr("fe_mel_w_q15", weights, "int16_t", 12))
    L.append("const int fe_mel_nnz = %d;" % len(weights))
    L.append(carr("fe_mel_start", starts, "uint16_t", 10).replace(
        "fe_mel_start[]", "fe_mel_start[FE_NMEL]"))
    L.append(carr("fe_mel_len", lens, "uint16_t", 10).replace(
        "fe_mel_len[]", "fe_mel_len[FE_NMEL]"))
    L.append(carr("fe_mel_off", offs, "uint16_t", 10).replace(
        "fe_mel_off[]", "fe_mel_off[FE_NMEL]"))
    L.append("")
    L.append("/* DCT-II, orthonormal, pre-scaled by 1/2; Q0.31, row-major [k][n]. */")
    L.append(carr("fe_dct_q31", dct, "int32_t", 6).replace(
        "fe_dct_q31[]", "fe_dct_q31[FE_NDCT * FE_NMEL]"))
    L.append("")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    # the module-level names are what build() reads; rebind them from argv below
    ap = argparse.ArgumentParser()
    ap.add_argument("--sr", type=float, default=SR_DEFAULT)
    ap.add_argument("--nfft", type=int, default=NFFT)
    ap.add_argument("--frame", type=int, default=FRAME)
    ap.add_argument("--hop", type=int, default=HOP)
    ap.add_argument("--nmel", type=int, default=NMEL)
    ap.add_argument("--ndct", type=int, default=NDCT)
    ap.add_argument("--out", default=None)
    ap.add_argument("--geometry", default=None, choices=sorted(GEOMETRIES),
                    help="a named geometry from GEOMETRIES; sets nfft/frame/hop and "
                         "the default output file")
    ap.add_argument("--check", action="store_true",
                    help="with no --geometry, re-derive and diff EVERY named geometry")
    a = ap.parse_args()
    here = pathlib.Path(__file__).resolve().parents[1]
    todo = [a.geometry] if a.geometry else (sorted(GEOMETRIES) if a.check else ["asr"])
    bad = 0
    for name in todo:
        nfft, frame, hop = GEOMETRIES[name]
        if a.geometry is None or a.geometry == name:
            globals().update(NFFT=nfft, FRAME=frame, HOP=hop, NMEL=a.nmel, NDCT=a.ndct)
        else:
            globals().update(NFFT=a.nfft, FRAME=a.frame, HOP=a.hop,
                             NMEL=a.nmel, NDCT=a.ndct)
        _derive()
        text = emit(a.sr)
        out = pathlib.Path(a.out) if a.out else here / ("audio_fe_tables_%s.c" % name)
        if a.check:
            have = out.read_text() if out.exists() else ""
            if have != text:
                print("MISMATCH: %s is not what gen_fe_tables.py --geometry %s produces"
                      % (out, name))
                bad += 1
            else:
                print("ok  %s == gen_fe_tables.py --geometry %s --sr %.3f"
                      % (out.name, name, a.sr))
        else:
            out.write_text(text)
            print("wrote %s  (nfft %d frame %d hop %d -> %.2f frames/s)"
                  % (out, nfft, frame, hop, a.sr / hop))
    sys.exit(1 if bad else 0)
