#!/usr/bin/env python3
"""Emit the Q8 -> int8 feature map the board must use, from the model's own meta.json.

    python3 gen_feat_map.py --meta weights/cnn_meta.json --out kws_featmap.h

The map is twenty integers -- one offset and one shift per MFCC coefficient -- chosen by
fpga/pynq-z2/sw/tools/featurise.py from the TRAINING set's percentiles.  Generating the
header from the same file the trainer wrote is the point: an offset that disagrees by one
between training and inference is a silent accuracy loss with no symptom, and there is no
way to notice it from the board.
"""
from __future__ import annotations

import argparse, json, pathlib


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--meta", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    m = json.load(open(a.meta))
    off, sh, lab = m["off_q8"], m["shift"], m["labels"]
    # The classifiers write nframes/ncoef and one label per class; the CTC transcribers
    # write frames/ncoef and nclass, because their extra class is the blank and a blank
    # has no label. Accept either rather than making the two trainers agree on a schema
    # neither of them needs.
    nframes = m.get("nframes", m.get("frames"))
    nclass = m.get("nclass", len(lab))
    feature = m.get("feature", "mfcc")
    L = []
    L.append("/* SPDX-License-Identifier: Apache-2.0")
    L.append(" *")
    L.append(" * GENERATED by fpga/pynq-z2/sw/tools/gen_feat_map.py from %s"
             % pathlib.Path(a.meta).name)
    L.append(" * -- do not edit.  arch=%s  geometry=%s  feature=%s  %dx%d"
             % (m["arch"], m["geometry"], feature, nframes, m["ncoef"]))
    if "test_wer_fp32" in m:
        L.append(" * fp32 word error rate %.2f%% on connected digits built from Google"
                 % (100 * m["test_wer_fp32"]))
        L.append(" * Speech Commands v2.  %d classes = %d labels + the CTC blank."
                 % (nclass, len(lab)))
    else:
        L.append(" * fp32 test accuracy %.2f%% on %d-class Google Speech Commands v2."
                 % (100 * m["test_acc_fp32"], nclass))
    L.append(" */")
    L.append("#ifndef KWS_FEATMAP_H_")
    L.append("#define KWS_FEATMAP_H_")
    L.append("")
    L.append("#define KWS_NFRAMES   %d" % nframes)
    L.append("#define KWS_NCOEF     %d" % m["ncoef"])
    L.append("#define KWS_NCLASS    %d" % nclass)
    L.append("#define KWS_ARCH      \"%s\"" % m["arch"])
    L.append("#define KWS_MACS      %d" % m["macs"])
    L.append("/* 1 = the model wants [ncoef][nframes], i.e. TIME ON THE WIDTH AXIS. The")
    L.append(" * arithmetic is identical either way; the layout decides how long the")
    L.append(" * curated MBP conv kernel's NCHW gather runs are, and that is worth 4x. */")
    L.append("#define KWS_TRANSPOSED %d" % (1 if m.get("transposed") else 0))
    L.append("")
    L.append("/* One (offset, shift) per coefficient, from the training set's 0.5th and")
    L.append(" * 99.5th percentiles.  The MFCC coefficients do not share a dynamic range")
    L.append(" * -- c0 spans ~13,400 Q8 and c9 ~3,800 -- so one pair for the whole tensor")
    L.append(" * would quantise the informative coefficients to about sixteen levels. */")
    L.append("static const int   kws_feat_off[KWS_NCOEF] = { %s };"
             % ", ".join(str(int(v)) for v in off))
    L.append("static const int   kws_feat_shift[KWS_NCOEF] = { %s };"
             % ", ".join(str(int(v)) for v in sh))
    L.append("")
    names = list(lab) + ["_blank_"] * (nclass - len(lab))
    L.append("static const char *const kws_labels[KWS_NCLASS] = {")
    for i in range(0, len(names), 4):
        L.append("\t" + ", ".join('"%s"' % x for x in names[i:i + 4]) + ",")
    L.append("};")
    L.append("")
    L.append("#endif /* KWS_FEATMAP_H_ */")
    pathlib.Path(a.out).write_text("\n".join(L) + "\n")
    print("wrote %s  (%d coefficients, %d classes)" % (a.out, len(off), nclass))


if __name__ == "__main__":
    main()
