#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate src/font5x8.c, a 5x8 CFB font, from the X11 misc-fixed 5x7 bitmap font.

    python3 samples/oled_status/tools/gen_font5x8.py [--pcf /usr/share/fonts/X11/misc/5x7-ISO8859-1.pcf.gz]

Why a new font: the smallest stock CFB font is 10x16, which gives a 128x64 panel 4 rows of
12 characters -- too few for a five-line status screen. The 5x7 misc-fixed glyphs (one
column and one row of each cell are already spacing) in a 5x8 cell give 25 columns x 8 rows
for 475 bytes, against ~13.8 KB for the stock fonts.

Licence of the source glyphs: the PCF's COPYRIGHT property reads "Public domain font.  Share
and enjoy." The generated C array is committed so a build never needs this script or the PCF.

CFB format: CFB_FONT_MONO_VPACKED, LSB first -- one byte per glyph column, bit 0 = top row.
That is the SSD1306's SCREEN_INFO_MONO_VTILED order, so CFB draws it without reversing.
"""
import argparse, gzip, io, sys
from PIL import PcfFontFile

FIRST, LAST, W, H = 32, 126, 5, 8

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pcf", default="/usr/share/fonts/X11/misc/5x7-ISO8859-1.pcf.gz")
    ap.add_argument("-o", "--out", default=None)
    a = ap.parse_args()
    raw = gzip.open(a.pcf).read() if a.pcf.endswith(".gz") else open(a.pcf, "rb").read()
    f = PcfFontFile.PcfFontFile(io.BytesIO(raw))
    cr = f.info.get(b"COPYRIGHT", b"").decode()
    if "Public domain" not in cr:
        sys.exit(f"refusing: source font copyright is {cr!r}, not public domain")
    rows = []
    for code in range(FIRST, LAST + 1):
        g = f.glyph[code]
        cols = [0] * W
        if g is not None and g[3] is not None:
            (dx, dy), (x0, y0, x1, y1), _, im = g
            # dst bbox is relative to the baseline; ascent 6 puts y0=-6 at cell row 0.
            for yy in range(im.size[1]):
                for xx in range(im.size[0]):
                    if im.getpixel((xx, yy)):
                        cx, cy = x0 + xx, (y0 + 6) + yy
                        if 0 <= cx < W and 0 <= cy < 7:
                            cols[cx] |= 1 << cy
        ch = chr(code)
        rows.append("\t{" + ", ".join(f"0x{c:02x}" for c in cols) + "},"
                    + f"  /* 0x{code:02x} {ch if ch not in '*/\\' else ' '} */")
    out = [
        "/* SPDX-License-Identifier: Apache-2.0 */",
        "/*",
        " * GENERATED by samples/oled_status/tools/gen_font5x8.py -- do not edit.",
        f" * Source: X11 misc-fixed {f.info.get(b'FONT', b'').decode()}",
        f" * Source licence (PCF COPYRIGHT property): \"{cr}\"",
        " * 5x8 cells, CFB_FONT_MONO_VPACKED, LSB first (bit 0 = top row), ASCII 0x20..0x7e.",
        " */",
        "#include <zephyr/display/cfb.h>",
        "",
        f"static const uint8_t oled_font5x8[{LAST - FIRST + 1}][{W}] = {{",
        *rows,
        "};",
        "",
        f"FONT_ENTRY_DEFINE(oled_font5x8_entry, {W}, {H}, CFB_FONT_MONO_VPACKED, oled_font5x8, {FIRST}, {LAST});",
        "",
    ]
    text = "\n".join(out)
    if a.out:
        open(a.out, "w").write(text)
    else:
        sys.stdout.write(text)

if __name__ == "__main__":
    main()
