#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Scale the 5x8 OLED font up by an integer factor, for text read across a room.

    gen_font_scaled.py 2 > ../src/font10x16.c     # 10x16 -- 12 chars x 4 lines
    gen_font_scaled.py 3 > ../src/font15x24.c     # 15x24 --  8 chars x 2 lines

WHY SCALE RATHER THAN SHIP A REAL 10x16 FACE.  A hand-drawn or converted 16-pixel face is
better looking, but it is another licensed blob to carry and check.  Pixel-doubling the font
already in the tree costs 20 bytes per glyph, is exactly legible at 2x on a 128x64 panel, and
inherits the source font's public-domain licence.  If a nicer face is wanted later this file
is not in the way.

THE PACKING IS CFB's, NOT OURS.  subsys/fb/cfb.c:82 reads a VPACKED glyph as
`glyph_ptr[x * (height / 8) + y]` -- column-major, `height/8` bytes per column, bit 0 of each
byte the TOP row of that byte's 8-row band.  At height 16 that is two bytes per column: byte 0
rows 0..7, byte 1 rows 8..15.  Get this wrong and the glyph renders as interleaved stripes,
which is why the layout is quoted here rather than assumed.
"""
import re, sys, pathlib

SRC = pathlib.Path(__file__).resolve().parent.parent / "src" / "font5x8.c"


def load():
    txt = SRC.read_text()
    rows = re.findall(r"\{((?:0x[0-9a-fA-F]{2},\s*){4}0x[0-9a-fA-F]{2})\}", txt)
    if len(rows) != 95:
        sys.exit("expected 95 glyphs in %s, found %d" % (SRC, len(rows)))
    return [[int(b, 16) for b in r.replace(" ", "").split(",")] for r in rows]


def scale(glyph, k):
    """5x8 -> (5k)x(8k). Returns column-major bytes, `8k/8` per column."""
    w, h = 5 * k, 8 * k
    nb = h // 8
    out = [0] * (w * nb)
    for x in range(5):
        for r in range(8):
            if not (glyph[x] >> r) & 1:
                continue
            for dx in range(k):
                X = x * k + dx
                for dy in range(k):
                    Y = r * k + dy
                    out[X * nb + (Y // 8)] |= 1 << (Y % 8)
    return out


def main():
    k = int(sys.argv[1]) if len(sys.argv) > 1 else 2
    if k < 2 or k > 4:
        sys.exit("scale factor must be 2..4 (128x64 panel)")
    w, h = 5 * k, 8 * k
    per = w * (h // 8)
    gl = load()
    name = "oled_font%dx%d" % (w, h)
    o = sys.stdout.write
    o("/* SPDX-License-Identifier: Apache-2.0 */\n/*\n"
      " * GENERATED by samples/oled_status/tools/gen_font_scaled.py %d -- do not edit.\n"
      " * Source: src/font5x8.c, pixel-doubled %dx.  Public domain font (X11 misc-fixed).\n"
      " * %dx%d cells, CFB_FONT_MONO_VPACKED, LSB first, ASCII 0x20..0x7e.\n"
      " * On a 128x64 panel: %d characters per line, %d lines.\n */\n"
      % (k, k, w, h, 128 // w, 64 // h))
    o("#include <zephyr/display/cfb.h>\n\n")
    o("static const uint8_t %s[95][%d] = {\n" % (name, per))
    for i, g in enumerate(gl):
        b = ", ".join("0x%02x" % v for v in scale(g, k))
        c = chr(32 + i)
        o("\t{%s},  /* 0x%02x %s */\n" % (b, 32 + i, c if c.isprintable() and c != " " else ""))
    o("};\n\n")
    o("FONT_ENTRY_DEFINE(%s_entry, %d, %d, CFB_FONT_MONO_VPACKED, %s, 32, 126);\n"
      % (name, w, h, name))


if __name__ == "__main__":
    main()
