#!/usr/bin/env python3
"""Write ln_golden.c from the reference kernels, so the golden is never hand-transcribed.

    fpga/pynq-z2/rtl_study/roccmoon/ln_lane/gen_golden.py

Extracts _Q16_NORM_CORE and the reference_impl of layernorm_pc_s8, layernorm_s16_s8 and
groupnorm_s16 verbatim from zephyr-chipyard-sw/modelblaster/pipeline/reference_kernels.py,
and pulls in the curated pext_nl_groupnorm_s16_pext_int_memo.c under a second name so the
testbench can re-check curated == reference on the same data.
"""
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
repo = os.path.abspath(os.path.join(here, "../../../../.."))
src = open(os.path.join(repo, "zephyr-chipyard-sw/modelblaster/pipeline/reference_kernels.py")).read()

core = re.search(r'_Q16_NORM_CORE = r"""(.*?)"""', src, re.S).group(1)

def impl(op):
    i = src.index('op="%s"' % op)
    j = src.index('reference_impl=r"""', i)
    k = src.index('"""', j + len('reference_impl=r"""'))
    body = src[j + len('reference_impl=r"""'):k]
    # the spec builds it as  <prologue> + _Q16_NORM_CORE + <kernel>; keep only the kernel half
    return body.split('\n""" + _Q16_NORM_CORE + r"""\n')[-1]

# in the file the three are written as  r"""...""" + _Q16_NORM_CORE + r"""..."""
def impl2(op):
    i = src.index('op="%s"' % op)
    j = src.index('_Q16_NORM_CORE + r"""', i)
    k = src.index('"""', j + len('_Q16_NORM_CORE + r"""'))
    return src[j + len('_Q16_NORM_CORE + r"""'):k]

out = ['/* GENERATED by ln_lane/gen_golden.py -- do not edit.  The q16 normalisation core and',
       ' * the three reference kernels, verbatim from',
       ' * zephyr-chipyard-sw/modelblaster/pipeline/reference_kernels.py, plus the curated',
       ' * GroupNorm kernel under a second name.  SPDX-License-Identifier: Apache-2.0 */',
       '#include <stddef.h>', '#include <stdint.h>', core]
for op in ("layernorm_pc_s8", "layernorm_s16_s8", "groupnorm_s16"):
    out.append("/* ---- %s, reference_kernels.py ---- */" % op)
    out.append(impl2(op))
out.append('''/* ---- the curated GroupNorm kernel the board build would run, under a second name ---- */
#define kernel_groupnorm_s16 kernel_groupnorm_s16_memo
#include "pext_nl_groupnorm_s16_pext_int_memo.c"
#undef kernel_groupnorm_s16
''')
open(os.path.join(here, "ln_golden.c"), "w").write("\n".join(out))
print("wrote ln_golden.c (%d bytes)" % os.path.getsize(os.path.join(here, "ln_golden.c")))
