/* GENERATED by ln_lane/gen_golden.py -- do not edit.  The q16 normalisation core and
 * the three reference kernels, verbatim from
 * zephyr-chipyard-sw/modelblaster/pipeline/reference_kernels.py, plus the curated
 * GroupNorm kernel under a second name.  SPDX-License-Identifier: Apache-2.0 */
#include <stddef.h>
#include <stdint.h>

#ifndef MB_Q16_NORM_CORE
#define MB_Q16_NORM_CORE
/* floor(sqrt(v)), bit by bit */
static inline unsigned __int128 mb_q16_isqrt128(unsigned __int128 v) {
    unsigned __int128 r = 0, bit = (unsigned __int128)1 << 126;
    while (bit > v) bit >>= 2;
    while (bit) {
        if (v >= r + bit) { v -= r + bit; r = (r >> 1) + bit; }
        else r >>= 1;
        bit >>= 2;
    }
    return r;
}
/* R = isqrt(floor(2^120 / V)), V = K*Q - S^2 + eps_q > 0 */
static inline int64_t mb_q16_norm_r(int64_t K, int64_t S, __int128 Q, int64_t eps_q) {
    __int128 V = (__int128)K * Q - (__int128)S * (__int128)S + (__int128)eps_q;
    return (int64_t)mb_q16_isqrt128(((unsigned __int128)1 << 120) / (unsigned __int128)V);
}
/* t = floor((K*u - S) * R / 2^44), then out = floor((t*g + b*2^16 + 2^31) / 2^32) */
static inline int64_t mb_q16_norm_out(int64_t K, int64_t u, int64_t S, int64_t R,
                                      int64_t g, int64_t b) {
    __int128 d = (__int128)K * (__int128)u - (__int128)S;
    int64_t t = (int64_t)((d * (__int128)R) >> 44);
    return (t * g + b * 65536 + ((int64_t)1 << 31)) >> 32;
}
#endif

/* ---- layernorm_pc_s8, reference_kernels.py ---- */

void kernel_layernorm_pc_s8(const int8_t *input, const int32_t *umul, const int64_t *gmul,
                            const int64_t *badd, int8_t *output, int M, int K, int64_t eps_q) {
    for (int m = 0; m < M; m++) {
        const int8_t *x = input + (size_t)m * (size_t)K;
        int8_t *y = output + (size_t)m * (size_t)K;
        int64_t S = 0;
        __int128 Q = 0;
        for (int k = 0; k < K; k++) {
            const int64_t u = (int64_t)x[k] * (int64_t)umul[k];
            S += u;
            Q += (__int128)u * (__int128)u;
        }
        const int64_t R = mb_q16_norm_r(K, S, Q, eps_q);
        for (int k = 0; k < K; k++) {
            int64_t v = mb_q16_norm_out(K, (int64_t)x[k] * (int64_t)umul[k], S, R, gmul[k], badd[k]);
            if (v < -128) v = -128;
            if (v > 127) v = 127;
            y[k] = (int8_t)v;
        }
    }
}

/* ---- layernorm_s16_s8, reference_kernels.py ---- */

void kernel_layernorm_s16_s8(const int16_t *input, const int64_t *gmul, const int64_t *badd,
                             int8_t *output, int M, int K, int64_t eps_q) {
    for (int m = 0; m < M; m++) {
        const int16_t *x = input + (size_t)m * (size_t)K;
        int8_t *y = output + (size_t)m * (size_t)K;
        int64_t S = 0;
        __int128 Q = 0;
        for (int k = 0; k < K; k++) {
            S += x[k];
            Q += (int64_t)x[k] * (int64_t)x[k];
        }
        const int64_t R = mb_q16_norm_r(K, S, Q, eps_q);
        for (int k = 0; k < K; k++) {
            int64_t v = mb_q16_norm_out(K, x[k], S, R, gmul[k], badd[k]);
            if (v < -128) v = -128;
            if (v > 127) v = 127;
            y[k] = (int8_t)v;
        }
    }
}

/* ---- groupnorm_s16, reference_kernels.py ---- */

void kernel_groupnorm_s16(const int16_t *input, const int64_t *gmul, const int64_t *badd,
                          int16_t *output, int N, int C, int HW, int64_t eps_q) {
    const int64_t K = (int64_t)C * (int64_t)HW;
    for (int n = 0; n < N; n++) {
        const int16_t *x = input + (size_t)n * (size_t)K;
        int16_t *y = output + (size_t)n * (size_t)K;
        int64_t S = 0;
        __int128 Q = 0;
        for (int64_t i = 0; i < K; i++) {
            S += x[i];
            Q += (int64_t)x[i] * (int64_t)x[i];
        }
        const int64_t R = mb_q16_norm_r(K, S, Q, eps_q);
        for (int c = 0; c < C; c++) {
            for (int p = 0; p < HW; p++) {
                const size_t i = (size_t)c * (size_t)HW + (size_t)p;
                int64_t v = mb_q16_norm_out(K, x[i], S, R, gmul[c], badd[c]);
                if (v < -32768) v = -32768;
                if (v > 32767) v = 32767;
                y[i] = (int16_t)v;
            }
        }
    }
}

/* ---- the curated GroupNorm kernel the board build would run, under a second name ---- */
#define kernel_groupnorm_s16 kernel_groupnorm_s16_memo
#include "pext_nl_groupnorm_s16_pext_int_memo.c"
#undef kernel_groupnorm_s16
