#!/usr/bin/env bash
# Lab B26 -- Moonshine Tiny's speech ENCODER, code-generated by ModelBlaster and run end to
# end on hart 0: the measured software baseline an accelerator is compared against.
#
#   ./scripts/50_rocket_moonshine_enc.sh --build-only                         # 1. no board
#   scripts/with_board.sh ./scripts/50_rocket_moonshine_enc.sh --board-only   # 2. board only
#
# Two steps so the board lock is never held across a build (codegen, host gates, the
# fidelity check and a dozen Zephyr images); --board-only reuses out/<name>/ as step 1 left
# it, --report-only re-parses what the board step collected.
#
# WHAT RUNS.  UsefulSensors/moonshine-tiny @ 390624ed, the encoder only, 4.0 s of 16 kHz
# speech (64,000 samples -> 165 frames), int8 through ModelBlaster's FX path with
# patches/0100 (tanh_s8, groupnorm_s8, rope_s8, multi-head attention as matmul_b_s8,
# view/permute).  The port is fpga/pynq-z2/modelblaster/moonshine/moonshine_enc.py and is
# bit-identical to transformers' MoonshineEncoder in float32.
#
# SOFTWARE BASELINES (--variants), one IR, same silicon, same session:
#   nl       pext_nl AS REGISTERED before patches/0100's kernels: MBP conv/linear, integer
#            GELU / layer norm / softmax, and the ops 0100 adds to the IR at their float
#            REFERENCE -- tanh_s8, groupnorm_s8, rope_s8 and add_s8 pinned with
#            --keep-reference-ops.  (matmul_b_s8 is not elementwise and takes its curated
#            DOT8 kernel in both.)
#   ew       plus the integer / memo elementwise kernels: tanh memo table (bit-exact), integer
#            add and rope (bit-exact, fpga/pynq-z2/sw/fexact32.h), integer group norm (1 LSB).
#   nl_eng   nl and ew with ModelBlaster target `roccmoon` (patches/0102): linear_s8 and the
#   ew_eng   1-D stem conv2d_s8 on the decoupled RoCC engine of bitstream 0x5A5A0010.  Same
#            IR (checked); the host-C golden must be BYTE-IDENTICAL to the twin's (checked:
#            on the host the engine kernels are the curated MBP fallback).  Run them with
#            --bit/--magic/--board/--runner for that bitstream and ROCCMOON_ACCEPTED=<md5>.
#   *_smx    any of the above with softmax_s8 taken by `pext_int_memo` (patches/0104): the same
#            kernel as pext_int_row with its exponential memoised, BIT-EXACT, so the host-C
#            golden must be byte-identical to the twin without _smx (checked).  One lever,
#            measured on its own (ROCC_DECOUPLED.md 8.14, T1).  Selected by generating from a
#            copy of the curated tree without pext_int_row's file: the reference backend's
#            curated probe walks spec.algorithms in order and does not apply --algorithms.
#   *_smx2   as _smx with `pext_int_memo2` (patches/0106): the memo's multiplies priced for the
#            big core's iterative multiplier, and a per-row zero cutoff.  Bit-exact the same way.
#   *_nhwc   (after _smx/_smx2 if both) the IR rewritten by pipeline/assign_layouts.py with
#            moonshine/layout_hints_moonshine.json: the stem (conv1, tanh, GroupNorm, conv2, GELU,
#            conv3, GELU) becomes an NHWC island (patches/0105), so the engine's convolutions
#            neither gather nor transpose.  Its host-C golden must be byte-identical to the twin
#            without _nhwc (checked here, not by check_moonshine.py, whose per-dispatch gates
#            read the NCHW IR).  T1 lever 2 (ROCC_DECOUPLED.md 8.14).
# ROCC_DECOUPLED.md 7.3 priced nl and nl+ew; this lab replaces the estimates.
#
# THE CONV KERNEL'S BUFFER LIMITS (images *_bigconv, on by default; --no-bigconv).
# pext_patch_dot8 takes its DOT8 path only when IC*KH <= MB_PEXT_CONV_MAXROWS (512) and
# processes output channels in blocks that fit MB_PEXT_CONV_WBYTES (8 KB) of repacked
# weights, re-gathering the patch per block.  Sized for LeNet and DroNet: Moonshine's conv3
# (IC*KH = 576) silently runs the scalar reference (kernel_picks.json still says
# pext_patch_dot8) and conv2 re-gathers every 4 output channels.  enc_ew_bigconv and
# stem_{w,h}_bigconv are the SAME generated C built with -DMB_PEXT_CONV_MAXROWS=2048
# -DMB_PEXT_CONV_WBYTES=2097152: the kernel's own compile-time knobs, same bit-exact answer.
#
# THE LAYOUT LEVER ON MOONSHINE'S OWN STEM (--stems): conv1..conv3 + tanh + GroupNorm + GELU
# alone, time on W ((1, k) kernels over [N,C,1,T], what the encoder uses) against time on H
# ((k, 1) over [N,C,T,1]).  Same int8 tensors either way.
#
# A CONTROL IMAGE (ctrl_ffn, on by default; --no-control) runs first and last: ModelBlaster's
# ffn_block at pext_nl, the block Lab B19 ran on this board.  A silent board is then
# recognisable as a silent board rather than as a property of the model.  And while every
# image runs, Rocket's RAM is read from the PS (moonshine/peek_ram.py): kernel-init flag, SMP
# hand-shake flags, the harness's `big` struct and the per-dispatch cycle records -- evidence
# that does not depend on the UART (--no-peek skips the RAM reads).
#
# THE GOLDEN.  The Python int8 golden is simulated the way the REFERENCE kernels compute
# (MB_INT8_GOLDEN_C_FLOAT=1) and host gate (a) proves the generated C with reference kernels
# reproduces it at every dispatch.  Every variant contains numeric_drift kernels (patches/
# 0060's integer GELU / layer norm / softmax; ew's integer group norm), so each image is baked
# with ITS OWN host-C golden -- the same generated C compiled for the host against pext.h's
# software model of MBP -- and the board must match that exactly.
#
# CALIBRATION.  16 real speech windows, evenly spaced across the utterances
# (moonshine_enc.speech_split), MB_INT8_GELU_AWARE_RANGES=1 (patches/0100; lossless for the
# GELU consumer).  host_fidelity.py measures what int8 does to transcripts.
#
# Produces out/<name>/{run.json,report.txt,host_gates.json,host_fidelity.json,...}.
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/bitstream_id.sh"

NAME="rocket_moonshine_enc"
VARIANTS="nl ew"
STEMS="w h"
TARGET="pext_nl"
NCAL=16
# THE AUDIO WINDOW, in seconds.  ModelBlaster's IR is built for one shape, so a rung of the shape
# ladder (ROCC_DECOUPLED.md s8.15.11) is this lab run again at another window over the same weights.
# The port derives every shape from it (moonshine_enc.py, MOONSHINE_WINDOW_S); 4.0 is what every
# measurement before 2026-09-17 used, and RTF is always computed against THIS window, so a rung's
# RTF is its cycles over its own audio.
WINDOW_S_OPT=4.0
FRAMES=""
ITERS=1
BOARD="chipyard_pynqz1_mic"
BIT="$IISWC_ROOT/fpga/pynq-z2/build_rocket_mic_z1/pynqz1_rocket_mic.bit"
RUNNER="run_rocket_mic.py"
SAMPLE="$IISWC_ROOT/samples/modelblaster_pext"
WANT_MAGIC="0x5A5A0005"
FCLK_CORE=34.4828
LOAD_BIT=1
DO_BOARD=1
HOST_GATES=1
FIDELITY=1
BOARD_ONLY=0
REPORT_ONLY=0
BIGCONV=1
CONTROL=1
ONLY_MODELS=""
RELOAD_PER_MODEL=1
PEEK_RAM=1
MAXREAD_ENC=5400
MAXREAD_SMALL=300
BIGCONV_CFLAGS="-DMB_PEXT_CONV_MAXROWS=2048 -DMB_PEXT_CONV_WBYTES=2097152"
# --kernel-cflags: appended to EVERY image's kernels.c flags (recorded in kernel_cflags.txt).
# For code-placement control (ROCC_DECOUPLED.md 8.15): e.g. -falign-loops=4 puts every loop
# head of the kernel TU -- the engine runtime and mbxr.c included -- on a 4-byte boundary.
KCF_ALL=""
while [ $# -gt 0 ]; do
  case "$1" in
    --name) NAME="${2:?}"; shift 2 ;;
    --variants) VARIANTS="${2:?}"; shift 2 ;;
    --stems) STEMS="${2}"; shift 2 ;;
    --iters) ITERS="${2:?}"; shift 2 ;;
    --board) BOARD="${2:?}"; shift 2 ;;
    --bit) BIT="${2:?}"; shift 2 ;;
    --magic) WANT_MAGIC="${2:?}"; shift 2 ;;
    --runner) RUNNER="${2:?}"; shift 2 ;;
    --no-bitstream) LOAD_BIT=0; shift ;;
    --build-only) DO_BOARD=0; shift ;;
    --board-only) BOARD_ONLY=1; shift ;;
    --report-only) BOARD_ONLY=1; REPORT_ONLY=1; shift ;;
    --models) ONLY_MODELS="${2:?}"; shift 2 ;;
    --no-bigconv) BIGCONV=0; shift ;;
    --kernel-cflags) KCF_ALL="${2}"; shift 2 ;;
    --window-s) WINDOW_S_OPT="${2:?}"; shift 2 ;;
    --no-control) CONTROL=0; shift ;;
    --no-reload) RELOAD_PER_MODEL=0; shift ;;
    --no-peek) PEEK_RAM=0; shift ;;
    --maxread-enc) MAXREAD_ENC="${2:?}"; shift 2 ;;
    --skip-host-gates) HOST_GATES=0; shift ;;
    --skip-fidelity) FIDELITY=0; shift ;;
    -h|--help) sed -n '2,72p' "$0"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

# Engine bitstreams are validated by their own lab, not added to lib/bitstream_id.sh's shared
# list (the pattern of scripts/51_rocket_roccmoon.sh and 43_rocket_bwlab.sh).
ROCCMOON_ACCEPTED="${ROCCMOON_ACCEPTED:-}"
BIT_ACCEPTED="${BIT_ACCEPTED:-} $ROCCMOON_ACCEPTED"

MB="$ZCS/modelblaster"
MOON="$IISWC_ROOT/fpga/pynq-z2/modelblaster/moonshine"
KERNELS="$IISWC_ROOT/fpga/pynq-z2/modelblaster/kernels"
[ -d "$MB/pipeline" ] || die "no modelblaster checkout at $MB"
# THE ENGINE'S OUTSTANDING CAP IS A PROPERTY OF THE BITSTREAM'S L2, not of the image.  The driver
# asks for 4 by default (mbxr_rt.h, MBXR_RT_CAP), which is right only where patch 0092 is in the
# L2: Lab B25's sweep reads 7.342 B/cycle at cap 4 on 0x5A5A0028 and DIPS at 4 on the builds
# without it.  So this lab keys the flag off the MAGIC it was told to run against, and an image
# built for one bitstream carries the cap that bitstream wants.  MBXR_CAP=<n> overrides.
case "${MBXR_CAP_OVERRIDE:-}${WANT_MAGIC}" in
  0x5A5A0028|0x5A5A0013) CAP_CFLAG="-DMBXR_RT_CAP=4" ;;
  [1-4]*)                CAP_CFLAG="-DMBXR_RT_CAP=${MBXR_CAP_OVERRIDE}" ;;
  *)                     CAP_CFLAG="-DMBXR_RT_CAP=3" ;;
esac
SSH=(ssh -o BatchMode=yes -o StrictHostKeyChecking=no "$PYNQ_HOST")
RUN="$IISWC_OUT/$NAME"
if [ "$BOARD_ONLY" -eq 0 ]; then rm -rf "$RUN"; mkdir -p "$RUN"; fi
export PYTHONPATH="$ZCS${PYTHONPATH:+:$PYTHONPATH}"
export CPATH="$IISWC_ROOT/fpga/pynq-z2/sw${CPATH:+:$CPATH}"
export IISWC_ROOT
# Every child that imports the port needs this rung's window: the fidelity check sizes its
# output from me.T, hostrun builds against the generated C, and check_moonshine reads the IR.
export MOONSHINE_WINDOW_S="$WINDOW_S_OPT"
export MOONSHINE_DIR="${MOONSHINE_DIR:-$IISWC_OUT/moonshine}"
PY="$ZCS/tools/miniforge3/envs/zephyr/bin/python"; [ -x "$PY" ] || PY=python
NM=$(find "${ZEPHYR_SDK_INSTALL_DIR:-$ZCS/tools-manual}" -name 'riscv64-zephyr-elf-nm' 2>/dev/null | head -1)
OBJDUMP=$(find "${ZEPHYR_SDK_INSTALL_DIR:-$ZCS/tools-manual}" -name 'riscv64-zephyr-elf-objdump' 2>/dev/null | head -1)

vbase () { local b="${1%_perm}"; b="${b%_nhwc}"; b="${b%_smx2}"; b="${b%_smx}"; echo "$b"; }
vtarget () { case "$(vbase "$1")" in *_eng) echo roccmoon ;; *) echo "$TARGET" ;; esac; }
vkind () { local b; b="$(vbase "$1")"; echo "${b%_eng}"; }
vir () { case "${1%_perm}" in *_nhwc) echo "$RUN/enc/ir_nhwc" ;; *) echo "$RUN/enc/ir" ;; esac; }
# *_perm: the variant's curated tree plus permute4_s8 pext_block (patches/0107), which lives in
# kernels_t1 so that no other build picks it up.
vcurated () { case "$1" in *_smx2_perm|*_smx2_nhwc_perm) echo "$RUN/kernels_smx2_perm" ;;
  *_smx2|*_smx2_nhwc) echo "$RUN/kernels_smx2" ;; *_smx|*_smx_nhwc) echo "$RUN/kernels_smx" ;; *) echo "$KERNELS" ;; esac; }

MODELS=""
[ "$CONTROL" -eq 1 ] && MODELS="ctrl_ffn"
for V in $VARIANTS; do MODELS="$MODELS enc_$V"; done
if [ "$BIGCONV" -eq 1 ]; then case " $VARIANTS " in *" ew "*) MODELS="$MODELS enc_ew_bigconv" ;; esac; fi
if [ "$BIGCONV" -eq 1 ]; then case " $VARIANTS " in *" ew_smx "*) MODELS="$MODELS enc_ew_smx_bigconv" ;; esac; fi
if [ "$BIGCONV" -eq 1 ]; then case " $VARIANTS " in *" ew_smx2 "*) MODELS="$MODELS enc_ew_smx2_bigconv" ;; esac; fi
# The best software encoder with no engine in it: every measured software lever AND the conv
# kernel's buffers.  Without this the no-engine row is 4.3 G cycles of conv buffer limit
# (8.15.9's table), which is not what hart 0 can do.
if [ "$BIGCONV" -eq 1 ]; then case " $VARIANTS " in *" ew_smx2_nhwc_perm "*) MODELS="$MODELS enc_ew_smx2_nhwc_perm_bigconv" ;; esac; fi
for L in $STEMS; do MODELS="$MODELS stem_$L"; done
if [ "$BIGCONV" -eq 1 ]; then for L in $STEMS; do MODELS="$MODELS stem_${L}_bigconv"; done; fi
[ "$CONTROL" -eq 1 ] && MODELS="$MODELS ctrl_ffn_end"
[ -n "$ONLY_MODELS" ] && MODELS="$ONLY_MODELS"

if [ "$BOARD_ONLY" -eq 1 ]; then
  [ "$REPORT_ONLY" -eq 1 ] || for M in $MODELS; do need_file "$RUN/$M/zephyr.bin" "run --build-only first"; done
  info "--board-only: using the images in $RUN"
else
step "0/5  checkpoint, speech, and patches"
"$MOON/fetch_moonshine.sh" > "$RUN/fetch.log" 2>&1 || { cat "$RUN/fetch.log"; die "fetch_moonshine.sh failed"; }
# 0009 and 0060 exactly as scripts/39_rocket_xformer_cost.sh applies them (0060 edits lines
# 0009 added, so 0009 cannot be reverse-checked on its own once both are in).  0100 and 0102
# are checked both ways: each must either apply or be already applied, never half.
for P in 0009-modelblaster-pext-backend 0060-modelblaster-pext-pc-and-int-nonlin; do
  F="$IISWC_ROOT/patches/$P.patch"
  if git -C "$MB" apply --check "$F" >/dev/null 2>&1; then run git -C "$MB" apply "$F"; fi
done
# The later patches edit hunks inside earlier ones (0105 inside 0100's groupnorm_s8), so an
# earlier patch no longer reverse-applies on its own once a later one is in.  Check the stack
# from the top: if the LAST one reverse-applies, the stack below it is in (scripts/02 proves
# the whole stack reconstructs); otherwise apply each in order.
MB_STACK="0100-modelblaster-moonshine-ops 0102-modelblaster-roccmoon-backend 0103-modelblaster-q16-lowering 0104-modelblaster-softmax-memo 0105-modelblaster-moonshine-stem-nhwc 0106-modelblaster-softmax-memo2 0107-modelblaster-permute-block"
MB_TOP="$IISWC_ROOT/patches/${MB_STACK##* }.patch"
if git -C "$MB" apply --reverse --check "$MB_TOP" >/dev/null 2>&1; then
  info "patch stack through ${MB_STACK##* } already applied"
else
  for P in $MB_STACK; do
    F="$IISWC_ROOT/patches/$P.patch"
    if git -C "$MB" apply --check "$F" >/dev/null 2>&1; then run git -C "$MB" apply "$F"
    elif git -C "$MB" apply --reverse --check "$F" >/dev/null 2>&1; then info "$P already applied"
    else die "patches/$P neither applies nor is already applied to $MB"; fi
  done
fi

step "1/5  codegen  (encoder: $VARIANTS; stems: ${STEMS:-none}; control: $CONTROL)"
extract () {  # model out_dir fusion_target ncal [env...]
  local model="$1" out="$2" ft="$3" ncal="$4"; shift 4
  ( cd "$ZCS" && env "$@" "$PY" -m modelblaster.pipeline.extract_graph \
      --model "$model" --out-dir "$out" --quant int8 --num-calibration "$ncal" \
      --fusion-target "$ft" ) >> "$RUN/codegen.log" 2>&1 || { tail -30 "$RUN/codegen.log"; die "extract_graph ($model) failed"; }
}
MOON_ENV=(MB_INT8_GELU_AWARE_RANGES=1 MB_INT8_GOLDEN_C_FLOAT=1 MOONSHINE_WINDOW_S="$WINDOW_S_OPT")
codegen () {  # ir_dir gen_dir kind(ref|nl|ew) target [curated_dir]
  local ir="$1" gen="$2" kind="$3" tgt="$4" cur="${5:-$KERNELS}" extra=()
  mkdir -p "$gen"
  ( cd "$ZCS" && "$PY" -m modelblaster.pipeline.generate_skeleton \
      --ir "$ir/graph.json" --weights "$ir/weights.npz" --io "$ir/io.npz" \
      --out-dir "$gen" --backend "$tgt" ) >> "$RUN/codegen.log" 2>&1 || die "generate_skeleton failed ($gen)"
  case "$kind" in
    ref) ;;
    nl)  extra=(--global-curated-dir "$cur" --keep-reference-ops tanh_s8,groupnorm_s8,rope_s8,add_s8,mul_s8) ;;
    ew)  extra=(--global-curated-dir "$cur") ;;
  esac
  ( cd "$ZCS" && "$PY" -m modelblaster.pipeline.generate_kernels \
      --ir "$ir/graph.json" --out-dir "$gen" --backend reference --target "$tgt" \
      --quant int8 --io "$ir/io.npz" --repo-root "$MB" --build-dir "$gen.kverify" \
      --harness-dir "$MB/harness" --cache-dir "$gen.cache" --algorithms all "${extra[@]}" ) \
      >> "$RUN/codegen.log" 2>&1 || { tail -20 "$RUN/codegen.log"; die "generate_kernels failed ($gen)"; }
  need_file "$gen/kernels.c" "codegen produced no kernels ($gen)"
  cp "$gen/test_golden.bin" "$gen/test_golden_python.bin"
}
extract moonshine_enc "$RUN/enc/ir" "$TARGET" "$NCAL" "${MOON_ENV[@]}" MB_INT8_DUMP_ACTIVATIONS="$RUN/enc/ir/acts.npz"
case " $VARIANTS " in
  *_eng*)
    # The IR is target-independent except for extended fusion, which fires on no target
    # (extract_graph._FUSION_SAFE_TARGETS is empty).  Checked, not assumed.
    extract moonshine_enc "$RUN/enc/ir_roccmoon" roccmoon "$NCAL" "${MOON_ENV[@]}"
    for f in graph.json io.npz weights.npz; do
      cmp -s "$RUN/enc/ir/$f" "$RUN/enc/ir_roccmoon/$f" || die "extract_graph --fusion-target roccmoon changed $f"
    done
    info "IR identical for --fusion-target $TARGET and roccmoon (graph.json, io.npz, weights.npz)" ;;
esac
codegen "$RUN/enc/ir" "$RUN/enc/gen_ref" ref "$TARGET"
case " $VARIANTS " in
  *_smx*)
    rm -rf "$RUN/kernels_smx" "$RUN/kernels_smx2"; cp -r "$KERNELS" "$RUN/kernels_smx"
    rm -f "$RUN/kernels_smx/pext_nl/pext_nl_softmax_s8_pext_int_row.c"
    need_file "$RUN/kernels_smx/pext_nl/pext_nl_softmax_s8_pext_int_memo.c" "no pext_int_memo kernel"
    cp -r "$RUN/kernels_smx" "$RUN/kernels_smx2"
    rm -f "$RUN/kernels_smx2/pext_nl/pext_nl_softmax_s8_pext_int_memo.c"
    need_file "$RUN/kernels_smx2/pext_nl/pext_nl_softmax_s8_pext_int_memo2.c" "no pext_int_memo2 kernel"
    case " $VARIANTS " in
      *_perm*)
        rm -rf "$RUN/kernels_smx2_perm"; cp -r "$RUN/kernels_smx2" "$RUN/kernels_smx2_perm"
        cp "$IISWC_ROOT/fpga/pynq-z2/modelblaster/kernels_t1/pext_nl/pext_nl_permute4_s8_pext_block.c" \
           "$RUN/kernels_smx2_perm/pext_nl/" ;;
    esac ;;
esac
case " $VARIANTS " in
  *_nhwc*)
    mkdir -p "$RUN/enc/ir_nhwc"
    cp "$RUN/enc/ir/weights.npz" "$RUN/enc/ir/io.npz" "$RUN/enc/ir_nhwc/"
    ( cd "$ZCS" && "$PY" -m modelblaster.pipeline.assign_layouts "$RUN/enc/ir/graph.json" \
        "$RUN/enc/ir_nhwc/graph.json" --hint "$MOON/layout_hints_moonshine.json" --model moonshine_enc ) \
      >> "$RUN/codegen.log" 2>&1 || { tail -20 "$RUN/codegen.log"; die "assign_layouts failed"; }
    grep "policy=islands" "$RUN/codegen.log" | tail -1 | sed 's/^/    /' ;;
esac
for V in $VARIANTS; do codegen "$(vir "$V")" "$RUN/enc_$V/gen" "$(vkind "$V")" "$(vtarget "$V")" "$(vcurated "$V")"; done
for L in $STEMS; do
  extract "moonshine_stem_$L" "$RUN/stem_$L/ir" "$TARGET" "$NCAL" "${MOON_ENV[@]}"
  codegen "$RUN/stem_$L/ir" "$RUN/stem_$L/gen" ew "$TARGET"
done
if [ "$CONTROL" -eq 1 ]; then
  # Lab B19's own extraction of ffn_block (one calibration sample), at pext_nl.
  extract ffn_block "$RUN/ctrl_ffn/ir" "$TARGET" 1
  codegen "$RUN/ctrl_ffn/ir" "$RUN/ctrl_ffn/gen" ew "$TARGET"
fi
# THE RUNG'S OWN T, and the gate that the IR really has it.  The port derives T from the window;
# this asks the port, then checks the extracted graph agrees -- a rung whose IR was built at the
# wrong window would otherwise be measured as if it were 4 s and read a flattering RTF.
FRAMES=$( cd "$MOON" && MOONSHINE_WINDOW_S="$WINDOW_S_OPT" "$PY" -c "import moonshine_enc as me; print(me.T)" )
[ -n "$FRAMES" ] || die "could not derive the frame count for a ${WINDOW_S_OPT} s window"
"$PY" - "$RUN/enc/ir/graph.json" "$FRAMES" "$WINDOW_S_OPT" <<'PYT' || die "the extracted IR is not a ${WINDOW_S_OPT} s window"
import json, sys
g = json.load(open(sys.argv[1])); T = int(sys.argv[2])
# graph.json: "ops" carries the shapes, "dispatches" is a list of indices into it.
ms = sorted({o["shape"]["M"] for o in g["ops"]
             if o.get("op") in ("linear_s8", "linear_s8_pc") and "M" in o.get("shape", {})})
if not ms:
    sys.exit("no linear dispatches in the IR")
if max(ms) != T:
    sys.exit("the IR's longest linear is M = %d, but a %s s window is T = %d" % (max(ms), sys.argv[3], T))
print("    window %s s -> T = %d frames; the IR's linear dispatches are M in %s" % (sys.argv[3], T, ms))
PYT
"$PY" - "$RUN" <<'PY'
import json, os, sys, collections, glob
run = sys.argv[1]
g = json.load(open(os.path.join(run, "enc/ir/graph.json")))
c = collections.Counter(o["op"] for o in g["ops"])
print("    encoder IR: %d ops, %d dispatches: %s" % (len(g["ops"]), len(g["dispatches"]), dict(c)))
for p in sorted(glob.glob(os.path.join(run, "*/gen/kernel_picks.json"))):
    d = p.split(os.sep)[-3]
    picks = json.load(open(p))["picks"]
    print("    %-9s picks: %s" % (d, {k: (v.get("algorithm") or v["source"]) for k, v in picks.items()}))
PY

step "2/5  host gates (no board)"
GATE_ARGS=()
for V in $VARIANTS; do case "$V" in *_nhwc|*_perm) ;; *) GATE_ARGS+=(--variant "$V:$RUN/enc_$V/gen") ;; esac; done
STRESS=(); [ "$HOST_GATES" -eq 1 ] || STRESS=(--skip-stress)
( cd "$MOON" && "$PY" check_moonshine.py --ir "$RUN/enc/ir" --acts "$RUN/enc/ir/acts.npz" \
    --ref-gen "$RUN/enc/gen_ref" "${GATE_ARGS[@]}" --workdir "$RUN/host" "${STRESS[@]}" \
    --json "$RUN/host_gates.json" ) > "$RUN/host_gates.log" 2>&1 \
  || { tail -40 "$RUN/host_gates.log"; die "host gates failed to run"; }
grep -E "^\(|dispatches, every|PASS|FAIL|mismatches|output vs" "$RUN/host_gates.log" | sed 's/^/    /' | head -70
# The NHWC variants: whole-model host-C output, byte-identical to the NCHW twin's.
for V in $VARIANTS; do
  case "$V" in
    *_nhwc)
      TW="${V%_nhwc}"
      ( cd "$MOON" && "$PY" -c "
import hostrun, numpy as np, sys
g, wd, out = sys.argv[1], sys.argv[2], sys.argv[3]
exe = hostrun.build(g, wd)
d = hostrun.dump(exe, g, wd + '/dump.bin')
d['__output__'].astype(np.int8).tofile(out)
" "$RUN/enc_$V/gen" "$RUN/host/$V" "$RUN/host/host_c_golden_$V.bin" ) >> "$RUN/host_gates.log" 2>&1 \
        || die "$V: host run failed"
      [ -f "$RUN/host/host_c_golden_$TW.bin" ] || die "$V: twin $TW not in this run"
      cmp -s "$RUN/host/host_c_golden_$V.bin" "$RUN/host/host_c_golden_$TW.bin" \
        || die "$V: host-C golden differs from $TW's -- the NHWC island must be bit-identical"
      info "$V: host-C golden identical to $TW's (NHWC island)" ;;
  esac
done
# The *_perm variants (patches/0107): whole-model host-C output byte-identical to the twin's, and
# permute4_s8 on pext_block with every other pick unchanged.
for V in $VARIANTS; do
  case "$V" in
    *_perm)
      TW="${V%_perm}"
      ( cd "$MOON" && "$PY" -c "
import hostrun, numpy as np, sys
g, wd, out = sys.argv[1], sys.argv[2], sys.argv[3]
exe = hostrun.build(g, wd)
d = hostrun.dump(exe, g, wd + '/dump.bin')
d['__output__'].astype(np.int8).tofile(out)
" "$RUN/enc_$V/gen" "$RUN/host/$V" "$RUN/host/host_c_golden_$V.bin" ) >> "$RUN/host_gates.log" 2>&1 \
        || die "$V: host run failed"
      [ -f "$RUN/host/host_c_golden_$TW.bin" ] || die "$V: twin $TW not in this run"
      cmp -s "$RUN/host/host_c_golden_$V.bin" "$RUN/host/host_c_golden_$TW.bin" \
        || die "$V: host-C golden differs from $TW's -- pext_block must be bit-exact"
      "$PY" -c "
import json, sys
a = json.load(open(sys.argv[1]))['picks']; b = json.load(open(sys.argv[2]))['picks']
alg = lambda v: v.get('algorithm') or v['source']
assert alg(a['permute4_s8']) == 'pext_block', ('permute4_s8 pick', alg(a['permute4_s8']))
diff = {k: (alg(b[k]), alg(a[k])) for k in a if k != 'permute4_s8' and alg(a[k]) != alg(b.get(k, {'source': None}))}
assert not diff, ('other picks changed', diff)
" "$RUN/enc_$V/gen/kernel_picks.json" "$RUN/enc_$TW/gen/kernel_picks.json" || die "$V: kernel picks are not the twin's plus pext_block"
      info "$V: host-C golden identical to $TW's; permute4_s8 on pext_block, every other pick unchanged" ;;
  esac
done
GATE_VARIANTS=""; for V in $VARIANTS; do case "$V" in *_nhwc|*_perm) ;; *) GATE_VARIANTS="$GATE_VARIANTS $V" ;; esac; done
"$PY" - "$RUN" "$GATE_VARIANTS" <<'PY' || die "a host gate FAILED -- see $RUN/host_gates.log"
import json, os, sys
run, variants = sys.argv[1], sys.argv[2].split()
h = json.load(open(os.path.join(run, "host_gates.json")))
bad = []
if not h["a_reference_vs_golden"]["every_dispatch_bit_exact"]:
    bad.append("(a) reference C != Python golden")
exact = {"tanh_s8", "add_s8", "rope_s8", "matmul_b_s8"}
for op, p in h["b3_model_data"]["per_kind"].items():
    if op in exact and p["mismatches"]:
        bad.append(f"(b3) {op} claimed bit_exact, {p['mismatches']} mismatches on model data")
for label in ("full", "san"):
    st = h.get(f"b2_stress_{label}")
    if st is None:
        continue
    for r in st["rows"]:
        if r["test"] != "groupnorm_s8_random" and r["mismatches"]:
            bad.append(f"(b2 {label}) {r['test']}: {r['mismatches']} mismatches")
    if st["returncode"]:
        bad.append(f"(b2 {label}) stress exited {st['returncode']}")
if h.get("b3_model_data_asan_ubsan", {}).get("returncode", 0):
    bad.append("(b3) ASan/UBSan model-data run failed")
for o in h.get("objects", []):
    if o.get("op") in ("add_s8", "mul_s8", "rope_s8", "matmul_b_s8", "groupnorm_s8") and \
            (o.get("softfloat_relocs") or o.get("libm_relocs")):
        bad.append(f"objects: {o['op']} links float: {o}")
eng = {}
for v in variants:
    if f"b4_model_{v}" not in h:
        bad.append(f"(b4) no whole-model run for {v}")
    if v.endswith("_eng"):
        twin = v[:-4]
        a = open(os.path.join(run, "host", f"host_c_golden_{v}.bin"), "rb").read()
        b = open(os.path.join(run, "host", f"host_c_golden_{twin}.bin"), "rb").read() \
            if os.path.exists(os.path.join(run, "host", f"host_c_golden_{twin}.bin")) else None
        picks = json.load(open(os.path.join(run, f"enc_{v}", "gen", "kernel_picks.json")))["picks"]
        pk = {k: picks.get(k, {}).get("algorithm") for k in ("linear_s8", "conv2d_s8")}
        eng[v] = {"twin": twin, "host_c_golden_identical_to_twin": (a == b) if b is not None else None,
                  "picks": pk}
        if b is None:
            bad.append(f"(eng) {v}: twin {twin} not in this run, golden identity unchecked")
        elif a != b:
            bad.append(f"(eng) {v}: host-C golden differs from {twin}'s")
        if any(x != "roccmoon_engine" for x in pk.values()):
            bad.append(f"(eng) {v}: picks {pk}, expected roccmoon_engine")
smx = {}
for v in variants:
    if v.endswith("_smx") or v.endswith("_smx2"):
        twin = v[:v.rindex("_smx")]
        want = "pext_int_memo2" if v.endswith("_smx2") else "pext_int_memo"
        pa = os.path.join(run, "host", f"host_c_golden_{v}.bin")
        pb = os.path.join(run, "host", f"host_c_golden_{twin}.bin")
        a = open(pa, "rb").read()
        b = open(pb, "rb").read() if os.path.exists(pb) else None
        pick = json.load(open(os.path.join(run, f"enc_{v}", "gen", "kernel_picks.json")))["picks"].get("softmax_s8", {}).get("algorithm")
        smx[v] = {"twin": twin, "host_c_golden_identical_to_twin": (a == b) if b is not None else None, "softmax_pick": pick}
        if b is None:
            bad.append(f"(smx) {v}: twin {twin} not in this run, golden identity unchecked")
        elif a != b:
            bad.append(f"(smx) {v}: host-C golden differs from {twin}'s -- {want} must be bit-exact")
        if pick != want:
            bad.append(f"(smx) {v}: softmax pick {pick}, expected {want}")
if smx:
    h["softmax_memo_variants"] = smx
    json.dump(h, open(os.path.join(run, "host_gates.json"), "w"), indent=1, default=str)
    for v, e in smx.items():
        print(f"    {v}: host-C golden identical to {e['twin']}'s: {e['host_c_golden_identical_to_twin']}; softmax {e['softmax_pick']}")
if eng:
    h["engine_variants"] = eng
    json.dump(h, open(os.path.join(run, "host_gates.json"), "w"), indent=1, default=str)
print("    host gates:", "PASS" if not bad else "FAIL: " + "; ".join(bad))
for v, e in eng.items():
    print(f"    {v}: host-C golden identical to {e['twin']}'s: {e['host_c_golden_identical_to_twin']}; picks {e['picks']}")
sys.exit(1 if bad else 0)
PY
# Bake each image's own host-C golden (see the header).
for V in $VARIANTS; do cp "$RUN/host/host_c_golden_$V.bin" "$RUN/enc_$V/gen/test_golden.bin"; done
bake_host_golden () {  # gen workdir label
  ( cd "$MOON" && "$PY" -c "
import hostrun, numpy as np, sys
g = sys.argv[1]
exe = hostrun.build(g, sys.argv[2])
d = hostrun.dump(exe, g, sys.argv[2] + '/dump.bin')
d['__output__'].astype(np.int8).tofile(g + '/test_golden.bin')
py = np.fromfile(g + '/test_golden_python.bin', dtype=np.int8)
print('    %s host-C golden: %d of %d elements differ from the Python golden (max %d)' % (
    sys.argv[3], int((py != d['__output__']).sum()), py.size, int(abs(py.astype(int) - d['__output__']).max())))
" "$1" "$2" "$3" ) 2>/dev/null || die "$3 host run failed"
}
for L in $STEMS; do bake_host_golden "$RUN/stem_$L/gen" "$RUN/host/stem_$L" "stem_$L"; done
[ "$CONTROL" -eq 1 ] && bake_host_golden "$RUN/ctrl_ffn/gen" "$RUN/host/ctrl_ffn" ctrl_ffn
if [ "$FIDELITY" -eq 1 ]; then
  FID_ARGS=(--variant "ref:$RUN/enc/ir:$RUN/enc/gen_ref")
  for V in $VARIANTS; do case "$V" in *_eng|*_smx|*_smx2|*_nhwc) ;; *) FID_ARGS+=(--variant "$V:$RUN/enc/ir:$RUN/enc_$V/gen") ;; esac; done
  # host_fidelity.py imports the port to size its output (me.T * me.D), so it needs this rung's
  # window too -- without it a 3 s model is measured against a 4 s expectation and the reshape fails.
  ( cd "$MOON" && PYTHONPATH="$MOONSHINE_DIR/pylib:$PYTHONPATH" MOONSHINE_WINDOW_S="$WINDOW_S_OPT" \
      "$PY" host_fidelity.py "${FID_ARGS[@]}" \
      --workdir "$RUN/fidelity" --json "$RUN/host_fidelity.json" ) > "$RUN/host_fidelity.log" 2>&1 \
    || { tail -30 "$RUN/host_fidelity.log"; die "host_fidelity.py failed"; }
  grep "^\[" "$RUN/host_fidelity.log" | sed 's/^/    /'
fi

step "2b/5 build the images"
for M in $MODELS; do
  D="$RUN/$M"
  case "$M" in
    ctrl_ffn_end)
      mkdir -p "$D"; ln -sfn "$RUN/ctrl_ffn/gen" "$D/gen"; ln -sfn "$RUN/ctrl_ffn/ir" "$D/ir"
      TGT="$TARGET"; CF_EXTRA="" ;;
    *_bigconv)
      B="${M%_bigconv}"
      mkdir -p "$D"; ln -sfn "$RUN/$B/gen" "$D/gen"; [ -d "$RUN/$B/ir" ] && ln -sfn "$RUN/$B/ir" "$D/ir"
      TGT="$TARGET"; CF_EXTRA="$BIGCONV_CFLAGS" ;;
    enc_*) TGT="$(vtarget "${M#enc_}")"; CF_EXTRA="" ;;
    *) TGT="$TARGET"; CF_EXTRA="" ;;
  esac
  CF=$(cd "$ZCS" && "$PY" -c "
from modelblaster.pipeline import backends
print(' '.join(backends.BACKENDS['$TGT'].kernel_cflags))")
  CF="$CF $CF_EXTRA $KCF_ALL $CAP_CFLAG"
  case "$M" in enc_*) WARM=0 ;; *) WARM=1 ;; esac
  run west build -p always -b "$BOARD" "$SAMPLE" -d "$D/build" -- \
      -DBOARD_ROOT="$IISWC_ROOT" -DMODEL_DIR="$D/gen" -DMB_ITERS="$ITERS" -DMB_WARMUP="$WARM" \
      -DMB_JOIN_TIMEOUT_S=7200 -DMODELBLASTER_KERNEL_CFLAGS="$CF" >> "$RUN/build.log" 2>&1 \
    || { tail -40 "$RUN/build.log"; die "west build failed for $M"; }
  cp "$D/build/zephyr/zephyr.elf" "$D/build/zephyr/zephyr.bin" "$D/"
  echo "$CF" > "$D/kernel_cflags.txt"
  echo "$TGT" > "$D/target.txt"
  echo "$WARM" > "$D/warmup.txt"
  grep -q "^CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=34483\$" "$D/build/zephyr/.config" || die "$M: board clock is not 34483"
  "$OBJDUMP" -d "$D/zephyr.elf" > "$D/dis.txt"
  python3 - "$D/dis.txt" "$M" <<'PYG'
import re, sys
t = open(sys.argv[1]).read()
sf = sorted(set(re.findall(r'<(__(?:add|sub|mul|div|eq|ne|lt|le|gt|ge|unord|float|fix|trunc|extend)[a-z0-9]*(?:sf|df)[0-9a-z]*)>', t)))
lm = sorted(set(re.findall(r'<(expf?|erff?|logf?|sqrtf?|tanhf?|powf?|roundf?)>', t)))
words = re.findall(r'^\s+[0-9a-f]+:\s+([0-9a-f]{8})\s', t, re.M)
c0 = sum(1 for w in words if (int(w, 16) & 0x7f) == 0x0b)
c1 = sum(1 for w in words if (int(w, 16) & 0x7f) == 0x2b)
print("    %-15s custom-0=%d custom-1=%d  soft-float=%s  libm=%s" % (sys.argv[2], c0, c1, ",".join(sf) or "none", ",".join(lm) or "none"))
PYG
  # RAM reads for the board step, resolved from this ELF (moonshine/peek_ram.py)
  "$NM" -S "$D/zephyr.elf" | awk 'NF == 4 {
      if ($4 == "z_sys_post_kernel") print $4 ":" $1 ":1:u8";
      else if ($4 == "riscv_cpu_boot_flag" || $4 == "riscv_cpu_wake_flag") print $4 ":" $1 ":8:u64";
      else if ($4 == "big") print "big:" $1 ":32:big";
      else if ($4 == "records_") print "records_:" $1 ":" strtonum("0x" $2) ":recs";
      else if ($4 ~ /^buf_.*(stem_conv1|_ln)$/) print $4 ":" $1 ":4096:nz";
    }' | tr '\n' ' ' > "$D/peek_spec.txt"
  info "$M image: $(fsize "$D/zephyr.bin")  ($(stat -c %s "$D/zephyr.bin") bytes); RAM end $("$NM" "$D/zephyr.elf" | awk '$3 == "_end" {print "0x" $1}')"
done
[ "$DO_BOARD" -eq 1 ] || { info "--build-only: stopping before the board"; exit 0; }
fi   # BOARD_ONLY

if [ "$REPORT_ONLY" -eq 0 ]; then
step "3/5  load the PL, read the clocks"
"${SSH[@]}" true 2>/dev/null || die "cannot ssh to $PYNQ_HOST"
run scp -q "$IISWC_ROOT/fpga/pynq-z2/host/run_rocket.py" "$IISWC_ROOT/fpga/pynq-z2/host/$RUNNER" \
      "$IISWC_ROOT/fpga/pynq-z2/host/run_rocket_mic.py" \
      "$IISWC_ROOT/fpga/pynq-z2/host/zynq_preflight.py" "$IISWC_ROOT/fpga/pynq-z2/host/console.py" \
      "$IISWC_ROOT/fpga/pynq-z2/host/fclk.py" "$MOON/peek_ram.py" "$PYNQ_HOST:$PYNQ_DIR/"
if [ "$LOAD_BIT" -eq 1 ]; then
  need_file "$BIT" "no bitstream"
  bitstream_identify "$BIT"
  bitstream_gate
  run scp -q "$BIT" "$PYNQ_HOST:$PYNQ_DIR/"
  HOLD_ARGS="--bitstream $(basename "$BIT") --hold"
else
  bitstream_identify ""
  HOLD_ARGS="--no-load --hold"
  RELOAD_PER_MODEL=0
fi
load_pl () {
  "${SSH[@]}" "cd $PYNQ_DIR && echo xilinx | sudo -S bash -lc '$PYNQ_ENV python3 -u $RUNNER $HOLD_ARGS'" \
    >> "$RUN/boot.log" 2>&1 || { tail -20 "$RUN/boot.log"; die "could not load the PL"; }
}
load_pl
grep -q "MAGIC = $WANT_MAGIC" "$RUN/boot.log" || { cat "$RUN/boot.log"; die "wrong bitstream: this lab needs $WANT_MAGIC"; }
"${SSH[@]}" "cd $PYNQ_DIR && echo xilinx | sudo -S python3 fclk.py --expect FCLK0=$FCLK_CORE" \
  > "$RUN/fclk.json" 2> "$RUN/fclk.err" || { cat "$RUN/fclk.json" "$RUN/fclk.err"; die "FCLK0 is not $FCLK_CORE MHz"; }
info "FCLK0..3 read back: $(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(', '.join('%s=%s' % (k, d[k]['mhz']) for k in ('fclk0','fclk1','fclk2','fclk3')))" "$RUN/fclk.json")"
# Two clocks: the board's Linux clock has been ~43.2 M s behind the workstation (it read
# 2025-05-04 on 2026-09-17), so a board_time is not a date.  Record both, and the offset
# measured inside this session (the same record as Lab 51's clocks.json).
H0=$(date +%s.%N); B0=$("${SSH[@]}" "date +%s.%N" 2>/dev/null || echo ""); H1=$(date +%s.%N)
python3 -c "import json,sys,datetime; h0,h1=float(sys.argv[1]),float(sys.argv[2]); b=sys.argv[3]
out={'workstation_time': datetime.datetime.fromtimestamp((h0+h1)/2).astimezone().isoformat(timespec='seconds'),
     'board_time_epoch_s': float(b) if b else None,
     'board_minus_workstation_s': (float(b)-(h0+h1)/2) if b else None, 'ssh_round_trip_s': h1-h0}
json.dump(out, open(sys.argv[4],'w'), indent=1)" "$H0" "$H1" "$B0" "$RUN/clocks.json"

step "4/5  run on hart 0  ($(echo $MODELS | wc -w) images; the PL is reloaded before each: $RELOAD_PER_MODEL)"
first=1
for M in $MODELS; do
  D="$RUN/$M"
  case "$M" in enc_*|stem_*) MAXREAD=$MAXREAD_ENC ;; *) MAXREAD=$MAXREAD_SMALL ;; esac
  if [ "$RELOAD_PER_MODEL" -eq 1 ] && [ "$first" -eq 0 ]; then load_pl; fi
  first=0
  run scp -q "$D/zephyr.bin" "$PYNQ_HOST:$PYNQ_DIR/zephyr.bin"
  PEEK="$(cat "$D/peek_spec.txt" 2>/dev/null)"
  info "$M: running (up to $MAXREAD s; the reader stops at the RESULT line)"
  # Wait on a FILE MARKER (the harness's final RESULT: line) and on the reader's PID.
  "${SSH[@]}" "bash -lc '
    cd $PYNQ_DIR
    echo tty-holders: \$(echo xilinx | sudo -S fuser /dev/ttyPS1 2>/dev/null) consoles: \$(pgrep -fc console.py)
    rm -f console.out
    nohup python3 -u console.py --seconds $MAXREAD > console.out 2>/dev/null &
    CPID=\$!
    sleep 1.5
    echo xilinx | sudo -S bash -lc \"$PYNQ_ENV python3 -u $RUNNER --no-load --elf zephyr.bin\" 2>&1 | grep -v sudo
    sleep 5
    if [ $PEEK_RAM = 1 ]; then echo xilinx | sudo -S python3 peek_ram.py t5 $PEEK 2>/dev/null; fi
    t=5
    while [ \$t -lt $MAXREAD ] && ! grep -q \"^RESULT:\" console.out; do sleep 5; t=\$((t+5)); done
    if [ $PEEK_RAM = 1 ]; then echo xilinx | sudo -S python3 peek_ram.py end $PEEK 2>/dev/null; fi
    sleep 2
    kill \$CPID 2>/dev/null
    wait \$CPID 2>/dev/null
    echo waited=\$t console_bytes=\$(wc -c < console.out)
  '" > "$D/board_side.log" 2>&1 || true
  cat "$D/board_side.log" >> "$RUN/boot.log"
  grep '^{"tag"' "$D/board_side.log" > "$D/peeks.jsonl" || true
  "${SSH[@]}" "cat $PYNQ_DIR/console.out" > "$D/console.txt" 2>/dev/null || true
  cp "$RUN/fclk.json" "$D/fclk.json"
  echo "$BIT_MD5" > "$D/bitstream_md5.txt"
  if grep -q 'MB_PEXT_RUN' "$D/console.txt" 2>/dev/null; then
    info "$M: $(grep -E '^MB_PEXT_RUN' "$D/console.txt" | head -1)"
  else
    warn "$M produced no result ($(grep -oE 'waited=[0-9]+ console_bytes=[0-9]+' "$D/board_side.log")); RAM: $(tail -1 "$D/peeks.jsonl" 2>/dev/null | cut -c1-200)"
  fi
done
fi   # REPORT_ONLY

step "5/5  per-op cycles"
# --board-only skips the codegen that derived it, so ask the port again if it is not set.
FRAMES="${FRAMES:-$( cd "$MOON" && MOONSHINE_WINDOW_S="$WINDOW_S_OPT" "$PY" -c "import moonshine_enc as me; print(me.T)" )}"
export BIT_MD5 BIT_NOTE WANT_MAGIC MB_WINDOW_S="$WINDOW_S_OPT" MB_FRAMES="$FRAMES"
"$PY" - "$RUN" "$MODELS" <<'PY' | tee "$RUN/report.txt"
import hashlib, json, os, re, sys
run, models = sys.argv[1], sys.argv[2].split()
CLK = 34482759.0
WINDOW_S = float(os.environ.get("MB_WINDOW_S", "4.0"))
FRAMES = int(os.environ.get("MB_FRAMES", "165"))


def work(op, s):
    """(MACs, output elements) of one dispatch, from its IR shape."""
    if op in ("linear_s8", "linear_s8_pc"):
        return s["M"] * s["K"] * s["N"], s["M"] * s["N"]
    if op in ("conv2d_s8", "conv2d_s8_pc"):
        return (s["OC"] * s["OH"] * s["OW"] * s["IC"] * s["KH"] * s["KW"],
                s["N"] * s["OC"] * s["OH"] * s["OW"])
    if op == "matmul_b_s8":
        return s["B"] * s["M"] * s["K"] * s["N"], s["B"] * s["M"] * s["N"]
    if op == "permute4_s8":
        return 0, s["d0"] * s["d1"] * s["d2"] * s["d3"]
    if op == "groupnorm_s8":
        return 0, s["N"] * s["C"] * s["H"] * s["W"]
    if op == "rope_s8":
        return 0, s["T"] * s["H"] * s["D"]
    if "n" in s:
        return 0, s["n"]
    if "M" in s and "K" in s:
        return 0, s["M"] * s["K"]
    return 0, 0


def rd(d, f):
    p = os.path.join(d, f)
    return open(p).read().strip() if os.path.exists(p) else None


def model(name):
    d = os.path.join(run, name)
    irp = os.path.join(d, "ir", "graph.json") if os.path.exists(os.path.join(d, "ir", "graph.json")) \
        else os.path.join(run, "enc", "ir", "graph.json")
    g = json.load(open(irp))
    picks = json.load(open(os.path.join(d, "gen", "kernel_picks.json")))["picks"]
    txt = open(os.path.join(d, "console.txt"), errors="replace").read() if os.path.exists(
        os.path.join(d, "console.txt")) else ""
    runl = next((l for l in txt.splitlines() if l.startswith("MB_PEXT_RUN ")), None)
    peeks = [json.loads(l) for l in open(os.path.join(d, "peeks.jsonl"))] if os.path.exists(
        os.path.join(d, "peeks.jsonl")) else []
    img_p = os.path.join(d, "zephyr.bin")
    # TIE THE ARTEFACT TO THE MEASUREMENT BY CHECKSUM.  The bitstream's md5 is already in every
    # row; the IMAGE's was only ever in a sidecar file, so a run.json could not say which bytes
    # produced its cycles.  Now it can, and an A/B whose two images differ by more than the one
    # flag it claims is detectable from the record alone.
    res = {"image_bytes": os.path.getsize(img_p) if os.path.exists(img_p) else None,
           "image_md5": (hashlib.md5(open(img_p, "rb").read()).hexdigest()
                         if os.path.exists(img_p) else None),
           "ran": runl is not None, "target": rd(d, "target.txt"), "warmup": rd(d, "warmup.txt"),
           "kernel_picks": {k: (v.get("algorithm") or v["source"]) for k, v in picks.items()},
           "kernel_cflags": rd(d, "kernel_cflags.txt"), "bitstream_md5": rd(d, "bitstream_md5.txt"),
           "fclk_as_run": json.load(open(os.path.join(d, "fclk.json"))) if rd(d, "fclk.json") else None,
           "console_bytes": len(txt), "ram_reads": peeks,
           "board_side": rd(d, "board_side.log")}
    if runl is None:
        res["banner_seen"] = "Booting Zephyr" in txt
        res["main_seen"] = "MB_PEXT_BUILD" in txt
        return res
    kv = {k: int(v) for k, v in re.findall(r"(\w+)=(-?\d+)", runl)}
    res.update({k: kv.get(k) for k in ("cpu", "mhartid", "median", "min", "max", "warm", "max_abs_err")})
    res["result_line"] = next((l for l in txt.splitlines() if l.startswith("RESULT:")), None)
    eng = {}
    for l in txt.splitlines():
        if l.startswith("MB_ROCCMOON "):
            e = dict(re.findall(r"(\w+)=(\S+)", l))
            ph = e.pop("phase")   # pop BEFORE the comprehension: `d[e.pop()] = {..e..}` runs the RHS first
            eng[ph] = {k: (int(v, 0) if re.fullmatch(r"-?(0x[0-9a-fA-F]+|\d+)", v) else v) for k, v in e.items()}
    if eng:
        if "warm" in eng and "total" in eng:
            eng["timed"] = {k: eng["total"][k] - eng["warm"][k] for k in eng["total"]
                            if k not in ("last_rc", "last_status") and isinstance(eng["total"][k], int)
                            and isinstance(eng["warm"].get(k), int)}
        res["roccmoon_stats"] = eng
    for l in txt.splitlines():
        if l.startswith("MB_SMX2 "):
            e = dict(re.findall(r"(\w+)=(\S+)", l))
            hist = {}
            for kv_ in e.pop("d0_hist", "").split(","):
                if ":" in kv_:
                    a_, b_ = kv_.split(":")
                    hist[int(a_)] = int(b_)
            res["smx2_stats"] = {k: int(v) for k, v in e.items() if re.fullmatch(r"\d+", v)}
            res["smx2_stats"]["d0_hist"] = hist
    ops = {}
    for l in txt.splitlines():
        if l.startswith("MB_PEXT_OP "):
            o = dict(re.findall(r"(\w+)=(\S+)", l))
            ops[o["name"]] = int(o["cycles"])
    rows, kinds = [], {}
    for o in g["ops"]:
        if o.get("dispatch_id") is None or o["name"] not in ops:
            continue
        macs, els = work(o["op"], o["shape"])
        cyc = ops[o["name"]]
        rows.append({"dispatch": o["dispatch_id"], "name": o["name"], "op": o["op"],
                     "shape": o["shape"], "cycles": cyc, "macs": macs, "elements": els,
                     "kernel": res["kernel_picks"].get(o["op"])})
        k = kinds.setdefault(o["op"], {"dispatches": 0, "cycles": 0, "macs": 0, "elements": 0,
                                        "kernel": res["kernel_picks"].get(o["op"])})
        k["dispatches"] += 1
        k["cycles"] += cyc
        k["macs"] += macs
        k["elements"] += els
    tot = sum(r["cycles"] for r in rows)
    for k in kinds.values():
        k["share_pct"] = round(100.0 * k["cycles"] / tot, 3) if tot else None
        k["cycles_per_mac"] = round(k["cycles"] / k["macs"], 4) if k["macs"] else None
        k["cycles_per_element"] = round(k["cycles"] / k["elements"], 3) if k["elements"] else None
        k["seconds"] = round(k["cycles"] / CLK, 3)
    res.update({"dispatch_cycles_total": tot, "seconds": tot / CLK, "rows": rows, "per_kind": kinds,
                "dispatches_profiled": len(rows), "dispatches_in_ir": len(g["dispatches"])})
    if name.startswith("enc"):
        res["rtf_4s"] = tot / CLK / WINDOW_S
        # THE HEADLINE NUMBER, IN THE RECORD AND NOT ONLY IN PROSE.  Every engine RTF this project
        # quotes is steady state: the dispatch total less the ONE-TIME weight-image build, which is
        # paid once per model load and not once per utterance.  It used to be derivable from
        # per-model fields but was written down nowhere, so run.json now carries it for every image
        # -- image_cycles is 0 for a software one, and then steady == the dispatch total.
        img_c = ((res.get("roccmoon_stats", {}).get("timed")
                  or res.get("roccmoon_stats", {}).get("total") or {}).get("image_cycles", 0))
        res["image_cycles_once"] = img_c
        res["steady_cycles"] = tot - img_c
        res["rtf_steady"] = (tot - img_c) / CLK / WINDOW_S
    return res


out = {"lab": "B26 moonshine_enc",
       "model": "UsefulSensors/moonshine-tiny@390624ed33d594443aa4aa221f5b9f283b545b5a encoder",
       "window_s": WINDOW_S, "encoder_frames": FRAMES, "clock_hz": CLK, "hart": 0,
       "bitstream_md5": os.environ.get("BIT_MD5") or next(
           (rd(os.path.join(run, m), "bitstream_md5.txt") for m in models
            if rd(os.path.join(run, m), "bitstream_md5.txt")), "unknown"),   # --report-only "bitstream_note": os.environ.get("BIT_NOTE", ""),
       "soc_magic": os.environ.get("WANT_MAGIC", ""),
       "fclk": json.load(open(os.path.join(run, "fclk.json"))) if os.path.exists(os.path.join(run, "fclk.json")) else None,
       "clocks": json.load(open(os.path.join(run, "clocks.json"))) if os.path.exists(os.path.join(run, "clocks.json")) else None,
       "models": {}}
for m in models:
    if os.path.isdir(os.path.join(run, m)):
        out["models"][m] = model(m)

for m, r in out["models"].items():
    if not r.get("ran"):
        last = r["ram_reads"][-1] if r["ram_reads"] else {}
        print(f"\n-- {m}: NO RESULT (console {r['console_bytes']} bytes, banner {r.get('banner_seen')}, "
              f"main {r.get('main_seen')}); RAM at the end: {json.dumps({k: v for k, v in last.items() if k != 'records_'})[:300]}")
        continue
    head = f"\n-- {m}  {r['dispatch_cycles_total']:,} cycles = {r['seconds']:.2f} s"
    if "rtf_4s" in r:
        head += f" for {WINDOW_S} s of audio, RTF {r['rtf_4s']:.2f}"
        if r.get("image_cycles_once"):
            head += f"; steady {r['steady_cycles']:,} = RTF {r['rtf_steady']:.3f} (image {r['image_cycles_once']:,})"
    print(head + f"   (run {r['median']:,}, warm {r['warm']:,}, max_abs_err {r['max_abs_err']} vs its host-C golden)")
    print("   %-13s %4s %14s %7s %14s %12s %10s %11s  %s" % ("op", "n", "cycles", "share", "MACs",
          "elements", "cyc/MAC", "cyc/elem", "kernel"))
    for op, k in sorted(r["per_kind"].items(), key=lambda kv: -kv[1]["cycles"]):
        print("   %-13s %4d %14s %6.2f%% %14s %12s %10s %11s  %s" % (
            op, k["dispatches"], f"{k['cycles']:,}", k["share_pct"], f"{k['macs']:,}" if k["macs"] else "-",
            f"{k['elements']:,}", k["cycles_per_mac"] or "-", k["cycles_per_element"], k["kernel"]))
    if r.get("roccmoon_stats"):
        print("   engine stats (timed = total - warm):", json.dumps(r["roccmoon_stats"].get("timed", r["roccmoon_stats"]))[:400])
    if m.startswith("stem"):
        for row in r["rows"]:
            sh = row["shape"]
            if row["op"] == "conv2d_s8":
                print("     %-12s KH=%s KW=%s SH=%s SW=%s  %14s cycles  %.3f cyc/MAC" % (
                    row["name"], sh["KH"], sh["KW"], sh["SH"], sh["SW"], f"{row['cycles']:,}", row["cycles"] / row["macs"]))

M = out["models"]
for sfx in ("", "_bigconv"):
    w, h = M.get("stem_w" + sfx, {}), M.get("stem_h" + sfx, {})
    if not (w.get("ran") and h.get("ran")):
        continue
    wr = {r["name"]: r for r in w["rows"]}
    hr = {r["name"]: r for r in h["rows"]}
    lever = {}
    print("\n-- the layout lever on Moonshine's stem%s: time on H / time on W, per dispatch" % sfx)
    for n in wr:
        if n in hr:
            lever[n] = {"op": wr[n]["op"], "w_cycles": wr[n]["cycles"], "h_cycles": hr[n]["cycles"],
                        "h_over_w": round(hr[n]["cycles"] / wr[n]["cycles"], 3),
                        "w_cyc_per_mac": round(wr[n]["cycles"] / wr[n]["macs"], 4) if wr[n]["macs"] else None,
                        "h_cyc_per_mac": round(hr[n]["cycles"] / hr[n]["macs"], 4) if hr[n]["macs"] else None}
            print("   %-16s %-12s W %14s  H %14s  H/W %.3f" % (n, wr[n]["op"], f"{wr[n]['cycles']:,}",
                  f"{hr[n]['cycles']:,}", lever[n]["h_over_w"]))
    out["stem_layout_lever" + sfx] = lever
# The engine against its twins.  Two twins where the lab built both: the same generated C
# (enc_ew: pext_patch_dot8 at its default limits, which sends conv3 to the scalar reference)
# and enc_ew_bigconv (the same C with the conv kernel's limits raised, conv3 on DOT8 -- the fair
# MBP baseline for conv2d_s8).  The encoder images run no warm-up, so the engine's ONE-TIME
# weight-image build (mbxr_rt_stats.image_cycles, spent inside the first call of each layer) is
# inside its measured dispatches; "excl_image" subtracts that measured counter.
for v in list(M):
    if not (v.startswith("enc_") and v.endswith("_eng") and M[v].get("ran")):
        continue
    img = (M[v].get("roccmoon_stats", {}).get("timed") or M[v].get("roccmoon_stats", {}).get("total") or {}).get("image_cycles", 0)
    for tw in (v[:-4], v[:-4] + "_bigconv"):
        t = M.get(tw, {})
        if not t.get("ran"):
            continue
        cmp = {op: {"engine_cycles": M[v]["per_kind"][op]["cycles"], "twin_cycles": t["per_kind"][op]["cycles"],
                    "speedup": round(t["per_kind"][op]["cycles"] / M[v]["per_kind"][op]["cycles"], 3)}
               for op in ("linear_s8", "conv2d_s8") if op in M[v]["per_kind"] and op in t["per_kind"]}
        eng_ll = sum(M[v]["per_kind"][op]["cycles"] for op in ("linear_s8", "conv2d_s8") if op in M[v]["per_kind"])
        tw_ll = sum(t["per_kind"][op]["cycles"] for op in ("linear_s8", "conv2d_s8") if op in t["per_kind"])
        cmp["linear_plus_conv_excl_image"] = {"engine_cycles": eng_ll - img, "twin_cycles": tw_ll,
                                              "speedup": round(tw_ll / (eng_ll - img), 3)}
        cmp["total"] = {"engine_cycles": M[v]["dispatch_cycles_total"], "twin_cycles": t["dispatch_cycles_total"],
                        "speedup": round(t["dispatch_cycles_total"] / M[v]["dispatch_cycles_total"], 3)}
        cmp["total_excl_image"] = {"engine_cycles": M[v]["dispatch_cycles_total"] - img,
                                   "twin_cycles": t["dispatch_cycles_total"], "image_cycles": img,
                                   "speedup": round(t["dispatch_cycles_total"] / (M[v]["dispatch_cycles_total"] - img), 3),
                                   "rtf_4s_engine": round((M[v]["dispatch_cycles_total"] - img) / CLK / WINDOW_S, 3)}
        out.setdefault("engine_vs_twin", {})[f"{v}_vs_{tw}"] = cmp
        print(f"\n-- {v} against {tw}: {json.dumps(cmp)}")
json.dump(out, open(os.path.join(run, "run.json"), "w"), indent=1)
print(f"\nwrote {os.path.join(run, 'run.json')}")
PY
