#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Emit the LIVE image's data: the embedding table and the constant record tail.

    emit_live_io.py --emb <hostref/emb.f32> --src <a packed in.bin> --out <dir>

WHAT A LIVE IMAGE NEEDS THAT A BAKED ONE DOES NOT, AND WHAT IT NO LONGER NEEDS.

  mb_ar_emb   STILL NEEDED.  32,768 x 288 float32 = 37.7 MB.  The decoder looks the token it
              just chose up in this table and writes the row back into its own input, so it
              is not optional and it is not compressible without changing the arithmetic.
  mb_ar_in    NOT NEEDED, AND THIS IS THE WHOLE POINT.  A baked image carries N x 70,912 B of
              audio; a live one captures its 64,000 samples from the microphone.  At 324
              records that is 22,975,488 B of .incbin that simply is not here.
  mb_ar_tail  NEW, AND IT IS 6,912 BYTES.  A packed record is [64,000 audio][6,912 tail] and
              b134_set.load_tail GATES that the tail is identical across every record of a
              packed in.bin -- the substitution this file performs is only sound because of
              that gate, so it is RE-CHECKED here rather than assumed.
"""
import argparse, hashlib, os, sys
import numpy as np

N_AUD, NB = 64000, 70912


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--emb", required=True)
    p.add_argument("--src", required=True, help="a packed in.bin to lift the tail from")
    p.add_argument("--out", required=True)
    p.add_argument("--selftest-run", help="a scored run dir; bake record --selftest-slot of "
                                          "its in.bin plus the tokens the BOARD produced for it")
    p.add_argument("--selftest-slot", type=int, default=0)
    a = p.parse_args()

    raw = np.fromfile(a.src, dtype=np.int8)
    if raw.size % NB:
        sys.exit("%s is not a whole number of %d-byte records" % (a.src, NB))
    rec = raw.reshape(-1, NB)
    tail = rec[:, N_AUD:]
    if not (tail == tail[0]).all():
        sys.exit("the tail is NOT identical across %s's %d records -- the live substitution "
                 "would be wrong" % (a.src, rec.shape[0]))
    t = tail[0]
    os.makedirs(a.out, exist_ok=True)

    emb = os.path.abspath(a.emb)
    nemb = os.path.getsize(emb)
    with open(os.path.join(a.out, "ar_io_live.S"), "w") as f:
        f.write("/* @generated by emit_live_io.py -- do not edit. */\n"
                "    .section .rodata\n    .balign 16\n"
                "    .globl mb_ar_emb\nmb_ar_emb:\n    .incbin \"%s\"\n"
                "    .balign 16\n" % emb)
    with open(os.path.join(a.out, "mb_ar_tail.c"), "w") as f:
        f.write("/* @generated by emit_live_io.py -- do not edit. */\n"
                "#include <stdint.h>\n"
                "const int8_t mb_ar_tail[%d] = {%s};\n"
                % (t.size, ",".join(str(int(v)) for v in t)))
    print("ar_io_live.S: mb_ar_emb <- %s (%d B = %.1f MB)" % (emb, nemb, nemb / 1048576.0))
    print("mb_ar_tail.c: %d B, identical across all %d records of %s, sha256 %s"
          % (t.size, rec.shape[0], os.path.basename(a.src),
             hashlib.sha256(t.tobytes()).hexdigest()[:16]))
    if a.selftest_run:
        emit_selftest(a, rec, os.path.join(a.out, "mb_selftest.c"))

    print("NOT emitted: mb_ar_in -- %d records x %d B = %d B of .incbin the live image omits"
          % (rec.shape[0], NB, rec.shape[0] * NB))


def emit_selftest(a, rec, path):
    """ONE baked record and the tokens THIS BOARD produced for it.

    The live image's first act is to decode this and compare.  It separates two failures that
    look identical on a console -- "the model is wrong" and "the microphone is wrong" -- and it
    costs 70,912 B.  The expected tokens are the BOARD's own, read out of a scored run, not the
    host's: if they differ the run that produced them would already have failed its folds gate.
    """
    import json
    rj = json.load(open(os.path.join(a.selftest_run, "run.json")))
    rows = {int(v["utt"]): v for v in rj.get("per_utterance", [])}
    r = rows.get(a.selftest_slot)
    if r is None:
        sys.exit("%s/run.json has no utterance %d" % (a.selftest_run, a.selftest_slot))
    toks = r.get("board_tokens") or []
    if not toks:
        sys.exit("utterance %d has no board_tokens" % a.selftest_slot)
    rec0 = rec[a.selftest_slot]
    with open(path, "w") as f:
        f.write("/* @generated by emit_live_io.py -- do not edit.  Record %d of %s. */\n"
                "#include <stdint.h>\n#include \"mb_selftest.h\"\n"
                "const int8_t mb_selftest_in[%d] = {%s};\n"
                "const int32_t mb_selftest_tok[%d] = {%s};\n"
                % (a.selftest_slot, os.path.abspath(a.selftest_run), rec0.size,
                   ",".join(str(int(v)) for v in rec0), len(toks),
                   ",".join(str(int(v)) for v in toks)))
    with open(os.path.join(os.path.dirname(path), "mb_selftest.h"), "w") as f:
        f.write("/* @generated by emit_live_io.py -- do not edit. */\n#pragma once\n"
                "#include <stdint.h>\n#define MB_SELFTEST_IN_BYTES %d\n"
                "#define MB_SELFTEST_NTOK %d\n"
                "extern const int8_t  mb_selftest_in[];\n"
                "extern const int32_t mb_selftest_tok[];\n" % (rec0.size, len(toks)))
    print("mb_selftest.c: record %d, %d B, %d expected tokens (the BOARD's own): %s"
          % (a.selftest_slot, rec0.size, len(toks), toks[:8]))


if __name__ == "__main__":
    main()
