#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Emit the Moonshine tokenizer's detokenisation table as C, for on-board transcripts.

    emit_vocab.py --out <dir>          # writes mb_vocab.h and mb_vocab.S
    emit_vocab.py --verify <run_dir>   # score the C algorithm against the Python tokenizer

WHY A TABLE AND NOT A TOKENISER.  The board never ENCODES text, only decodes token ids it
chose itself, so none of the BPE merge machinery is needed on the target.  tokenizer.json's
decoder is a four-step Sequence -- Replace "U+2581" -> " ", ByteFallback, Fuse, Strip one
leading space -- and the first two are per-token and can be applied HERE, on the host.  What
reaches the board is one byte string per id; detokenisation is then concatenation plus the
single leading-space strip, which is ~15 lines of C that cannot drift from the reference.

THE RISK THIS CREATES, AND THE GATE THAT CATCHES IT.  Pre-resolving a decoder on the host is
exactly how a transcript silently changes.  So --verify runs the C algorithm's EXACT steps in
Python over every token sequence the board has actually produced and requires the string to
equal PreTrainedTokenizerFast.decode(skip_special_tokens=True) CHARACTER FOR CHARACTER.
"""
import argparse, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)


def table():
    """id -> the bytes that id contributes, with Replace and ByteFallback already applied."""
    import moonshine_enc as me
    j = json.load(open(os.path.join(str(me.moonshine_dir()), "tokenizer.json")))
    vocab = j["model"]["vocab"]
    specials = {t["content"] for t in j.get("added_tokens", []) if t.get("special")}
    n = max(vocab.values()) + 1
    out = [b""] * n
    for tok, i in vocab.items():
        if tok in specials:
            out[i] = b""                      # skip_special_tokens=True
        elif len(tok) == 6 and tok.startswith("<0x") and tok.endswith(">"):
            out[i] = bytes([int(tok[3:5], 16)])          # ByteFallback
        else:
            out[i] = tok.replace("▁", " ").encode("utf-8")
    return out, n


def detok(ids, tab):
    """THE ALGORITHM THE C IMPLEMENTS, so --verify tests what ships."""
    s = b"".join(tab[i] for i in ids if 0 <= i < len(tab))
    return s.decode("utf-8", "replace")[1:] if s[:1] == b" " else s.decode("utf-8", "replace")


def cmd_emit(a):
    tab, n = table()
    blob = b"".join(tab)
    off, k = [], 0
    for t in tab:
        off.append(k); k += len(t)
    os.makedirs(a.out, exist_ok=True)
    with open(os.path.join(a.out, "mb_vocab.h"), "w") as f:
        f.write("/* @generated by emit_vocab.py -- do not edit. */\n#pragma once\n"
                "#include <stdint.h>\n"
                "#define MB_VOCAB_N %d\n#define MB_VOCAB_BYTES %d\n"
                "extern const uint8_t  mb_vocab_blob[];\n"
                "extern const uint32_t mb_vocab_off[];\n" % (n, len(blob)))
    with open(os.path.join(a.out, "mb_vocab.c"), "w") as f:
        f.write("/* @generated by emit_vocab.py -- do not edit. */\n#include \"mb_vocab.h\"\n")
        f.write("const uint8_t mb_vocab_blob[%d] = {" % max(len(blob), 1))
        f.write(",".join(str(b) for b in blob) if blob else "0")
        f.write("};\n")
        f.write("const uint32_t mb_vocab_off[%d] = {" % (n + 1))
        f.write(",".join(str(v) for v in off + [k]))
        f.write("};\n")
    print("mb_vocab: %d ids, %d blob bytes, %d offset bytes = %.1f KB total"
          % (n, len(blob), 4 * (n + 1), (len(blob) + 4 * (n + 1)) / 1024.0))
    return 0


def cmd_verify(a):
    from transformers import PreTrainedTokenizerFast
    import moonshine_enc as me
    tab, _ = table()
    tok = PreTrainedTokenizerFast(
        tokenizer_file=os.path.join(str(me.moonshine_dir()), "tokenizer.json"))
    rj = json.load(open(os.path.join(a.verify, "run.json")))
    rows = rj.get("per_utterance", [])
    if not rows:
        sys.exit("%s/run.json has no per_utterance rows" % a.verify)
    bad = 0
    for r in rows:
        ids = r.get("board_tokens") or []
        want = tok.decode(ids, skip_special_tokens=True)
        got = detok(ids, tab)
        if got != want:
            bad += 1
            if bad <= 5:
                print("  MISMATCH utt %s\n    py %r\n    c  %r" % (r.get("utt"), want, got))
    print("checked %d board token sequences from %s" % (len(rows), a.verify))
    print("MISMATCHES: %d -- %s" % (bad, "PASS" if bad == 0 else "***FAIL***"))
    return 1 if bad else 0


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--out"); p.add_argument("--verify")
    A = p.parse_args()
    sys.exit(cmd_verify(A) if A.verify else cmd_emit(A))
