#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Build ModelBlaster's generated C for the HOST and run it -- the machinery the Moonshine
host gates (check_moonshine.py) and the fidelity check (host_fidelity.py) share.

The generated model.c/kernels.c/weights.c/buffers.c are compiled UNMODIFIED, against
fpga/pynq-z2/modelblaster/check/shim/zephyr/kernel.h (k_cycle_get_64 only) and, for the
curated kernels, fpga/pynq-z2/sw/pext.h with MB_PEXT_HW=0 -- the header's own software
model of the MBP instructions, which PEXT_SPEC.md makes the normative definition.

-ffp-contract=off: the reference kernels' float expressions must not be fused into
FMA instructions on a host that has them, because the board (soft-float, no FPU) never
does and the golden simulator does not either.

Two drivers:
  dump    run on the BAKED test input and write every intermediate buffer, in buffers.c
          order, followed by the model output
  batch   run on N inputs read back to back from one file, write the N outputs
"""
from __future__ import annotations

import json
import os
import re
import subprocess

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
MBDIR = os.path.dirname(HERE)                               # fpga/pynq-z2/modelblaster
SHIM = os.path.join(MBDIR, "check", "shim")
SW = os.path.join(os.path.dirname(MBDIR), "sw")             # fpga/pynq-z2/sw
CC = os.environ.get("HOST_CC", "cc")

DRIVER = r"""/* @generated by fpga/pynq-z2/modelblaster/moonshine/hostrun.py */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "model.h"
#include "test_io.h"

%(externs)s

#ifdef FX_STATS
/* The exact kernels' slow-path counters, weak so a variant without them still links. */
extern unsigned long pint_add_slow_count __attribute__((weak)), pint_add_count __attribute__((weak));
extern unsigned long pint_rope_slow_count __attribute__((weak)), pint_rope_count __attribute__((weak));
extern unsigned long pint_mmb_slow_count __attribute__((weak)), pint_mmb_count __attribute__((weak));
static void fx_stats(void)
{
    if (&pint_add_count) fprintf(stderr, "FXSTATS kernel=add_s8 slow=%%lu elements=%%lu\n", pint_add_slow_count, pint_add_count);
    if (&pint_rope_count) fprintf(stderr, "FXSTATS kernel=rope_s8 slow=%%lu elements=%%lu\n", pint_rope_slow_count, pint_rope_count);
    if (&pint_mmb_count) fprintf(stderr, "FXSTATS kernel=matmul_b_s8 slow=%%lu elements=%%lu\n", pint_mmb_slow_count, pint_mmb_count);
}
#else
static void fx_stats(void) {}
#endif

static void dump_all(FILE *f, const int8_t *out)
{
%(writes)s
    fwrite(out, 1, MODEL_TEST_OUTPUT_LEN, f);
}

int main(int argc, char **argv)
{
    static int8_t out[MODEL_TEST_OUTPUT_LEN];
    static model_input_t in[MODEL_TEST_INPUT_LEN];
    FILE *f, *g;

    if (argc == 3 && !strcmp(argv[1], "dump")) {
        model_run_test(out, 0);
        f = fopen(argv[2], "wb");
        if (!f) return 2;
        dump_all(f, out);
        fclose(f);
        fx_stats();
        return 0;
    }
    if (argc == 4 && !strcmp(argv[1], "batch")) {
        f = fopen(argv[2], "rb");
        g = fopen(argv[3], "wb");
        if (!f || !g) return 2;
        while (fread(in, sizeof(in[0]), MODEL_TEST_INPUT_LEN, f) == MODEL_TEST_INPUT_LEN) {
            run_model(in, out, 0);
            fwrite(out, 1, MODEL_TEST_OUTPUT_LEN, g);
        }
        fclose(f);
        fclose(g);
        return 0;
    }
    fprintf(stderr, "usage: %%s dump OUT | batch INPUTS OUTPUTS\n", argv[0]);
    return 2;
}
"""


_CTYPES = {"int8_t": np.int8, "int16_t": np.int16}


def buffers(gen: str):
    """[(symbol, size)] of the int8 buffers, in buffers.c order."""
    return [(n, s) for n, s, t in buffers_typed(gen) if t == np.int8]


def buffers_typed(gen: str):
    """[(symbol, elements, numpy dtype)] of the int8 and int16 buffers, in buffers.c order
    (patches/0103 lowers Moonshine's stem to int16)."""
    out = []
    for line in open(os.path.join(gen, "buffers.c")):
        m = re.match(r"^\s*(int8_t|int16_t)\s+(buf_\w+)\[(\d+)\]", line)
        if m:
            out.append((m.group(2), int(m.group(3)), _CTYPES[m.group(1)]))
    return out


def tensor_of_buffer(gen: str, ir: dict) -> dict:
    """{buffer symbol: IR tensor name}."""
    mid = re.sub(r"[.\-]", "_", ir["name"])
    return {f"buf_{mid}_{re.sub(r'[.-]', '_', t)}": t for t in ir["tensors"]}


def build(gen: str, workdir: str, kernels_c: str | None = None,
          extra_cflags=(), sanitize: bool = False) -> str:
    os.makedirs(workdir, exist_ok=True)
    bufs = buffers_typed(gen)
    cname = {np.int8: "int8_t", np.int16: "int16_t"}
    with open(os.path.join(workdir, "driver.c"), "w") as f:
        f.write(DRIVER % {
            "externs": "\n".join(f"extern {cname[t]} {n}[{s}];" for n, s, t in bufs),
            "writes": "\n".join(f"    fwrite({n}, sizeof({n}[0]), {s}, f);" for n, s, t in bufs),
        })
    exe = os.path.join(workdir, "model")
    objs = []
    # weights.c is 30 MB of initialisers: compile it once, without optimisation, and
    # keep the object across rebuilds of the kernels.
    wobj = os.path.join(workdir, "weights.o")
    wsrc = os.path.join(gen, "weights.c")
    if not os.path.exists(wobj) or os.path.getmtime(wobj) < os.path.getmtime(wsrc):
        subprocess.run([CC, "-O0", "-c", "-w", f"-I{gen}", wsrc, "-o", wobj], check=True)
    objs.append(wobj)
    san = ["-fsanitize=address,undefined", "-fno-sanitize-recover=all", "-g"] if sanitize else []
    cmd = [CC, "-O2", "-w", "-std=gnu11", "-ffp-contract=off", "-DMB_PEXT_HW=0",
           f"-I{SHIM}", f"-I{gen}", f"-I{SW}", *san, *extra_cflags,
           os.path.join(workdir, "driver.c"), os.path.join(gen, "model.c"),
           kernels_c or os.path.join(gen, "kernels.c"), os.path.join(gen, "buffers.c"),
           os.path.join(gen, "test_io.S"), *objs, "-o", exe, "-lm"]
    subprocess.run(cmd, check=True, cwd=gen)
    return exe


def dump(exe: str, gen: str, path: str) -> dict:
    """Run on the baked input; {buffer symbol or '__output__': int8 array}, plus
    '__fxstats__' when the build carried -DFX_STATS."""
    proc = subprocess.run([exe, "dump", path], check=True, capture_output=True, text=True)
    raw = np.fromfile(path, dtype=np.int8)
    out, off = {}, 0
    for n, s, t in buffers_typed(gen):
        nb = s * np.dtype(t).itemsize
        out[n] = raw[off:off + nb].view(t)
        off += nb
    out["__output__"] = raw[off:]
    out["__fxstats__"] = [dict(re.findall(r"(\w+)=(\S+)", l)) for l in proc.stderr.splitlines()
                          if l.startswith("FXSTATS ")]
    return out


def batch(exe: str, inputs: np.ndarray, out_len: int, workdir: str) -> np.ndarray:
    """inputs: [B, input_len] int8 (or int16, for a model whose input is int16) -> [B, out_len] int8."""
    ip = os.path.join(workdir, "batch_in.bin")
    op = os.path.join(workdir, "batch_out.bin")
    np.ascontiguousarray(inputs if inputs.dtype == np.int16 else inputs.astype(np.int8)).tofile(ip)
    subprocess.run([exe, "batch", ip, op], check=True)
    return np.fromfile(op, dtype=np.int8).reshape(inputs.shape[0], out_len)


def compare_to_golden(gen: str, ir_path: str, acts_npz: str, dumped: dict) -> list:
    """Per dispatch: max |host - python golden| over its output tensor."""
    ir = json.load(open(ir_path))
    acts = np.load(acts_npz)
    t_of = tensor_of_buffer(gen, ir)
    rows = []
    for op in ir["ops"]:
        if op.get("dispatch_id") is None:
            continue
        for t in op["outputs"]:
            sym = next((b for b, tt in t_of.items() if tt == t), None)
            if t == ir["output"]["tensors"][0]:
                host = dumped["__output__"]
            elif sym in dumped:
                host = dumped[sym]
            else:
                continue
            gold = acts[t].reshape(-1)
            err = int(np.abs(host.astype(np.int64) - gold.astype(np.int64)).max())
            ndiff = int((host != gold).sum())
            rows.append({"dispatch": op["dispatch_id"], "name": op["name"], "op": op["op"],
                         "tensor": t, "elements": int(gold.size),
                         "max_abs_err": err, "n_differ": ndiff})
    return rows
