#!/usr/bin/env python3
"""SIMULATION ONLY.  Emit rtl/gen/byptb_top_<cfg>.sv around the GENERATED memory bus of a bypass config.

What is real: MemoryBus.sv as elaborated -- the BwBypass lanes (mbxd_dma.v), the lane couplers, the mbus
crossbar, patch 0061's TLBuffer, TLWidthWidget, TLToAXI4, AXI4IdIndexer, AXI4UserYanker -- and the pbus-side
TLAsyncCrossingSource that reaches its register node, so the MMIO path is the generated one too.
What is not: the AXI4 memory behind each channel (csrc/main.cpp) and one clock for both domains.
The top's ports come from the generated port lists, not from a hand-written copy."""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
CFGS = {'bypass':  ('PynqZ2RocketBigLittlePextTacitMicRgbBwBypassConfig',  'TLAsyncCrossingSource_a29d64s11k1z2u'),
        'bypass4': ('PynqZ2RocketBigLittlePextTacitMicRgbBwBypass4Config', 'TLAsyncCrossingSource_a29d64s11k1z2u')}
NCH = {'bypass': 2, 'bypass4': 4}

def ports(sv, mod):
    txt = open(sv).read()
    m = re.search(r'^module %s\((.*?)^\);' % re.escape(mod), txt, re.S | re.M)
    out = []
    for line in m.group(1).split('\n'):
        line = line.split('//')[0]
        mm = re.match(r'\s*(input|output)\s*(\[[^\]]+\])?\s*(\w+)', line)
        if mm: out.append((mm.group(1), mm.group(2) or '', mm.group(3)))
    return out

def main():
    name = sys.argv[1] if len(sys.argv) > 1 else 'bypass'
    cfg, xsrc_mod = CFGS[name]
    if len(sys.argv) > 2 and sys.argv[2] == '--config': print(cfg); return
    if len(sys.argv) > 2 and sys.argv[2] == '--nch': print(NCH[name]); return
    root = os.environ.get('BYPTB_GENSRC_ROOT') or sys.exit('set BYPTB_GENSRC_ROOT to <chipyard>/sims/verilator/generated-src')
    gen = os.path.join(root, 'chipyard.harness.TestHarness.' + cfg, 'gen-collateral')
    mb = ports(os.path.join(gen, 'MemoryBus.sv'), 'MemoryBus')
    xs = ports(os.path.join(gen, xsrc_mod + '.sv'), xsrc_mod)
    top_ports, decl, conn_mb, conn_xs = ['input clock', 'input reset'], [], [], []
    xsrc_out = {p for _, _, p in xs if p.startswith('auto_out_')}
    for d, w, p in mb:
        if p in ('auto_mbus_clock_groups_in_member_mbus_0_clock',):
            conn_mb.append('.%s(clock)' % p); continue
        if p in ('auto_mbus_clock_groups_in_member_mbus_0_reset',):
            conn_mb.append('.%s(reset)' % p); continue
        if p.startswith('auto_xsink_in_'):
            peer = 'auto_out_' + p[len('auto_xsink_in_'):]
            assert peer in xsrc_out, peer
            decl.append('  wire %s x_%s;' % (w, peer)); conn_mb.append('.%s(x_%s)' % (p, peer)); continue
        if p.startswith('auto_bus_xing_in_'):          # the L2's crossing from the sbus: idle
            if d == 'input':
                conn_mb.append(".%s('0)" % p)
            else:
                decl.append('  wire %s nc_%s;' % (w, p)); conn_mb.append('.%s(nc_%s)' % (p, p))
            continue
        if p.startswith('auto_fixedClockNode_'):
            decl.append('  wire %s nc_%s;' % (w, p)); conn_mb.append('.%s(nc_%s)' % (p, p)); continue
        short = p.replace('auto_coupler_to_memory_controller_port_named_axi4_axi4yank_out_', 'axi')
        short = short.replace('auto_buffer_out_', 'buf_')
        top_ports.append('%s %s %s' % (d, w, short)); conn_mb.append('.%s(%s)' % (p, short))
    for d, w, p in xs:
        if p == 'clock': conn_xs.append('.clock(clock)'); continue
        if p == 'reset': conn_xs.append('.reset(reset)'); continue
        if p.startswith('auto_out_'):
            conn_xs.append('.%s(x_%s)' % (p, p)); continue
        short = p.replace('auto_in_', 'mmio_')
        top_ports.append('%s %s %s' % (d, w, short)); conn_xs.append('.%s(%s)' % (p, short))
    out = ['// GENERATED by gen_top.py for %s -- SIMULATION ONLY' % cfg,
           'module byptb_top (', ',\n'.join('  ' + x for x in top_ports), ');'] + decl + [
           '  MemoryBus mbus (', ',\n'.join('    ' + c for c in conn_mb), '  );',
           '  %s xsrc (' % xsrc_mod, ',\n'.join('    ' + c for c in conn_xs), '  );', 'endmodule', '']
    os.makedirs(os.path.join(HERE, 'rtl', 'gen'), exist_ok=True)
    dst = os.path.join(HERE, 'rtl', 'gen', 'byptb_top_%s.sv' % name)
    open(dst, 'w').write('\n'.join(out))
    print(dst)

main()
