#!/usr/bin/env python3
# SIMULATION ONLY. Emit rtl/gen/l2tb_top_<cfg>.sv from rtl/l2tb_top.sv.in for one generated L2 config.
import sys, os
HERE=os.path.dirname(os.path.abspath(__file__))
CFGS = {
  # name:   (chipyard config, probe-coupler TLBuffer, inner TLBuffer, sinkW, L2 outer srcW, cork outer srcW, MSHRs)
  'lever1': ('PynqZ2RocketBigLittlePextTacitMicRgbBwConfig',        'TLBuffer_a32d64s3k3z4u', 'TLBuffer_a32d64s6k3z3c', 3, 3, 4, 7),
  'mshr12': ('PynqZ2RocketBigLittlePextTacitMicRgbBwL2Mshr12Config', 'TLBuffer_a32d64s3k4z4u', 'TLBuffer_a32d64s6k4z3c', 4, 4, 5, 12),
  'cap256': ('PynqZ2RocketBigLittlePextTacitMicRgbBwL2Cap256Config', 'TLBuffer_a32d64s3k3z4u', 'TLBuffer_a32d64s6k3z3c', 3, 3, 4, 7),
  # generated ReleaseAck-first cork (patch 0091): arbiter index 0 is the ReleaseAck queue, 1 is outer data
  'cork':   ('PynqZ2RocketBigLittlePextTacitMicRgbBwL2CorkConfig',   'TLBuffer_a32d64s3k3z4u', 'TLBuffer_a32d64s6k3z3c', 3, 3, 4, 7),
  # generated skip-clean-Release RTL (patch 0092): MSHR.sv differs; its TLCacheCork.sv differs from lever-1 only in $error text
  'skip':   ('PynqZ2RocketBigLittlePextTacitMicRgbBwL2SkipConfig',   'TLBuffer_a32d64s3k3z4u', 'TLBuffer_a32d64s6k3z3c', 3, 3, 4, 7),
  # lever 4: 128-bit system bus; the L2 inner port is 128-bit, outer 64-bit
  'wide':   ('PynqZ2RocketBigLittlePextTacitMicRgbBwWideConfig',   'TLBuffer_a32d128s3k3z4u', 'TLBuffer_a32d128s6k3z3c', 3, 3, 4, 7),
  # lever 4 + WithEdgeDataBits(128) + patch 0092: the L2 is 128-bit on both sides, data-first cork, skip clean Release
  'wideskip': ('PynqZ2RocketBigLittlePextTacitMicRgbBwL2WideSkipConfig', 'TLBuffer_a32d128s3k3z4u', 'TLBuffer_a32d128s6k3z3c', 3, 3, 4, 7),
  # WideSkip with the handler count released: 12 MSHRs, 10 take Gets
  'wideskipm12': ('PynqZ2RocketBigLittlePextTacitMicRgbBwL2WideSkipM12Config', 'TLBuffer_a32d128s3k4z4u', 'TLBuffer_a32d128s6k4z3c', 4, 4, 5, 12),
}
WIDE = {'wide': 128, 'wideskip': 128, 'wideskipm12': 128}      # inner (sbus side) data width
OUTER = {'wideskip': 128, 'wideskipm12': 128}                  # outer (cork / memory side) data width
# which TLArbiter state register holds the lock for outer data / for the ReleaseAck queue
CORK_LOCKS = {'cork': ('state_1_1', 'state_1_0')}
def main():
    name=sys.argv[1]
    cfg,pbuf,ibuf,sinkw,osrcw,csrcw,nm=CFGS[name]
    if len(sys.argv) > 2 and sys.argv[2] == '--config': print(cfg); return
    s=open(os.path.join(HERE,'rtl','l2tb_top.sv.in')).read()
    S='`SCH'
    def cat(fmt): return ', '.join(fmt.format(i=i) for i in reversed(range(nm)))
    plan = ', '.join('{%s}' % ', '.join(f'{S}._mshrs_{i}_io_schedule_bits_{c}_valid' for c in ['x','dir','e','d','c','a'])
                     for i in reversed(range(nm)))
    flags = ['meta_valid','s_release','w_releaseack','s_acquire','w_grantfirst','w_grantlast','w_grant',
             's_execute','s_grantack','s_writeback','meta_hit','request_valid']
    mf = ', '.join('{%s}' % ', '.join(f'{S}.mshrs_{i}.{f}' for f in flags) for i in reversed(range(nm)))
    obs = f"""  // generated for {name}: {cfg}, {nm} MSHRs
  assign obs_nm    = 8'd{nm};
  assign obs_req   = 16'({S}.mshr_request);
  assign obs_sel   = 16'({S}.mshr_selectOH);
  assign obs_schv  = 16'({{{cat(S+'._mshrs_{i}_io_schedule_valid')}}});
  assign obs_statv = 16'({{{cat(S+'._mshrs_{i}_io_status_valid')}}});
  assign obs_plan  = 96'({{{plan}}});
  // flags per MSHR: {{{', '.join(flags)}}}
  assign obs_mshr  = 192'({{{mf}}});"""
    for k,v in [('@@PBUF@@',pbuf),('@@IBUF@@',ibuf),('@@SINKW@@',str(sinkw)),('@@OSRCW@@',str(osrcw)),
                ('@@CSRCW@@',str(csrcw)),('@@OBSGEN@@',obs),
                ('@@DATAW@@',str(WIDE.get(name,64))),('@@MASKW@@',str(WIDE.get(name,64)//8)),
                ('@@IBEATS@@',str(64//(WIDE.get(name,64)//8))),
                ('@@ODATAW@@',str(OUTER.get(name,64))),('@@OMASKW@@',str(OUTER.get(name,64)//8)),
                ('@@OBYTES@@',str(OUTER.get(name,64)//8)),
                ('@@CORK_DATA_LOCK@@',CORK_LOCKS.get(name,('state_1_0','state_1_1'))[0]),
                ('@@CORK_RA_LOCK@@',CORK_LOCKS.get(name,('state_1_0','state_1_1'))[1])]:
        s=s.replace(k,v)
    assert '@@' not in s
    os.makedirs(os.path.join(HERE,'rtl','gen'),exist_ok=True)
    out=os.path.join(HERE,'rtl','gen',f'l2tb_top_{name}.sv')
    open(out,'w').write(f"// GENERATED by gen_top.py {name} -- do not edit\n"+s)
    print(out)
main()
