#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Emit b67_sides.h -- the 552 cat2_c1_s8 SIDES the Moonshine decoder actually runs:
element count, the exact set of input byte values that side contains, and its scales.

D is not an assumption here.  It is read off the HOST build of this decoder, by wrapping
the generated kernel and counting distinct input bytes per side (the L318 method), so the
spike instruction account below is taken at the model's own (cnt, D, value set) and not at
a nominal 256.  Regenerate with the measure_D pass described in the commit message."""
import json, sys, numpy as np

rows = json.load(open(sys.argv[1]))
out = ["/* SPDX-License-Identifier: Apache-2.0 */",
       "/* @generated by b67_gen_sides.py -- the decoder's own 552 cat2_c1_s8 sides. */",
       "#ifndef B67_SIDES_H", "#define B67_SIDES_H", "",
       "typedef struct {", "\tint cnt;", "\tint d;", "\tfloat s_in, s_out;",
       "\tint amin, amax;", "\tint ident;",
       "\tconst char *bm;   /* 64 hex nibbles: bit j of nibble i is set when byte code 4i+j occurs */",
       "} b67_side_t;", "",
       "static const b67_side_t b67_sides[] = {"]
tot_el = tot_d = 0
for r in rows:
    cnt, d = int(r["cnt"]), int(r["D"])
    si, so = float(np.float32(float(r["s_in"]))), float(np.float32(float(r["s_out"])))
    n = sum(bin(int(ch, 16)).count("1") for ch in r["bm"])
    assert n == d, (n, d)
    tot_el += cnt
    if not int(r["ident"]):
        tot_d += d
    out.append('\t{ %d, %d, %sf, %sf, %s, %s, %s, "%s" },' %
               (cnt, d, si.hex(), so.hex(), r["amin"], r["amax"], r["ident"], r["bm"]))
out += ["};",
        "#define B67_NSIDES ((int)(sizeof(b67_sides) / sizeof(b67_sides[0])))",
        "/* %d elements, %d table entries built by the pre-B67 builder. */" % (tot_el, tot_d),
        "", "#endif /* B67_SIDES_H */"]
open(sys.argv[2], "w").write("\n".join(out) + "\n")
print("sides", len(rows), "elements", tot_el, "entries", tot_d)
