# ---------------------------------------------------------------------------
# Out-of-context area AND timing for the packed-SIMD candidate datapaths.
#
#   vivado -mode batch -source ooc_pext.tcl
#
# Same part as the real build (xc7z020clg400-1) and the same 25 ns period, but
# unlike tcl/ooc_area.tcl this goes all the way through route_design, because the
# question here is path delay, not utilisation -- and on this device the routed
# delay is most of the answer (the real critical path is 6.3 ns of logic and
# 18.3 ns of routing).
#
# Every DUT is wrapped in pext_harness, which registers all inputs and the
# output, so report_timing measures a genuine reg -> logic -> reg path.
#
# Env:
#   PEXT_ONLY   space-separated subset of labels to run (default: all)
#   PEXT_OUT    output directory (default: ./ooc_out)
#   PEXT_PERIOD clock period in ns (default: 25.0)
# ---------------------------------------------------------------------------
set here [file dirname [file normalize [info script]]]
set outdir [expr {[info exists ::env(PEXT_OUT)] ? $::env(PEXT_OUT) : "$here/ooc_out"}]
set period [expr {[info exists ::env(PEXT_PERIOD)] ? $::env(PEXT_PERIOD) : 25.0}]
set only   [expr {[info exists ::env(PEXT_ONLY)] ? $::env(PEXT_ONLY) : ""}]
file mkdir $outdir

set part xc7z020clg400-1

# RocketALU.sv, straight out of the generated sources of the config that is on
# the board -- so the ALU reference is the ALU that is actually built.
# $CHIPYARD_GENSRC wins; otherwise the collateral vendored in this repo and unpacked by
# scripts/08_gensrc.sh. No absolute path into anyone's scratch directory -- see
# docs/REPRODUCING.md.
set cfg PynqZ2RocketBigLittleTacitConfig
if {[info exists ::env(CHIPYARD_GENSRC)]} {
  set gensrc $::env(CHIPYARD_GENSRC)
} else {
  set gsroot [expr {[info exists ::env(CHIPYARD_GENSRC_ROOT)] ? $::env(CHIPYARD_GENSRC_ROOT)
                                                              : [file normalize $here/../../../../out/gensrc]}]
  set gensrc $gsroot/chipyard.harness.TestHarness.$cfg
}
set alusrc $gensrc/gen-collateral/RocketALU.sv
if {![file exists $alusrc]} {
  # the generated-src tree is regenerated by other work; fall back to the vendored copy
  set alusrc $here/RocketALU_vendored.sv
  puts "NOTE: using vendored RocketALU.sv"
}
if {![file exists $alusrc]} { error "no RocketALU.sv: $alusrc" }

set rtl [list \
  $here/pext_pdot8_lut.v $here/pext_pdot8_dsp.v $here/pext_pdot8_lut_p2.v \
  $here/pext_pmaxmin8.v $here/pext_paddsub8_sat.v $here/pext_prequant.v \
  $here/pext_pdot4_16.v $here/pext_reduce_ladder.v $here/pext_decomposed.v \
  $here/pext_simd_alu.v $here/pext_variants.v $here/pext_alu_ref.v \
  $here/pext_null.v $here/pext_harness.v $here/pext_ex_stage.v $here/pext_regfile.v $here/pext_pdot8_dsp48.v \
  $here/pext_mulcell.v $alusrc]

# label  top-module  PEXT_DUT-define
set duts {
  {null              pext_harness        pext_null}
  {alu_only          pext_harness        pext_alu_only}
  {pmaxmin8          pext_harness        pext_pmaxmin8}
  {paddsub8_sat      pext_harness        pext_paddsub8_sat}
  {padd_2x32         pext_harness        pext_padd_2x32}
  {padd_4x16_sat     pext_harness        pext_padd_4x16_sat}
  {pclamp_4x16_to_8  pext_harness        pext_pclamp_4x16_to_8}
  {pclamp_2x32_to_8  pext_harness        pext_pclamp_2x32_to_8}
  {pmul8_16_d0       pext_harness        pext_pmul8_16}
  {pdot8_4x16_d1     pext_harness        pext_pdot8_4x16}
  {pdot8_2x32_d2     pext_harness        pext_pdot8_2x32}
  {pdot8_lut_d3      pext_harness        pext_v_dot8_lut}
  {pdot8_lut_signed  pext_harness        pext_v_dot8_lut_signed}
  {pdot8_lut_acc     pext_harness        pext_v_dot8_lut_acc}
  {pdot8_dsp48_d3    pext_harness        pext_v_dot8_dsp48}
  {pdot8_dsp48_p2    pext_harness        pext_v_dot8_dsp48_p2}
  {simd4_dsp48       pext_harness        pext_v_simd4_dsp48}
  {alu_simd4_dsp48   pext_harness        pext_v_alu_simd4_dsp48}
  {pdot8_dsp_d3      pext_harness        pext_v_dot8_dsp}
  {pdot8_dsp_p2      pext_harness        pext_v_dot8_dsp_p2}
  {pdot8_lut_p2      pext_harness        pext_pdot8_lut_p2}
  {pdot4_16_dsp      pext_harness        pext_v_dot4_16_dsp}
  {pdot4_16_lut      pext_harness        pext_v_dot4_16_lut}
  {requant2_auto     pext_harness        pext_v_requant2}
  {requant2_dsp      pext_harness        pext_v_requant2_dsp}
  {requant2_lut      pext_harness        pext_v_requant2_lut}
  {requant4_auto     pext_harness        pext_v_requant4}
  {mulscale2_dsp     pext_harness        pext_v_mulscale_dsp}
  {mulscale2_lut     pext_harness        pext_v_mulscale_lut}
  {pshift2_32        pext_harness        pext_pshift_2x32}
  {qmul2_dsp         pext_harness        pext_v_qmul2_dsp}
  {qmul2_lut         pext_harness        pext_v_qmul2_lut}
  {simd4_lut         pext_harness        pext_v_simd4_lut}
  {simd4_dsp         pext_harness        pext_v_simd4_dsp}
  {simd5_lut         pext_harness        pext_v_simd5_lut}
  {simd4_shallow     pext_harness        pext_simd_alu_shallow}
  {simd4_mid         pext_harness        pext_simd_alu_mid}
  {alu_simd4_lut     pext_harness        pext_v_alu_simd4_lut}
  {alu_simd4_dsp     pext_harness        pext_v_alu_simd4_dsp}
  {alu_simd_noreq    pext_harness        pext_v_alu_simd_noreq}
  {alu_simd_shallow  pext_harness        pext_alu_simd_shallow}
  {ex_none           pext_ex_none        -}
  {ex_shallow        pext_ex_shallow     -}
  {ex_mid            pext_ex_mid         -}
  {ex_deep           pext_ex_deep        -}
  {ex_full           pext_ex_full        -}
  {ex_dsp48          pext_ex_dsp48       -}
  {regfile_2r1w      pext_regfile_2r1w   -}
  {regfile_3r1w      pext_regfile_3r1w   -}
}

proc util_row {rpt name} {
  set fh [open $rpt r]; set txt [read $fh]; close $fh
  foreach line [split $txt "\n"] {
    if {[regexp "^\\|\\s+${name}\\*?\\s+\\|\\s+(\[0-9\]+)\\s+\\|" $line -> v]} { return $v }
  }
  return 0
}

# an undriven net synthesises to constant 0 with only a warning -- same promotion
# as the real build.  Set once: re-setting it after the promotion is itself an error.
set_msg_config -id {Synth 8-3848} -new_severity ERROR

set summary {}
foreach d $duts {
  lassign $d label top define
  if {$only ne "" && [lsearch -exact $only $label] < 0} { continue }
  puts "=============== PEXT_RUN $label (top=$top define=$define) ==============="

  create_project -in_memory -force -part $part
  read_verilog -sv $rtl

  set args [list -top $top -part $part -mode out_of_context]
  if {$define ne "-"} { lappend args -verilog_define "PEXT_DUT=$define" }
  if {[catch {synth_design {*}$args} err]} {
    puts "PEXT_RESULT $label SYNTH_FAILED: $err"
    close_project
    continue
  }

  create_clock -name clk -period $period [get_ports clk]
  # every I/O port is registered inside the harness, so only reg -> reg matters;
  # leaving the ports unconstrained keeps them out of the reported worst path.

  opt_design
  place_design -quiet
  phys_opt_design -quiet
  route_design -quiet

  report_utilization -file $outdir/${label}_util.rpt
  report_timing -delay_type max -max_paths 5 -nworst 5 -path_type full_clock_expanded \
                -from [all_registers] -to [all_registers] -file $outdir/${label}_timing.rpt

  set luts [util_row $outdir/${label}_util.rpt "Slice LUTs"]
  set ffs  [util_row $outdir/${label}_util.rpt "Slice Registers"]
  set dsps [util_row $outdir/${label}_util.rpt "DSPs"]
  set lram [util_row $outdir/${label}_util.rpt "LUT as Memory"]
  set llog [util_row $outdir/${label}_util.rpt "LUT as Logic"]

  # worst reg -> reg path
  set paths [get_timing_paths -delay_type max -max_paths 1 -nworst 1 -from [all_registers] -to [all_registers]]
  if {[llength $paths] == 0} {
    puts "PEXT_RESULT $label lut=$luts ff=$ffs dsp=$dsps NO_TIMING_PATH"
  } else {
    set pth   [lindex $paths 0]
    set slack [get_property SLACK $pth]
    set dd    [get_property DATAPATH_DELAY $pth]
    set lvl   [get_property LOGIC_LEVELS $pth]
    set src   [get_property STARTPOINT_PIN $pth]
    set dst   [get_property ENDPOINT_PIN $pth]
    # split logic vs route out of the text report
    set fh [open $outdir/${label}_timing.rpt r]; set t [read $fh]; close $fh
    set lg "?"; set rt "?"
    if {[regexp {Data Path Delay:\s+([0-9.]+)ns\s+\(logic ([0-9.]+)ns.*route ([0-9.]+)ns} $t -> _dd _lg _rt]} {
      set lg $_lg; set rt $_rt
    }
    puts [format "PEXT_RESULT %s lut=%s lutlogic=%s lutmem=%s ff=%s dsp=%s slack=%.3f dpd=%.3f logic=%s route=%s levels=%s" \
          $label $luts $llog $lram $ffs $dsps $slack $dd $lg $rt $lvl]
    lappend summary [list $label $luts $llog $lram $ffs $dsps $slack $dd $lg $rt $lvl $src $dst]
  }
  close_project
}

set fh [open $outdir/summary.tsv w]
puts $fh "label\tlut\tlut_logic\tlut_mem\tff\tdsp\tslack_ns\tdatapath_ns\tlogic_ns\troute_ns\tlevels\tstart\tend"
foreach s $summary { puts $fh [join $s "\t"] }
close $fh
puts "PEXT_ALL_DONE period=$period n=[llength $summary] -> $outdir/summary.tsv"
exit
