#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Exhaustive bit-exactness gate for the integer batchnorm2d_s8 / add_s8 curated kernels.

Reads a model's exported graph.json + weights.npz, pulls out the REAL per-channel
batchnorm parameters and the REAL add scale triples, and enumerates the entire input
domain of both kernels against ModelBlaster's own float reference expression.

See check_dronet_integer.c for why "the entire input domain" is a finite thing here and
why the claim is deliberately model-specific.  In one line: these two kernels are
numeric_drift in general -- PEXT_SPEC.md section 1.5 says so and is right -- and the only
honest way to use them is to prove, per model, that the general drift does not occur on
that model's parameters.  This is that proof, and it must be re-run after any
recalibration.

The oracle is KernelSpec.reference_impl, emitted VERBATIM, and the kernels under test are
the shipped .c files, #included by the C driver.  Neither side is a transcription.

Usage:
    python3 check_dronet_integer.py --ir <dir with graph.json + weights.npz>
                                    [--kernels-dir <curated .../pext>]
                                    [--build-dir DIR] [--json OUT]
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MBDIR = os.path.dirname(HERE)                       # fpga/pynq-z2/modelblaster
FPGA = os.path.dirname(MBDIR)                       # fpga/pynq-z2
ROOT = os.path.dirname(os.path.dirname(FPGA))       # repo root
ZCS = os.environ.get("ZCS", os.path.join(ROOT, "zephyr-chipyard-sw"))
CC = os.environ.get("HOST_CC", "cc")

DEFAULT_KERNELS = os.path.join(MBDIR, "kernels_dronet", "pext")


def emit_params(ir_dir: str, out_h: str) -> dict:
    import numpy as np
    g = json.load(open(os.path.join(ir_dir, "graph.json")))
    W = np.load(os.path.join(ir_dir, "weights.npz"))
    bns = [n for n in g["ops"] if n["op"] == "batchnorm2d_s8"]
    adds = [n for n in g["ops"] if n["op"] == "add_s8"]
    if not bns and not adds:
        raise SystemExit("graph has no batchnorm2d_s8 and no add_s8 -- nothing to check")

    L = ["/* @generated by check_dronet_integer.py -- do not edit */",
         "#include <stdint.h>", ""]
    for i, n in enumerate(bns):
        sc = W[n["weight"]].astype("float32").ravel()
        bi = W[n["bias"]].astype("float32").ravel()
        L.append("static const float bn%d_sc[] = {%s};"
                 % (i, ",".join("%.9gf" % v for v in sc)))
        L.append("static const float bn%d_bi[] = {%s};"
                 % (i, ",".join("%.9gf" % v for v in bi)))
    L += ["typedef struct { const char *name; int C; float scale_in, scale_out;",
          "                 int amin, amax; const float *sc; const float *bi; } bn_t;",
          "static const bn_t BNS[] = {"]
    for i, n in enumerate(bns):
        q, s = n["quant"], n["shape"]
        L.append('  {"%s",%d,%.9gf,%.9gf,%d,%d,bn%d_sc,bn%d_bi},'
                 % (n["name"], s["C"], q["scale_in"], q["scale_out"],
                    q["activation_min"], q["activation_max"], i, i))
    L += ["};",
          "typedef struct { const char *name; int n; float sa, sb, so;",
          "                 int amin, amax; } add_t;",
          "static const add_t ADDS[] = {"]
    for n in adds:
        q = n["quant"]
        L.append('  {"%s",%d,%.9gf,%.9gf,%.9gf,%d,%d},'
                 % (n["name"], n["shape"]["n"], q["scale_a"], q["scale_b"],
                    q["scale_out"], q["activation_min"], q["activation_max"]))
    L.append("};")
    open(out_h, "w").write("\n".join(L) + "\n")
    return {"batchnorm_dispatches": len(bns), "add_dispatches": len(adds),
            "batchnorm_channels": sum(n["shape"]["C"] for n in bns),
            "bn_cases": sum(n["shape"]["C"] for n in bns) * 256,
            "add_cases": len(adds) * 65536}


def emit_reference(out_c: str) -> None:
    """KernelSpec.reference_impl for both ops, verbatim -- the pipeline's own oracle."""
    sys.path.insert(0, ZCS)
    from modelblaster.pipeline import reference_kernels as rk
    parts = ["/* @generated: ModelBlaster's KernelSpec.reference_impl, VERBATIM. */",
             "#include <stddef.h>", "#include <stdint.h>", "#include <math.h>", ""]
    for spec in (rk.BATCHNORM2D_S8, rk.ADD_S8):
        parts.append(spec.reference_impl)
        parts.append("")
    open(out_c, "w").write("\n".join(parts))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True,
                    help="directory holding graph.json and weights.npz")
    ap.add_argument("--kernels-dir", default=DEFAULT_KERNELS)
    ap.add_argument("--build-dir", default=os.path.join(ROOT, "out", "dronet_integer_check"))
    ap.add_argument("--json", default=None)
    a = ap.parse_args()

    os.makedirs(a.build_dir, exist_ok=True)
    hdr = os.path.join(a.build_dir, "dronet_params.h")
    refc = os.path.join(a.build_dir, "ref_kernels.c")
    exe = os.path.join(a.build_dir, "check_dronet_integer")

    meta = emit_params(a.ir, hdr)
    emit_reference(refc)
    print(f"  graph: {meta['batchnorm_dispatches']} batchnorm dispatches "
          f"({meta['batchnorm_channels']} channels), {meta['add_dispatches']} add dispatches")
    print(f"  domain: {meta['bn_cases']:,} batchnorm cases + {meta['add_cases']:,} add cases "
          f"= the whole input space of both kernels")

    bn_k = os.path.join(a.kernels_dir, "pext_batchnorm2d_s8_direct.c")
    add_k = os.path.join(a.kernels_dir, "pext_add_s8_direct.c")
    for p in (bn_k, add_k):
        if not os.path.exists(p):
            raise SystemExit(f"curated kernel not found: {p}")

    # The oracle and the kernels define the same symbol names, so each side is compiled
    # as its own TU with its own renaming -D and the two are linked together.  The
    # oracle's shift-by-negative branch is UB in a branch no model takes, hence the
    # narrow -fno-sanitize allowance used by check_bitexact.py for the same reason.
    ref_o = os.path.join(a.build_dir, "ref_kernels.o")
    subprocess.run([CC, "-O2", "-std=c11", "-c",
                    "-Dkernel_batchnorm2d_s8=ref_kernel_batchnorm2d_s8",
                    "-Dkernel_add_s8=ref_kernel_add_s8",
                    refc, "-o", ref_o], check=True)
    subprocess.run([CC, "-O2", "-std=c11", "-Wall", f"-I{a.build_dir}", f"-I{HERE}",
                    "-Dkernel_batchnorm2d_s8=cur_kernel_batchnorm2d_s8",
                    "-Dkernel_add_s8=cur_kernel_add_s8",
                    os.path.join(HERE, "check_dronet_integer.c"), bn_k, add_k,
                    ref_o, "-o", exe, "-lm"], check=True)

    proc = subprocess.run([exe], text=True, capture_output=True)
    print(proc.stdout, end="")
    if proc.stderr:
        print(proc.stderr, file=sys.stderr)
    ok = proc.returncode == 0 and "RESULT: PASS" in proc.stdout
    if a.json:
        meta["result"] = "PASS" if ok else "FAIL"
        meta["stdout"] = proc.stdout
        json.dump(meta, open(a.json, "w"), indent=2)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
