#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Prove the MBP curated kernels are bit-exact against ModelBlaster's reference.

Three checks, cheapest first, all on the build host with MB_PEXT_HW=0 -- i.e. against
pext.h's own software model of DOT8 / MAX8 / QMUL / CLIP8, which PEXT_SPEC.md section 3.5
makes the normative definition of the instructions.  No board, no simulator, no bitstream.

  1. ModelBlaster's own host verify (pipeline/verify_kernel.py) at atol = rtol = 0, on
     every shape the KernelSpec registers.  This is the pipeline's trusted oracle, called
     the way the pipeline calls it, so a pass here is a pass on the project's own terms.

  2. A stress sweep (stress_main.c) over what check 1 does not vary: the real LeNet and
     DroNet quant parameters, every output_shift including 0 and negative, all four
     clamp shapes including the ReLU fold that is the only user of MBP.MAX8 in a conv,
     non-zero zero points (which must be REFUSED and handed to the reference), every K
     residue class mod 8, padded/strided/dilated pooling, and eight starting alignments
     for every tensor.  Compiled with -fsanitize=address,undefined, and with
     MB_PEXT_LD8 / MB_PEXT_ST8 instrumented so a misaligned 8-byte access fails on x86
     -- the alignment contract cannot otherwise be tested off-target, because x86 does
     not trap and Rocket does.

  3. Whole-model LeNet: run the generated model.c end to end on the host with the
     reference kernels.c and again with the pext kernels.c, and compare every
     intermediate tensor and the final output element by element, against each other and
     against the baked int8 golden.  This is the acceptance criterion in its own terms --
     per dispatch, max_abs_err = 0.

Usage:
    python3 check_bitexact.py [--build-dir DIR] [--gen-dir DIR] [--pext-gen-dir DIR]
                              [--iters N] [--skip-model]
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MBDIR = os.path.dirname(HERE)                       # fpga/pynq-z2/modelblaster
FPGA = os.path.dirname(MBDIR)                       # fpga/pynq-z2
ROOT = os.path.dirname(os.path.dirname(FPGA))       # repo root
PEXT_H_DIR = os.path.join(FPGA, "sw")
KDIR = os.path.join(MBDIR, "kernels", "pext")
ZCS = os.environ.get("ZCS", os.path.join(ROOT, "zephyr-chipyard-sw"))

KERNELS = {
    "conv2d_s8": "pext_conv2d_s8_pext_patch_dot8.c",
    "linear_s8": "pext_linear_s8_pext_row_dot8.c",
    "maxpool2d_s8": "pext_maxpool2d_s8_pext_max8_rows.c",
}

CC = os.environ.get("HOST_CC", "cc")


def run(cmd, **kw):
    print("  $", " ".join(cmd))
    return subprocess.run(cmd, check=True, **kw)


# --------------------------------------------------------------------------
# 1. ModelBlaster's own host verify, at zero tolerance
# --------------------------------------------------------------------------
def check_pipeline_verify() -> bool:
    sys.path.insert(0, ZCS)
    os.environ["CPATH"] = (
        PEXT_H_DIR + (os.pathsep + os.environ["CPATH"] if os.environ.get("CPATH") else "")
    )
    from modelblaster.pipeline import reference_kernels as rk
    from modelblaster.pipeline.verify_kernel import verify

    specs = {
        "conv2d_s8": rk.CONV2D_S8,
        "linear_s8": rk.LINEAR_S8,
        "maxpool2d_s8": rk.MAXPOOL2D_S8,
    }
    ok = True
    for op, fname in KERNELS.items():
        spec = specs[op]
        src = open(os.path.join(KDIR, fname)).read()
        res = verify(spec, src, spec.extra_shapes, n_trials=5,
                     atol=0.0, rtol=0.0, seed=7)
        print(f"  {op:14s} {'PASS' if res.ok else 'FAIL'}  {res.message.splitlines()[0]}")
        ok = ok and res.ok
    return ok


# --------------------------------------------------------------------------
# 2. The stress sweep
# --------------------------------------------------------------------------
def emit_reference_tu(path: str) -> None:
    """Write ModelBlaster's reference_impl for the three ops, verbatim, as one TU."""
    sys.path.insert(0, ZCS)
    from modelblaster.pipeline import reference_kernels as rk

    parts = [
        "/* @generated by fpga/pynq-z2/modelblaster/check/check_bitexact.py.\n"
        " * ModelBlaster's KernelSpec.reference_impl for each op, VERBATIM -- the\n"
        " * pipeline's own trusted oracle, not a paraphrase of it.  Renamed to\n"
        " * ref_kernel_<op> on the command line so the kernels under test can live in\n"
        " * the same program. */",
        "#include <stddef.h>",
        "#include <float.h>",
        "#include <stdint.h>",
        "#include <math.h>",
        "",
    ]
    for spec in (rk.CONV2D_S8, rk.LINEAR_S8, rk.MAXPOOL2D_S8):
        parts.append(spec.reference_impl.rstrip())
        parts.append("")
    with open(path, "w") as f:
        f.write("\n".join(parts))


def check_stress(build: str, iters: int) -> bool:
    ref_c = os.path.join(build, "ref_kernels.c")
    emit_reference_tu(ref_c)
    ref_o = os.path.join(build, "ref_kernels.o")
    san = ["-fsanitize=address,undefined", "-fno-sanitize-recover=all"]
    # -fno-sanitize=shift on the ORACLE only.  ModelBlaster's reference expression is
    # `scaled = scaled << (-output_shift)` on a signed int32, which is undefined
    # behaviour when `scaled` is negative -- UBSan reports it, correctly, on the
    # reference and not on the kernel under test.  The exporter never emits a negative
    # output_shift (PEXT_SPEC.md 1.2: every DroNet and LeNet shift is positive), so this
    # is a latent defect in a branch no model takes, not something to fix from here.
    # The sweep keeps negative shifts anyway: the kernel implements that branch as a
    # well-defined unsigned shift, and the point is to confirm it agrees with what the
    # compiler actually emits for the reference.  The check is disabled for one file,
    # never silenced globally, and ASan stays on for both.
    run([CC, "-O1", "-g", "-std=c99", "-Wall", "-Wextra", "-Wno-unused-parameter"] + san +
        ["-fno-sanitize=shift",
         "-Dkernel_conv2d_s8=ref_kernel_conv2d_s8",
         "-Dkernel_linear_s8=ref_kernel_linear_s8",
         "-Dkernel_maxpool2d_s8=ref_kernel_maxpool2d_s8",
         "-c", ref_c, "-o", ref_o])
    exe = os.path.join(build, "stress")
    run([CC, "-O1", "-g", "-std=c99", "-Wall", "-Wextra"] + san +
        [f"-I{PEXT_H_DIR}", f"-I{KDIR}",
         os.path.join(HERE, "stress_main.c"), ref_o, "-o", exe])
    proc = subprocess.run([exe, str(iters), "1"], text=True, capture_output=True)
    sys.stdout.write("".join("  " + l + "\n" for l in proc.stdout.strip().splitlines()))
    if proc.stderr.strip():
        sys.stderr.write(proc.stderr[:4000])
    return proc.returncode == 0


# --------------------------------------------------------------------------
# 3. Whole-model LeNet, both kernel sets, every intermediate compared
# --------------------------------------------------------------------------
SHIM = """/* Minimal <zephyr/kernel.h> so ModelBlaster's generated model.c -- which is
 * unmodified -- builds and runs on the host.  It uses exactly one thing from Zephyr:
 * k_cycle_get_64(), for the wall-clock cross-check.  Nothing here is timed. */
#ifndef MB_HOST_ZEPHYR_SHIM_H_
#define MB_HOST_ZEPHYR_SHIM_H_
#include <stdint.h>
static inline uint64_t k_cycle_get_64(void) { return 0; }
#endif
"""

DUMPER = """/* @generated by check_bitexact.py -- runs the model once on its baked test input and
 * writes every intermediate tensor and the output to one file, in dispatch order. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "model.h"
#include "test_io.h"

%(externs)s

int main(int argc, char **argv) {
    static int8_t out[MODEL_LENET_TEST_OUTPUT_LEN];
    FILE *f;
    if (argc < 2) return 2;
    memset(out, 0, sizeof out);
    model_lenet_run_test(out, 0);
    f = fopen(argv[1], "wb");
    if (!f) return 2;
%(writes)s
    fwrite(out, 1, sizeof out, f);
    fclose(f);
    return 0;
}
"""


def _buffers(gen: str):
    """(name, size) for each buffer buffers.c defines, in file order."""
    out = []
    for line in open(os.path.join(gen, "buffers.c")):
        line = line.strip()
        if line.startswith("int8_t buf_") and "[" in line:
            name = line.split()[1].split("[")[0]
            size = int(line.split("[")[1].split("]")[0])
            out.append((name, size))
    return out


def build_model(build: str, gen: str, kernels_c: str, label: str, extra_cflags=()):
    """Build the generated LeNet with one kernels.c, and return the dump path."""
    d = os.path.join(build, label)
    os.makedirs(os.path.join(d, "zephyr"), exist_ok=True)
    with open(os.path.join(d, "zephyr", "kernel.h"), "w") as f:
        f.write(SHIM)
    bufs = _buffers(gen)
    externs = "\n".join(f"extern int8_t {n}[{s}];" for n, s in bufs)
    writes = "\n".join(f'    fwrite({n}, 1, {s}, f);' for n, s in bufs)
    with open(os.path.join(d, "dump.c"), "w") as f:
        f.write(DUMPER % {"externs": externs, "writes": writes})
    exe = os.path.join(d, "model")
    srcs = [os.path.join(d, "dump.c"),
            os.path.join(gen, "model.c"), kernels_c,
            os.path.join(gen, "weights.c"), os.path.join(gen, "buffers.c"),
            os.path.join(gen, "test_io.S")]
    run([CC, "-O2", "-g", "-w", f"-I{d}", f"-I{gen}", f"-I{PEXT_H_DIR}",
         *extra_cflags, *srcs, "-o", exe, "-lm"])
    dump = os.path.join(d, "dump.bin")
    run([exe, dump])
    return dump, bufs


def check_model(build: str, gen_ref: str, gen_pext: str) -> bool:
    print(f"  reference gen: {gen_ref}")
    print(f"  pext gen:      {gen_pext}")
    d_ref, bufs = build_model(build, gen_ref,
                              os.path.join(gen_ref, "kernels.c"), "ref")
    d_pext, _ = build_model(build, gen_pext,
                            os.path.join(gen_pext, "kernels.c"), "pext")
    a = open(d_ref, "rb").read()
    b = open(d_pext, "rb").read()
    if len(a) != len(b):
        print(f"  FAIL: dump sizes differ ({len(a)} vs {len(b)})")
        return False

    # Which dispatch writes which buffer, straight out of the IR.
    import json
    ir = os.path.join(os.path.dirname(gen_ref), "ir", "graph.json")
    owner = {}
    if os.path.exists(ir):
        g = json.load(open(ir))
        for op in g["ops"]:
            if op.get("dispatch_id") is None:
                continue
            for t in op["outputs"]:
                owner[f"buf_{g['name']}_{t}"] = f"{op['name']} ({op['op']})"

    ok = True
    off = 0
    rows = []
    for name, size in bufs:
        ra, rb = a[off:off + size], b[off:off + size]
        err = max((abs(x - y) for x, y in zip(ra, rb)), default=0)
        rows.append((owner.get(name, "-- unused --"), name, size, err))
        ok = ok and err == 0
        off += size
    golden = open(os.path.join(gen_ref, "test_golden.bin"), "rb").read()
    out_ref, out_pext = a[off:], b[off:]
    err_out = max((abs(x - y) for x, y in zip(out_ref, out_pext)), default=0)
    err_gold_ref = max((abs(x - y) for x, y in zip(out_ref, golden)), default=0)
    err_gold_pext = max((abs(x - y) for x, y in zip(out_pext, golden)), default=0)

    w = max(len(r[0]) for r in rows)
    for dispatch, name, size, err in rows:
        print(f"  {dispatch:<{w}}  {name:<22} {size:6d} B   max_abs_err={err}")
    print(f"  {'model output':<{w}}  {'(fc3)':<22} {len(out_ref):6d} B   "
          f"max_abs_err={err_out}")
    print(f"  vs baked int8 golden: reference max_abs_err={err_gold_ref}, "
          f"pext max_abs_err={err_gold_pext}")
    ok = ok and err_out == 0 and err_gold_ref == 0 and err_gold_pext == 0
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir",
                    default=os.path.join(ROOT, "out", "pext_check"))
    ap.add_argument("--gen-dir",
                    default=os.path.join(ROOT, "out", "rocket_mb_lenet_int8",
                                         "model", "gen"),
                    help="generated C from the SCALAR baseline run")
    ap.add_argument("--pext-gen-dir",
                    default=os.path.join(ROOT, "out", "rocket_mb_lenet_int8_pext",
                                         "model", "gen"),
                    help="generated C from the PEXT run")
    ap.add_argument("--iters", type=int, default=400)
    ap.add_argument("--skip-model", action="store_true")
    args = ap.parse_args()

    build = args.build_dir
    if os.path.isdir(build):
        shutil.rmtree(build)
    os.makedirs(build)

    ok = True
    print("[1/3] ModelBlaster host verify, atol=rtol=0, KernelSpec shapes")
    ok &= check_pipeline_verify()

    print("[2/3] stress sweep (quant params, clamps, offsets, alignment, ASan+UBSan)")
    ok &= check_stress(build, args.iters)

    if not args.skip_model:
        print("[3/3] whole-model LeNet, reference kernels vs pext kernels")
        if not os.path.isdir(args.pext_gen_dir):
            print(f"  SKIP: no pext codegen at {args.pext_gen_dir} "
                  f"(run scripts/28_rocket_modelblaster_pext.sh --build-only first)")
            ok = False
        else:
            ok &= check_model(build, args.gen_dir, args.pext_gen_dir)
    else:
        print("[3/3] whole-model LeNet -- skipped by request")

    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
